# Das Lineare Modell und Erweiterungen

Im folgenden wird das Modell der einfachen linearen Regression erweitert indem zusätzliche Terme in das Modell aufgenommen werden. Die Prinzipien bleiben dabei jedoch weitestgehend enthalten und können direkt auf den komplizierteren Fall der multiplen Regression übertragen werden. Die Erweiterung zeigen, dass neben mehreren kontinuierlichen Variablen auch nominale Faktoren in das Modell integriert werden können. Daraus entsteht insgesamt ein sehr flexibler Modellapparat, der in den verschiedensten Zusammenhängen angewendet werden kann und letztendlich im Linearen Modell aufgeht. Dies wird anschließend erweitert zum Generalisierten Linearen Modell (engl. Generalized Linear Modell; GLS) in Form der Logistischen Regression bei dem die abhängige Variable nur zwei Werte annehmen kann und damit nicht mehr kontinuierlich ist und zum Gemischten Linearen Modell (engl. Linear-mixed Modell; LLM) bei dem die einzelnen Datenpunkte nicht mehr unabhängig voneinander sein müssen. Die Anwendung des Gemischten Linearen Modells hat in den letzten Jahren sehr stark an Bedeutung zugenommen und kann heutzutage als Standardanalysemethode angesehen werden.
