<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Multiple Lineare Regression – Skriptum - SBT4 Quantitatitve Methoden</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./mlm_logistic.html" rel="next">
<link href="./mlm_title.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-631496449bf32ff9b0bb69a6bfd9195d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>
<script>

  MathJax = {

    tex: {

      tags: 'ams'  // should be 'ams', 'none', or 'all'

    }

  };

</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./mlm_title.html">Das Lineare Modell und Erweiterungen</a></li><li class="breadcrumb-item"><a href="./mlm_basics.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Lineare Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skriptum - SBT4 Quantitatitve Methoden</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stats_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistik - Die Grundlagen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Eine kleine Welt der Unsicherheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistische Signifikanz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Hypothesentests</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./slm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das einfache Regressionsmodell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Grundlagen und Inferenz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_model_fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modellfit und Vorhersage</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./mlm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das Lineare Modell und Erweiterungen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_basics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_lmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Gemischte Lineare Modelle</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./ed_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Grundlagen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Messfehler und Reliabilität</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Experimentelle Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_causal_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kausale Inferenz</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literatur</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#bedeutung-der-koeffizienten-bei-der-multiplen-regression" id="toc-bedeutung-der-koeffizienten-bei-der-multiplen-regression" class="nav-link active" data-scroll-target="#bedeutung-der-koeffizienten-bei-der-multiplen-regression"><span class="header-section-number">6.1</span> Bedeutung der Koeffizienten bei der multiplen Regression</a>
  <ul class="collapse">
  <li><a href="#added-variable-plots" id="toc-added-variable-plots" class="nav-link" data-scroll-target="#added-variable-plots"><span class="header-section-number">6.1.1</span> Added-variable plots</a></li>
  <li><a href="#was-passiert-wenn-eine-prädiktorvariable-weggelassen-wird" id="toc-was-passiert-wenn-eine-prädiktorvariable-weggelassen-wird" class="nav-link" data-scroll-target="#was-passiert-wenn-eine-prädiktorvariable-weggelassen-wird"><span class="header-section-number">6.1.2</span> Was passiert wenn eine Prädiktorvariable weggelassen wird?</a></li>
  </ul></li>
  <li><a href="#multikollinearität" id="toc-multikollinearität" class="nav-link" data-scroll-target="#multikollinearität"><span class="header-section-number">6.2</span> Multikollinearität</a>
  <ul class="collapse">
  <li><a href="#take-away" id="toc-take-away" class="nav-link" data-scroll-target="#take-away"><span class="header-section-number">6.2.1</span> Take-away</a></li>
  </ul></li>
  <li><a href="#interaktionseffekte" id="toc-interaktionseffekte" class="nav-link" data-scroll-target="#interaktionseffekte"><span class="header-section-number">6.3</span> Interaktionseffekte</a>
  <ul class="collapse">
  <li><a href="#take-away-1" id="toc-take-away-1" class="nav-link" data-scroll-target="#take-away-1"><span class="header-section-number">6.3.1</span> Take-away</a></li>
  </ul></li>
  <li><a href="#nominale-variablen-im-modell" id="toc-nominale-variablen-im-modell" class="nav-link" data-scroll-target="#nominale-variablen-im-modell"><span class="header-section-number">6.4</span> Nominale Variablen im Modell</a></li>
  <li><a href="#kombination-von-kontinuierlichen-und-nominalen-prädiktorvariablen" id="toc-kombination-von-kontinuierlichen-und-nominalen-prädiktorvariablen" class="nav-link" data-scroll-target="#kombination-von-kontinuierlichen-und-nominalen-prädiktorvariablen"><span class="header-section-number">6.5</span> Kombination von kontinuierlichen und nominalen Prädiktorvariablen</a>
  <ul class="collapse">
  <li><a href="#take-away-2" id="toc-take-away-2" class="nav-link" data-scroll-target="#take-away-2"><span class="header-section-number">6.5.1</span> Take-away</a></li>
  </ul></li>
  <li><a href="#genereller-linearer-modell-testansatz" id="toc-genereller-linearer-modell-testansatz" class="nav-link" data-scroll-target="#genereller-linearer-modell-testansatz"><span class="header-section-number">6.6</span> Genereller Linearer Modell Testansatz</a></li>
  <li><a href="#zum-weiterlesen" id="toc-zum-weiterlesen" class="nav-link" data-scroll-target="#zum-weiterlesen"><span class="header-section-number">6.7</span> Zum Weiterlesen</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./mlm_title.html">Das Lineare Modell und Erweiterungen</a></li><li class="breadcrumb-item"><a href="./mlm_basics.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Lineare Regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Lineare Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In den meisten Fällen in der Praxis liegt selten der einfache Fall vor, dass eine abhängige Variable mittels nur einer einzigen Prädiktorvariablen erklärt bzw. vorhergesagt werden soll. In den meisten Fällen liegt das Interesse darin den Zusammenhang mehrerer Prädiktorvariablen auf die abhängige Variable zu zu modellieren. Ein Beispiel aus der Literatur ist eine Untersuchung von <span class="citation" data-cites="debanne2011">Debanne und Laffaye (<a href="references.html#ref-debanne2011" role="doc-biblioref">2011</a>)</span> über den Zusammenhang zwischen der Wurfgeschwindigkeit in Abhängigkeit vom Körpergewicht und der Armspannweite im Handball. In <a href="#tbl-debanne-2011" class="quarto-xref">Tabelle&nbsp;<span>6.1</span></a> ist ein Ausschnitt aus dem Datensatz abgebildet.</p>
<div class="cell">
<div id="tbl-debanne-2011" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-debanne-2011-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.1: Datenausschnitt: Wurfgeschwindigkeit, Körpermasse und Armspannweite bei professionellen Handballern (angelehnt an Debanne &amp; Laffaye, 2011).
</figcaption>
<div aria-describedby="tbl-debanne-2011-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Velocity[m/s]</th>
<th style="text-align: right;">body mass[kg]</th>
<th style="text-align: right;">arm span[cm]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">15.8</td>
<td style="text-align: right;">70.7</td>
<td style="text-align: right;">189.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">17.2</td>
<td style="text-align: right;">63.7</td>
<td style="text-align: right;">182.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">18.3</td>
<td style="text-align: right;">76.2</td>
<td style="text-align: right;">192.1</td>
</tr>
<tr class="even">
<td style="text-align: right;">18.4</td>
<td style="text-align: right;">64.9</td>
<td style="text-align: right;">171.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">18.4</td>
<td style="text-align: right;">63.0</td>
<td style="text-align: right;">181.1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Im Prinzip ändert sich an der Art der Daten nichts gegenüber der einfachen Regression. Die Daten beinhalten lediglich nun eine weitere Spalten mit einer weiteren Prädiktorvariablen. Im Prinzip könnte der isolierte Einfluss der beiden Prädiktorvariablen Körpermasse und Armspannweite auf die abhängige Variable Wurfgeschwindigkeit einzeln untersucht werden. Allerdings ist oft von größerem Interesse zu untersuchen, wie sich der gemeinsame Einfluss der beiden Variablen zusammen verhält und ob durch die Kombination der beiden Variablen ein <em>besseres</em> Modell erstellt werden kann. Aus dieser Problemstellung heraus ergibt sich die Notwendigkeit von der einfachen linearen Regression zur <strong>multiplen linearen Regression</strong> überzugehen. Formal geschieht dies einfach dadurch, dass die Formel der einfachen Regression mit dem Prädiktor <span class="math inline">\(X\)</span> um eine weitere oder eben mehrere Variablen erweitert wird. Dementsprechend wird aus:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\]</span></p>
<p>die Formel für die multiple Regression mit:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \dots + \beta_K x_{Ki} + \epsilon_i
\]</span></p>
<p>Da bei der einfachen Regression nur eine einzige <span class="math inline">\(X\)</span>-Variable in der Formel vorhanden war, ist kein Index <span class="math inline">\(j\)</span> notwendig gewesen um die <span class="math inline">\(X\)</span>-Variablen voneinander zu unterscheiden. Bei der multiplen Regression mit mehreren Prädiktorvariablen <span class="math inline">\(X\)</span> wird jeder <span class="math inline">\(X\)</span> Variable ein zusätzlicher Index <span class="math inline">\(j\)</span> angehängt um die Variablen eindeutig identifizieren zu können. Per Konvention, wobei diese leider nicht global eingehalten wird, wird die <strong>Anzahl der Prädiktorvariablen</strong> mit <span class="math inline">\(K\)</span> bezeichnet (oft auch <span class="math inline">\(p\)</span>). Der <span class="math inline">\(y\)</span>-Achsenabschnitt erhält wieder den Index <span class="math inline">\(j=0\)</span> und die weiteren Steigungskoeffzienten <span class="math inline">\(\beta_1\)</span> bis <span class="math inline">\(\beta_K\)</span> erhalten den Prädiktorvariablen <span class="math inline">\(X_j\)</span> folgend den entsprechenden Index.</p>
<p>In welcher Reihenfolge die Prädiktorvariablen mit <span class="math inline">\(j=1, j=2, \ldots, j=K\)</span> verteilt werden hat zunächst keine Auswirkung auf das Modell und regelt lediglich die Bezeichnung. In unserem konkreten Fall der Handballwurfdaten wäre zum Beispiel eine mögliche Zuordnung, das <span class="math inline">\(X_1\)</span> die Körpermasse und <span class="math inline">\(X_2\)</span> die Armspannweite kodiert.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(i\)</span></th>
<th style="text-align: right;">Velocity[m/s]</th>
<th style="text-align: right;">body mass[kg] <span class="math inline">\(j=1\)</span></th>
<th style="text-align: right;">arm span[cm] <span class="math inline">\(j=2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">15.8</td>
<td style="text-align: right;">70.7</td>
<td style="text-align: right;">189.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">17.2</td>
<td style="text-align: right;">63.7</td>
<td style="text-align: right;">182.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">18.3</td>
<td style="text-align: right;">76.2</td>
<td style="text-align: right;">192.1</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">18.4</td>
<td style="text-align: right;">64.9</td>
<td style="text-align: right;">171.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">18.4</td>
<td style="text-align: right;">63.0</td>
<td style="text-align: right;">181.1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Rein formal hat sich nun der Übergang zur multiple Regression bereits vollzogen. Die Frage die sich nun direkt anschließt bezieht sich auf die Bedeutung der Koeffizienten <span class="math inline">\(\beta_1, \ldots, \beta_k\)</span>. Sind diese ebenfalls als Steigungen einer Geraden zu interpretieren? Ebenso, wie lassen sich die anderen Konzepte die bereits im Rahmen der einfachen Regression behandelt wurden haben auf die multiple Regression übertragen? Zunächst aber noch ein Beispiel.</p>
<div id="exm-rowing-example-01" class="theorem example">
<p><span class="theorem-title"><strong>Beispiel 6.1</strong></span> In <span class="citation" data-cites="riechman2002">Riechman u.&nbsp;a. (<a href="references.html#ref-riechman2002" role="doc-biblioref">2002</a>)</span> wurde ein Modell erstellt um die Leistung beim 2000m Indoor-Rudern von 12 Wettkampfruderinnen anhand eines 30-Sekunden-Ruder-Sprints, der maximalen Sauerstoffaufnahme und der Ermüdung vorherzusagen. Die Autoren bestimmten das folgende Modell: <span class="math display">\[\begin{equation*}
Zeit_{\text{2000m}} = 567.29-0.163\cdot\text{Power }-14.213\cdot \dot{V}0_{2\text{max}} + 0.738\cdot\text{Fatigue}
\end{equation*}\]</span> Mit einem Standardfehler von <span class="math inline">\(\hat{\sigma} = 0.96\)</span>.</p>
</div>
<section id="bedeutung-der-koeffizienten-bei-der-multiplen-regression" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="bedeutung-der-koeffizienten-bei-der-multiplen-regression"><span class="header-section-number">6.1</span> Bedeutung der Koeffizienten bei der multiplen Regression</h2>
<p>Um die Bedeutung der Regressionskoeffzienten bei der multiple Regression besser zu verstehen ist es von Vorteil sich noch einmal die Bedeutung der Koeffizienten im einfachen Regressionsmodell zu vergegenwärtigen (siehe <a href="#fig-mlm-basics-simple" class="quarto-xref">Abbildung&nbsp;<span>6.1</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-basics-simple" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-basics-simple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-simple-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-basics-simple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.1: Beispiel für eine einfache Regression und der resultierenden Regressiongeraden
</figcaption>
</figure>
</div>
</div>
</div>
<p>Bei der einfachen Regression wurde mittels der Methode der kleinsten Quadrate eine Regressionsgerade durch die Punktwolke der Daten gelegt. Dabei wurde die Regressionsgerade so gewählt, dass die senkrechten Abstände der beobachteten Punkte von der Regressionsgerade minimiert werden bzw. die Abstände zwischen denen auf der Gerade liegenden, vorhergesagten Werte <span class="math inline">\(\hat{y}_i\)</span> und den beobachteten Wert <span class="math inline">\(Y_i\)</span> (Residuen). Wird nun der Übergang von einer Prädiktorvariablen zum nächstkomplizierteren Fall mit zwei Prädiktorvariablen <span class="math inline">\(X_1\)</span> und <span class="math inline">\(X_2\)</span> durchgeführt, dann ist eine mögliche Darstellungsform der Daten eine Punktwolke im dreidimensionalen Raum (siehe <a href="#fig-mlm-basics-scatter-1" class="quarto-xref">Abbildung&nbsp;<span>6.2 (a)</span></a>).</p>
<div id="fig-mlm-basics-scatter" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-basics-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-basics-scatter" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-basics-scatter-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-basics-scatter-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-scatter-1.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-basics-scatter" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-basics-scatter-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) 3D Punktwolke
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-basics-scatter" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-basics-scatter-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-basics-scatter-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-scatter-2.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-basics-scatter" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-basics-scatter-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) 3D Punktwolke mit gefitteter Ebene
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-basics-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.2: Punktwolken bei der multiple Regression
</figcaption>
</figure>
</div>
<p>Da jetzt eine einzelne Gerade nicht mehr ausreichend ist um die Daten zu fitten, wird nun eine <strong>Ebene</strong> durch die Punktwolke gelegt (siehe <a href="#fig-mlm-basics-scatter-2" class="quarto-xref">Abbildung&nbsp;<span>6.2 (b)</span></a>). Dieser Ansatz ermöglicht nun die gleiche Herangehensweise wie bei der einfachen linearen Regression anzuwenden. Als Zielgröße wird aus den möglichen Ebenen diejenigen Ebene gesucht, deren vorhergesagte, in der Ebene liegende, Punkte <span class="math inline">\(\hat{y}_i\)</span> die geringsten, senkrechten Abstand zu den tatsächlich beobachteten Punkten <span class="math inline">\(y_i\)</span> haben (wieder Residuen). Anders ausgedrückt, es wird diejenigen Ebene durch die Punktwolke gesucht deren Summe der quadrierten Residuen <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span> minimal ist. Die Definition der Residuen ist dabei genau gleich derjenigen bei der einfachen linearen Regression.</p>
<p>Diese Herangehensweise hat den Vorteil, dass sie zum einem die einfache lineare Regression als Spezialfall mit <span class="math inline">\(K=1\)</span> beinhaltet und sich beliebig erweitern lässt. Lediglich mit der Einschränkung, dass bei <span class="math inline">\(K&gt;2\)</span> die dreidimensionale Darstellung mittels einer Grafik nicht mehr möglich ist da nicht ausreichend Dimensionen dargestellt werden können. Das Prinzip der Minimierung der Abweichungen von <span class="math inline">\(\hat{y}_i\)</span> zu <span class="math inline">\(y\)</span> von einer Ebene bleibt aber weiter erhalten. D.h. alle Konzepte die im Rahmen der einfachen linearen Regression erarbeitet wurden, lassen sich direkt auf die multiple lineare Regression übertragen.</p>
<p>Zusammenfassend:</p>
<ul>
<li>Die Berechnungen beim Übergang von der einfachen zur multiplen Regression bleiben alle gleich</li>
<li>Die Abweichungen, die Residuen <span class="math inline">\(\hat{\epsilon_i}\)</span> sind nun nicht mehr Abweichungen von einer Gerade sondern von einer <span class="math inline">\(K\)</span>-dimensionalen Hyperebene. Die grundlegenden Eigenschaften der Residuen bleiben alle erhalten.</li>
<li>Die Modellannahmen bleiben alle gleich: Unabhängige <span class="math inline">\(y_i\)</span> und <span class="math inline">\(\epsilon_i \sim \mathcal{N}(0,\sigma^2)\)</span> iid</li>
<li>Inferenz für die Koeffizienten mittels <span class="math inline">\(t_k = \frac{\hat{\beta}_k}{s_k} \sim t(N-K-1)\)</span> bleiben erhalten und übertragen sich auf die Konfidenzintervalle</li>
<li>Alle Konzepte für die Vorhersage bleiben erhalten</li>
<li>Modelldiagnosetools bleiben ebenfalls alle erhalten</li>
</ul>
<p>Die Interpretation von <span class="math inline">\(\beta_0\)</span> ist vollkommen identisch mit derjenigen bei der einfachen linearen Regression. Bei der einfachen linearen Regression bedeutete der Koeffizient <span class="math inline">\(\beta_0\)</span> derjenige Wert, den das Modell annimmt, der vorhergesagte Wert <span class="math inline">\(\hat{Y}\)</span>, wenn die Prädiktorvariable <span class="math inline">\(X\)</span> den Wert <span class="math inline">\(0\)</span> annimmt. Graphisch ist dies der <span class="math inline">\(y\)</span>-Achsenabschnitt. Bei der multiplen Regression bleibt diese Interpretation erhalten und <span class="math inline">\(\beta_0\)</span> ist nun der Wert <span class="math inline">\(\hat{Y}\)</span> wenn <strong>alle</strong> Prädiktorvariablen den Wert <span class="math inline">\(0\)</span> annehmen. Graphisch ist dies der Schnittpunkt der Modellebene mit der <span class="math inline">\(y\)</span>-Achse, also ebenfalls der <span class="math inline">\(y\)</span>-Achsenabschnitt (siehe <a href="#fig-mlm-basics-scatter-2" class="quarto-xref">Abbildung&nbsp;<span>6.2 (b)</span></a>).</p>
<p>Die Interpretation der Modellkoeffizienten <span class="math inline">\(\beta_1, \beta_2, \ldots, \beta_K\)</span> bleibt zunächst auch gleich derjenigen aus der einfachen Regression. Der Koeffizient <span class="math inline">\(\beta_j, (j\neq0)\)</span> gibt den Unterschied zwischen zwei Objekten an die sich um eine Einheit bezüglich der Variablen <span class="math inline">\(X_j\)</span> unterscheiden. Der Steigungskoeffizient <span class="math inline">\(\beta_i\)</span> drückt dabei die Information der Variable <span class="math inline">\(X_i\)</span> aus, wenn der gemeinsame Anteil von <span class="math inline">\(X_i\)</span> mit allen anderen Prädiktorvariablen <span class="math inline">\(X_j, j \neq i\)</span> rausgerechnet, <em>bereinigt</em>, wurde. Anders ausgedrückt: Welche zusätzliche Information wird erhalten , wenn die Variable <span class="math inline">\(X_i\)</span> in das Modell integriert wird, wenn schon alle anderen Variablen <span class="math inline">\(X_j, j \neq i\)</span> im Modell enthalten sind. D.h., das multiple Regressionsmodell kontrolliert automatisch immer den Einfluss der anderen <span class="math inline">\(K-1\)</span> Variablen bei der Betrachtung der Variablen <span class="math inline">\(x_i\)</span>. Nochmal als Liste:</p>
<ul>
<li><span class="math inline">\(\hat{\beta}_1\)</span>: Wenn <span class="math inline">\(X_2\)</span> bekannt ist, welche zusätzlichen Informationen wird durch <span class="math inline">\(X_1\)</span> über <span class="math inline">\(Y\)</span> erhalten.</li>
<li><span class="math inline">\(\hat{\beta}_2\)</span>: Wenn <span class="math inline">\(X_1\)</span> bekannt ist, welche zusätzlichen Informationen wird durch <span class="math inline">\(X_2\)</span> über <span class="math inline">\(Y\)</span> erhalten.</li>
</ul>
<section id="added-variable-plots" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="added-variable-plots"><span class="header-section-number">6.1.1</span> Added-variable plots</h3>
<p>Die Idee hinter den sogenannten <em>added-variable plots</em> basiert auf den <em>isolierten</em> Einfluss einer Variable auf die abhängige Variable abzubilden. Dazu wird wieder eine einfache lineare Regression von <span class="math inline">\(Y\)</span> gegen <span class="math inline">\(X_1\)</span> berechnet und eine einfache Regression von <span class="math inline">\(X_1\)</span> auf <span class="math inline">\(X_2\)</span>. Von beiden Regressionen werden die resultierenden Residuen in einem Streudiagramm gegeneinander abgetragen (siehe <a href="#fig-mlm-basics-avplot-01" class="quarto-xref">Abbildung&nbsp;<span>6.3</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-basics-avplot-01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-basics-avplot-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-avplot-01-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-basics-avplot-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.3: Added-variable Plots der Handballdaten
</figcaption>
</figure>
</div>
</div>
</div>
<p>Wenn eine multiple Regression mit mehr als zwei Prädiktorvariablen gerechnet wird, dann werden im added-variable plot jeweils alle <span class="math inline">\(K-1\)</span> Variablen aus <span class="math inline">\(x_i\)</span> und <span class="math inline">\(y\)</span> herausgerechnet. D.h. <span class="math inline">\(Y\)</span> und <span class="math inline">\(X_i\)</span> werden um den Einfluss aller, verbleibenden <span class="math inline">\(X_j, j \neq i\)</span> bereinigt. Die Darstellung von added-variable plots ist daher im Zusammenhang einer multiplen Regressionsanalyse immer von Vorteil um den Einfluss einzelner Variablen auf die abhängige Variable zu beurteilen.</p>
<p>Da ein Steigungskoeffizientt <span class="math inline">\(\beta_i\)</span> immer den Beitrag der Information von <span class="math inline">\(X_i\)</span> über denjenigen der anderen Prädiktorvariablen hinaus bestimmt, stellt sich die Frage was passiert wenn im Modell eine oder mehrere Prädiktorvariablen weggelassen werden.</p>
</section>
<section id="was-passiert-wenn-eine-prädiktorvariable-weggelassen-wird" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="was-passiert-wenn-eine-prädiktorvariable-weggelassen-wird"><span class="header-section-number">6.1.2</span> Was passiert wenn eine Prädiktorvariable weggelassen wird?</h3>
<p>In <a href="#tbl-mlm-basics-modelfit-01" class="quarto-xref">Tabelle&nbsp;<span>6.2</span></a> sind Koeffizienten aus einem synthetischen Modell abgebildet.</p>
<div class="cell">
<div id="tbl-mlm-basics-modelfit-01" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-basics-modelfit-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.2: Koeffizienten im Beispielmodell.
</figcaption>
<div aria-describedby="tbl-mlm-basics-modelfit-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<caption>Modellfit</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.077</td>
<td style="text-align: right;">0.066</td>
</tr>
<tr class="even">
<td style="text-align: left;">x1</td>
<td style="text-align: right;">2.965</td>
<td style="text-align: right;">0.056</td>
</tr>
<tr class="odd">
<td style="text-align: left;">x2</td>
<td style="text-align: right;">0.708</td>
<td style="text-align: right;">0.060</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Was passiert nun, wenn anstatt einer multiplen Regression mit beiden Prädiktorvariablen zwei Einzelmodelle als einfache lineare Regression gefittet werden. Die Modell enthalten dabei jeweils mit eine der Prädiktorvariablen? Bleiben die Werte der Koeffizienten gleich derjenigen im multiplen Regressionsmodell? Dazu wird erst einmal das Modell mit nur der Prädiktorvariablen <span class="math inline">\(X_1\)</span> berechnet:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Modellfit</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.007</td>
<td style="text-align: right;">0.129</td>
</tr>
<tr class="even">
<td style="text-align: left;">x1</td>
<td style="text-align: right;">3.018</td>
<td style="text-align: right;">0.111</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Im Vergleich zum multiplen Regressionsmodell (siehe <a href="#tbl-mlm-basics-modelfit-01" class="quarto-xref">Tabelle&nbsp;<span>6.2</span></a>) hat sich der Modellkoeffizient verändert. Die Größe des Werts ist zwar in einem ähnlichen Bereich, die Werte sind aber nicht genau gleich. Das Gleiche nun für <span class="math inline">\(X_2\)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Modellfit</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.338</td>
<td style="text-align: right;">0.503</td>
</tr>
<tr class="even">
<td style="text-align: left;">x2</td>
<td style="text-align: right;">0.956</td>
<td style="text-align: right;">0.458</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Wieder ist der Wert des Modellskoeffizient anders als derjenige im multiplen Regressionsmodell (siehe <a href="#tbl-mlm-basics-modelfit-01" class="quarto-xref">Tabelle&nbsp;<span>6.2</span></a>). Wieder ist die Größenordnung des Wertes aber ähnlich. Aus Sicht der vorgehenden Ausführungen betrachtet, deutet die Veränderung der Werte darauf hin, dass die Information die die Prädiktorvariablen über <span class="math inline">\(Y\)</span> aussagen sich ändert wenn die jeweils andere Variable im Modell enthalten ist.</p>
</section>
</section>
<section id="multikollinearität" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="multikollinearität"><span class="header-section-number">6.2</span> Multikollinearität</h2>
<p>Sei nun ein anderer Datensatz betrachtet <span class="citation" data-cites="kutner2005">(Beispiel aus <a href="references.html#ref-kutner2005" role="doc-biblioref">Kutner u.&nbsp;a. 2005</a>)</span>. Im Rahmen einer Untersuchung sind Körperfettmessungen durchgeführt an <span class="math inline">\(20\)</span> Personen durchgeführt worden. Neben einer Gesamtkörpermessung wurde auch der Körperfettanteil am Oberarm, Unterarm und am Oberschenkel bestimmt. In <a href="#tbl-mlm-basics-bodyfat-01" class="quarto-xref">Tabelle&nbsp;<span>6.3</span></a> ist ein Ausschnitt der Daten abgebildet.</p>
<div class="cell">
<div id="tbl-mlm-basics-bodyfat-01" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-basics-bodyfat-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.3: Ausschnitt der Körperfettdaten [%]
</figcaption>
<div aria-describedby="tbl-mlm-basics-bodyfat-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Oberarm</th>
<th style="text-align: right;">Unterarm</th>
<th style="text-align: right;">Oberschenkel</th>
<th style="text-align: right;">Gesamt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">19.5</td>
<td style="text-align: right;">43.1</td>
<td style="text-align: right;">29.1</td>
<td style="text-align: right;">11.9</td>
</tr>
<tr class="even">
<td style="text-align: right;">24.7</td>
<td style="text-align: right;">49.8</td>
<td style="text-align: right;">28.2</td>
<td style="text-align: right;">22.8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">30.7</td>
<td style="text-align: right;">51.9</td>
<td style="text-align: right;">37.0</td>
<td style="text-align: right;">18.7</td>
</tr>
<tr class="even">
<td style="text-align: right;">29.8</td>
<td style="text-align: right;">54.3</td>
<td style="text-align: right;">31.1</td>
<td style="text-align: right;">20.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">19.1</td>
<td style="text-align: right;">42.2</td>
<td style="text-align: right;">30.9</td>
<td style="text-align: right;">12.9</td>
</tr>
<tr class="even">
<td style="text-align: right;">25.6</td>
<td style="text-align: right;">53.9</td>
<td style="text-align: right;">23.7</td>
<td style="text-align: right;">21.7</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Als Modell sollen der Gesamtkörperfettanteil mit Hilfe der drei verschiedenen Messungen bestimmt werden.</p>
<p><span class="math display">\[
Y_{\text{Körperfettanteil}} = \beta_0 + \beta_1 \cdot X_{\text{Oberarm}} + \beta_2 \cdot X_{\text{Unterarm}} + \beta_3 \cdot X_{\text{Oberschenkel}} + \epsilon
\]</span></p>
<p>Um die Daten besser zu verstehen wird zunächst betrachtet, wie stark die Werte miteinander korrelieren (siehe <a href="#fig-mlm-basics-bodyfat-01" class="quarto-xref">Abbildung&nbsp;<span>6.4</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-basics-bodyfat-01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-basics-bodyfat-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-bodyfat-01-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-basics-bodyfat-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.4: Korrelationsmatrize der Körperfettdaten
</figcaption>
</figure>
</div>
</div>
</div>
<p>Wie bei Körperfettwerten nicht anders zu erwarten, korrelieren die Prädiktorvariablen relativ stark miteinander. Die Korrelation zwischen den Oberschenkeldaten und den Oberarmdaten in dieser Stichprobe ist sogar <span class="math inline">\(&gt;0.9\)</span>. Die Frage ist nun, wie sich diese Korrelation auf den Modellfit auswirkt, wenn nur Teilmengen der Prädiktorvariablen zur Anpassung verwenden werden. Insgesamt können vier verschiedene Modelle verwendet werden. Ein Modell mit allen Prädiktorvariablen und drei weitere Modelle bei denen wir jeweils eine der Prädiktorvariablen weglassen.</p>
<p>In <a href="#tbl-mlm-basics-bodyfat-02" class="quarto-xref">Tabelle&nbsp;<span>6.4</span></a> sind nur die Steigungskoeffizienten für die vier verschiedenen Modell abgebildet.</p>
<div class="cell">
<div id="tbl-mlm-basics-bodyfat-02" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-basics-bodyfat-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.4: Koeffizienten der vier verschiedenen Modellen zu den Körperfettdaten.
</figcaption>
<div aria-describedby="tbl-mlm-basics-bodyfat-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Oberarm</th>
<th style="text-align: right;">Oberschenkel</th>
<th style="text-align: right;">Unterarm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alle</td>
<td style="text-align: right;">4.33</td>
<td style="text-align: right;">-2.86</td>
<td style="text-align: right;">-2.19</td>
</tr>
<tr class="even">
<td style="text-align: left;">ohne Unterarm</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">ohne Oberschenkel</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">-0.43</td>
</tr>
<tr class="even">
<td style="text-align: left;">ohne Oberarm</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">0.10</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Es ist zu beobachten, dass für diese Daten die Werte der Modellkoeffizienten sich sehr stark ändern in Abhängigkeit von welche Variablen in dem Modell enthalten sind. Beispielsweise änder der Koeffizient für den Oberschenkel nicht nur seine Größe sondern auch sein Vorzeichen, je nachdem ob der Ober- oder der Unterarm oder beide im Modell enthalten sind. D.h. durch die Korrelation der Prädiktorvariablen untereinander kommt es dazu, dass die Modellkoeffizienten sehr stark schwanken in Abhängigkeit von der Variablenkombination. Wird dies wieder aus der Sicht der Information betrachtet ist dieser Effekt eigentlich auch zu erwarten. Die Interpretation der Modellkoeffizienten bei der multiplen Regression war oben hergeleitet als, wie viel Information die <em>neue</em> Variablen liefert nachdem die anderen Variablen schon im Modell berücksichtigt wurden. Wenn die Variablen nun sehr stark miteinander korrelieren, dann bringt eine neue Variable wenige <em>neue Information</em> in das Modell über diejenige Information die schon durch die anderen Variablen repräsentiert wird. D.h. bei der multiplen Regression ist die Betrachtung der Beziehung der Prädiktorvariablen miteinander wichtig bei der Beurteilung des Modells. Dieses Konzept ist so wichtig, dass es einen eigenen Namen bekommt. Wenn mehrere Variablen in einem Modell miteinander korrelieren, dann wird dies als <strong>Multikollinearität</strong> bezeichnet.</p>
<div id="def-multicollinearity" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 6.1 (Multikollinearität)</strong></span> Wenn in einem Modell Prädiktorvariablen miteinander korrelieren, dann wird dies als Multikollinearität bezeichnet.</p>
</div>
<p>Multikollinearität hat verschiedene Einflüsse auf das Modell die sich vor allem hinsichtlich der Stabilität der Koeffizienten auswirken, wenn Prädiktorvariablen aus dem Modell herausgenommen werden bzw. dazugenommen werden. Dazu beeinflusst Multikollinearität auch die Größe der Standardfehler der geschätzten Koeffizienten <span class="math inline">\(\hat{\beta}_j\)</span>.</p>
<p>Multikollinearität hat unter anderem die folgenden Effekte:</p>
<ul>
<li>Große Änderungen in den Koeffizienten wenn Prädiktoren ausgelassen/eingefügt werden</li>
<li>Koeffizienten haben eine andere Richtung als erwartet</li>
<li>Hohe (einfache) Korrelationen zwischen Prädiktoren</li>
<li>Breite Konfidenzintervalle für “wichtige” Prädiktoren <span class="math inline">\(b_j\)</span></li>
</ul>
<p>Ein Maß mit dem Einfluss der Prädiktorvariablen untereinander abgeschätzt werden kann ist <strong>Variance Inflation Factor (VIF)</strong> (siehe <a href="#eq-mlm_basics_VIF" class="quarto-xref">Gleichung&nbsp;<span>6.1</span></a>).</p>
<p><span id="eq-mlm_basics_VIF"><span class="math display">\[
\text{VIF}_j = \frac{1}{1-R_j^2}
\tag{6.1}\]</span></span></p>
<p>Der VIF kann für jede kontinuierliche Prädiktorvariable einzeln berechnet werden. Der Term <span class="math inline">\(R_j^2\)</span> wird als multipler Korrelationskoeffizient bezeichnet und beruht auf dem Determinationskoeffizienten der Prädiktorvariablen <span class="math inline">\(X_i, i\neq j\)</span> auf die Prädiktorvariable <span class="math inline">\(X_j\)</span>. D.h. es wird ein Regressionsmodell gerechnet, bei dem die Prädiktorvariable <span class="math inline">\(X_j\)</span> als abhängige Variable verwendet wird und mittels der anderen <span class="math inline">\(p-1\)</span> Prädiktorvariablen modelliert wird.Wie der Name bereits andeutet, kommt es durch die Korrelation der Prädiktorvariablen untereinander es zu einer <em>Inflation der Varianzen</em>. D.h. die Standardfehler, die Wurzeln der jeweiligen Varianzen, der Modellparameter werden größer. Dies kann dann dazu führen, dass die Modellkoeffizienten keine statistische Signifikanz erreichen obwohl ein klarer Zusammenhang zwischen der Prädiktorvariablen und der abhängigen Variablen besteht. Der <span class="math inline">\(VIF_j\)</span> bietet eine einfache Möglichkeit, zumindest heuristisch, das gefittete Regressionsmodell auf Multikollinearitäten zu überprüfen. Bei der Interpretation der VIF gibt es allerdings keinen <em>magischen</em> Wert der eineindeutig Probleme identifiziert. Im Allgemeinen werden die VIFs niemals komplett null sein. Bei der Beurteilung von Problemen auf Grund von Multikollinearität wird üblicherweise der größte VIF Wert im Modell betrachtet.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wenn VIF &gt; 10 ist, dann deutet dies auf hohe Multikollinearität hin.</p>
</div>
</div>
<p>Manchmal wird in der Literatur auch die sogenannte Tolerance = <span class="math inline">\(\frac{1}{VIF}\)</span>, der Inverse Wert des VIF betrachtet.</p>
<p><span id="eq-mlm_basics_tolerance"><span class="math display">\[
\text{Tolerance}_j = \frac{1}{\text{VIF}_j} = 1 - R^2_j
\tag{6.2}\]</span></span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wenn der <span class="math inline">\(\text{Tolerance}_j\)</span> nahe bei <span class="math inline">\(1\)</span> ist, spricht dies für keine relevante Multikollinearität, während Werte <span class="math inline">\(&lt;0.1\)</span> auf Problem hindeuten.</p>
</div>
</div>
<p>Hinsichtlich des Einflusses bzw. des Umgangs bei Multikollinearität muss unterschieden werden, welches Ziel die Modellierung verfolgt. Das Problem das durch die Multikollinearität entsteht ist, basiert darauf das das Modell nicht eindeutig zuordnen kann, welche der miteinander korrelierten Variable für die beobachteten Veränderungen in der abhängigen Variablen <span class="math inline">\(Y\)</span> zuständig ist. Multikollinearität vermindert dabei <strong>nicht</strong> die Fähigkeit des Modells Mittelwerte <span class="math inline">\(E[y|x]\)</span> vorherzusagen oder einen guten Modellfit zu erhalten. Allerdings verkompliziert sich die Interpretation der Modellkoeffizienten <span class="math inline">\(\hat{\beta}_j\)</span>. Dadurch das die Prädiktorvariablen miteinander korrelieren, kann es beispielsweise gar nicht praktisch möglich sein die Variablen einzeln zu variieren, wodurch die Interpretation des Koeffizienten <span class="math inline">\(b_j\)</span> als die Veränderung von <span class="math inline">\(y\)</span> bei Veränderung von <span class="math inline">\(x_j\)</span> um eine Einheit problematisch wird. Da die Multikollinearität die Varianzen der Modellkoeffizienten vergrößert, kann es zu dem Fall kommen, dass ein Modellkoeffizienten <span class="math inline">\(b_j\)</span> statistisch nicht signifikant ist, obwohl eindeutig ein Zusammenhang zwischen <span class="math inline">\(x_j\)</span> und <span class="math inline">\(y\)</span> besteht. Zusätzlich, da die Modellkoeffizienten bei starken Multikollinearität eher instabil sind und sich stark bei Veränderung des Modells verändern können ist deren Interpretation grundsätzlich problematisch.</p>
<div id="exm-mlm-basics-jiourumaru" class="theorem example">
<p><span class="theorem-title"><strong>Beispiel 6.2 (Gehparameter bei Älteren)</strong></span> Die Beziehung zwischen gebrechlichen älteren Menschen und der Gehgeschwindigkeit ist entscheidend, um den Bedarf an Langzeitpflege oder erhöhter Unterstützung zu minimieren. Insbesondere ist der Zusammenhang zwischen Gehleistung, respiratorischer Funktion und dynamischem Gleichgewicht bei älteren Menschen, die auf Langzeitpflege angewiesen sind, noch nicht gut verstanden. Zu diesem Zweck wurde in <span class="citation" data-cites="jiroumaru2023">Jiroumaru u.&nbsp;a. (<a href="references.html#ref-jiroumaru2023" role="doc-biblioref">2023</a>)</span> der Zusammenhänge zwischen Gehgeschwindigkeit, Atemmuskelkraft und dynamischem Gleichgewicht mittels multipler Regressionsanalyse untersucht.</p>
<p>Die Atemmuskelkraft wurde mittels des maximalen inspiratorische (PImax) und des maximalen exspiratorische Drucks (PEmax) bestimmt. Der maximale Doppelschrittlängentest (MDST) wurde als Index für das dynamische Gleichgewicht verwendet. Eine multiple Regressionsanalyse wurde durchgeführt, wobei die Gehgeschwindigkeit (normale und maximale Gehgeschwindigkeit) als abhängige Variable und PImax, PEmax sowie MDST als unabhängige Variablen verwendet wurden. Zusätzlich wurde das Geschlecht als Anpassungsvariable berücksichtigt und in den Daten als entweder <span class="math inline">\(0\)</span> oder <span class="math inline">\(1\)</span> kodiert. Die Daten sind im repository zum Skriptum zu finden. Eine Analyse der Daten für die abhängige Variable maximale Gehgeschwindigkeit (<code>mws</code>) führte zu folgendem Ergebnis:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Modellfit</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.089</td>
<td style="text-align: right;">0.144</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pemax</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mdst</td>
<td style="text-align: right;">0.811</td>
<td style="text-align: right;">0.157</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pimax</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gender</td>
<td style="text-align: right;">-0.121</td>
<td style="text-align: right;">0.083</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>D.h. es wurde ein statistisch signifikanter Zusammenhang der maximalen Gehgeschwindigkeit mit PEmax und MDST beobachtet. Eine Untersuchung der VIF-Werte deutete auf keine starken Multikollineariäten zwischen den Variablen hin (siehe <a href="#tbl-mlm-basics_vif_ex" class="quarto-xref">Tabelle&nbsp;<span>6.5</span></a>).</p>
<div class="cell">
<div id="tbl-mlm-basics_vif_ex" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-basics_vif_ex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.5: VIF-Werte des Jioumaru et al.&nbsp;(2013) Modells.
</figcaption>
<div aria-describedby="tbl-mlm-basics_vif_ex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Prädiktor</th>
<th style="text-align: right;">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pemax</td>
<td style="text-align: right;">2.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">mdst</td>
<td style="text-align: right;">1.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pimax</td>
<td style="text-align: right;">1.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender</td>
<td style="text-align: right;">1.5</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</div>
<section id="take-away" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="take-away"><span class="header-section-number">6.2.1</span> Take-away</h3>
<ul>
<li>Bei der multiplen Regression wird das Modell um zusätzliche Prädiktorvariablen erweitert</li>
<li>Die Interpretation der Modellkoeffizienten ist bezieht sich auf den Einfluss der jeweiligen Variblen über denjenigen der anderen Variablen hinaus</li>
<li>Die Korrelation der Prädiktorvariablen, die Multikollinearität, untereinander kann zu unvorhergesehenen Effekten bei den Modellkoeffizienten führen</li>
</ul>
</section>
</section>
<section id="interaktionseffekte" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="interaktionseffekte"><span class="header-section-number">6.3</span> Interaktionseffekte</h2>
<p>Bisher sind die Variablen in das multiple Regressionsmodell nur <em>additiv</em> eingegangen. D.h. in der Modellspezifikation sind die Prädiktorvariablen <span class="math inline">\(x_i\)</span> immer nur mit einem <span class="math inline">\(+\)</span> in die Formel eingegangen. Im folgenden soll nun untersucht werden, was passiert wenn die Prädiktorvariablen auch multiplikativ in das Modell eingehen. Dies führt dann zu sogenannten <em>Interaktionseffekten</em>.</p>
<p>Ausgangspunkt sei wieder der Handballdatensatz. Ziel ist es noch immer, die Wurfgeschwindigkeit anhand der Körpermasse und der Armspanweite zu modellieren (siehe <a href="#tbl-mlm-inter-handball-01" class="quarto-xref">Tabelle&nbsp;<span>6.6</span></a>).</p>
<div id="tbl-mlm-inter-handball-01" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-inter-handball-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.6: Deskriptive Statistiken der Handballdaten
</figcaption>
<div aria-describedby="tbl-mlm-inter-handball-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">&nbsp;</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std.Dev</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><strong>Armspannweite[cm]</strong></td>
<td style="text-align: right;">184.29</td>
<td style="text-align: right;">7.72</td>
<td style="text-align: right;">169.43</td>
<td style="text-align: right;">200.74</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>Körpermasse[kg]</strong></td>
<td style="text-align: right;">77.46</td>
<td style="text-align: right;">10.26</td>
<td style="text-align: right;">57.95</td>
<td style="text-align: right;">101.12</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>Wurfgeschwindigkeit[m/s]</strong></td>
<td style="text-align: right;">21.85</td>
<td style="text-align: right;">2.31</td>
<td style="text-align: right;">18.50</td>
<td style="text-align: right;">29.22</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>In <a href="#tbl-mlm-inter-handball-01" class="quarto-xref">Tabelle&nbsp;<span>6.6</span></a> ist zunächst einmal nichts auffallendes zu sehen. Vielleicht sind die Wurfgeschwindigkeiten etwas zu niedrig für Hochleistungshandballer, aber das stört die weitere Analyse der Daten. Als nächstes erfolgt eine Betrachtung der Daten mittels von Streudiagrammen.</p>
<div id="fig-mlm-inter-handball-01" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-inter-handball-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-inter-handball-01" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-inter-handball-01-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-inter-handball-01-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-inter-handball-01-1.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-inter-handball-01" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-inter-handball-01-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Geschwindigkeit gegen Körpergewicht
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-inter-handball-01" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-inter-handball-01-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-inter-handball-01-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-inter-handball-01-2.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-inter-handball-01" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-inter-handball-01-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Geschwindigkeit gegen Armspannweite
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-inter-handball-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.5: Streudiagramme der Handballdaten.
</figcaption>
</figure>
</div>
<p>In beiden Graphen ist mit etwas gutem Willen ein positiver Zusammenhang zwischen den jeweiligen Prädiktorvariablen und der Wurfgeschwindigkeit zu identifizieren. Für das Körpergewicht in <a href="#fig-mlm-inter-handball-01-1" class="quarto-xref">Abbildung&nbsp;<span>6.5 (a)</span></a> vielleicht etwas mehr als für die Armspannweite in <a href="#fig-mlm-inter-handball-01-2" class="quarto-xref">Abbildung&nbsp;<span>6.5 (b)</span></a>.</p>
<p>Nun sollen die Daten mittels eines linearen Modells modelliert werden.</p>
<p><span class="math display">\[
Y_{i} = \beta_0 + \beta_1 \cdot \textrm{bm}_i + \beta_2 \cdot \textrm{as}_i + \epsilon_i
\]</span></p>
<p>Bei Betrachtung der Modellparameter (siehe <a href="#tbl-mlm-inter-handball-mod1" class="quarto-xref">Tabelle&nbsp;<span>6.7</span></a>) ist zu erkennen, dass die Steigungskoeffizienten zwar knapp statistisch signifikant sind, aber in Bezug auf die Residualvarianz bzw. den Standardfehler <span class="math inline">\(\hat{\sigma}\)</span> eine ziemlich hohe Restunsicherheit <span class="math inline">\(\hat{\sigma} = 1.9958\)</span> aufweisen. Dies macht die Vorhersage letztendlich unbrauchbar.</p>
<div class="cell">
<div id="tbl-mlm-inter-handball-mod1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-inter-handball-mod1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.7: Modellfit der Handballdaten aus Model 1
</figcaption>
<div aria-describedby="tbl-mlm-inter-handball-mod1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<caption>Modell 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
<th style="text-align: right;">t</th>
<th style="text-align: left;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-1.768</td>
<td style="text-align: right;">7.632</td>
<td style="text-align: right;">-0.232</td>
<td style="text-align: left;">0.818</td>
</tr>
<tr class="even">
<td style="text-align: left;">body_mass</td>
<td style="text-align: right;">0.077</td>
<td style="text-align: right;">0.033</td>
<td style="text-align: right;">2.359</td>
<td style="text-align: left;">0.024</td>
</tr>
<tr class="odd">
<td style="text-align: left;">arm_span</td>
<td style="text-align: right;">0.096</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">2.192</td>
<td style="text-align: left;">0.035</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\hat{\sigma}\)</span></td>
<td style="text-align: right;">1.996</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Der <span class="math inline">\(y\)</span>-Achsenabschnitt <span class="math inline">\(\beta_0\)</span> im Modell macht auch ebenfalls keinen Sinn, da er, verbal übersetzt ausdrückt, dass ein Handballer mit einer Spannweite von <span class="math inline">\(0\)</span>cm und einer Körpermasse von <span class="math inline">\(0\)</span> Kg eine Wurfgeschwindigkeit von <span class="math inline">\(v = -1.8\)</span>m/s erreichen würde. Um den <span class="math inline">\(y\)</span>-Achsenabschnitt interpretierbar zu machen zentrieren wir diese Variable, so dass der Mittelwert bei Null liegt. Dazu wird von jedem Wert der Mittelwert der Variable abgezogen. Dies ändert wieder nichts an dem Modellfit, aber der <span class="math inline">\(y\)</span>-Achsenabschnitt bekommt dadurch einen sinnvollen Wert.</p>
<p>Nun wird wieder da gleiche Modell angepasst, wobei die zentrierten Variablen als Prädiktorvariablen verwendet werden.</p>
<p>Wie erwartet ändert dies nichts an den Modellwerten, bis auf den <span class="math inline">\(y\)</span>-Achsenabschnitt. Der Wert von <span class="math inline">\(21.8\)</span> ist jetzt dahingehend zu interpretieren, dass ein Handballer mit einer Armspannweite von <span class="math inline">\(184\)</span>cm und einer Körpermasse von <span class="math inline">\(77\)</span>Kg eine Wurfgeschwindigkeit von <span class="math inline">\(21.9\)</span>m/s erreichen sollte (siehe <a href="#tbl-mlm-inter-handball-01" class="quarto-xref">Tabelle&nbsp;<span>6.6</span></a> und <a href="#tbl-mlm-inter-handball-mod2" class="quarto-xref">Tabelle&nbsp;<span>6.8</span></a>).</p>
<div class="cell">
<div id="tbl-mlm-inter-handball-mod2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-inter-handball-mod2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.8: Modellfit der Handballdaten aus Model 2
</figcaption>
<div aria-describedby="tbl-mlm-inter-handball-mod2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<caption>Modell 2</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
<th style="text-align: right;">t</th>
<th style="text-align: left;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">21.852</td>
<td style="text-align: right;">0.316</td>
<td style="text-align: right;">69.247</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">body_mass_c</td>
<td style="text-align: right;">0.077</td>
<td style="text-align: right;">0.033</td>
<td style="text-align: right;">2.359</td>
<td style="text-align: left;">0.024</td>
</tr>
<tr class="odd">
<td style="text-align: left;">arm_span_c</td>
<td style="text-align: right;">0.096</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">2.192</td>
<td style="text-align: left;">0.035</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\hat{\sigma}\)</span></td>
<td style="text-align: right;">1.996</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Nun erfolgt wie immer eine Betrachtung der Residuen <span class="math inline">\(e_i\)</span> im zentrierten, additiven Modell (Model 2) (siehe <a href="#fig-mlm-inter-handball-02" class="quarto-xref">Abbildung&nbsp;<span>6.6</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-inter-handball-02" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-inter-handball-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-inter-handball-02-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-inter-handball-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.6: Residuenplot unter Modell 2
</figcaption>
</figure>
</div>
</div>
</div>
<p>Da die Werte für kleine und große vorhergesagte Werte <span class="math inline">\(\hat{y}_i\)</span> ganz klar ein Muster aufweisen, kann davon ausgegangen werden, das das Modell eine in den Daten vorhandene <em>Struktur</em> nicht zu modellieren im Stande ist. Ein Möglichkeit besteht nun darin einen sogenannten <strong>Interaktionseffekt</strong> in das Modell zu integrieren.</p>
<div id="def-interaction" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 6.2 (Interaktionseffekt)</strong></span> Wenn der Effekt einer unabhängigen Variable auf die abhängige Variable davon abhängt welche Ausprägung eine weitere unabhängige Variable hat, dann wird dies als ein Interaktionseffekt bezeichnet.</p>
</div>
<p>In Abgrenzung zu Interaktionseffekte werden die <em>normalen</em> Effekte als Haupteffekte bezeichnet.</p>
<div id="def-maineffect" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 6.3 (Haupteffekte )</strong></span> Haupteffekte beschreiben den <strong>isolierten Einfluss</strong> einer unabhängigen Variable auf die abhängige Variable, unabhängig von anderen Variablen im Modell.</p>
</div>
<p>Im Rahmen eines linearen Modells, wird ein solcher Interaktionseffekt durch einen <em>multiplikativen</em> Term zwischen den beiden Variablen modelliert.</p>
<p><span id="eq-mlm-inter-model-ex"><span class="math display">\[
Y_{i} = \beta_0 + \beta_1 \times \textrm{bodymass}_i + \beta_2 \times \textrm{armspan}_i + \beta_3 \times \textrm{bodymass}_i \times \textrm{armspan}_i + \epsilon_i
\tag{6.3}\]</span></span></p>
<p>In der Formel <a href="#eq-mlm-inter-model-ex" class="quarto-xref">Gleichung&nbsp;<span>6.3</span></a> ist neben den beiden Modellkoeffizienten <span class="math inline">\(\beta_1\)</span> und <span class="math inline">\(\beta_2\)</span> jetzt ein weiterer Koeffizienten <span class="math inline">\(\beta_3\)</span> einhalten. Dieser Koeffizient bildet den Interaktionseffekt. Die <span class="math inline">\(X\)</span>-Werte die diesem Modellkoeffizienten zugeordnet sind, berechnen sich aus Produkt aus den beiden beteiligten Prädiktorvariablen. In dem vorliegenden Handballbeispiel aus dem Produkt aus Armspannweite und Körpergewicht <code>body_mass</code> <span class="math inline">\(\cdot\)</span> <code>arm_span</code>. Dies ist der Interaktionseffekt.</p>
<p>Im Handballbeispiel folgt daraus die folgende Modellanpassung (siehe <a href="#tbl-mlm-inter-handball-mod3" class="quarto-xref">Tabelle&nbsp;<span>6.9</span></a>)</p>
<div class="cell">
<div id="tbl-mlm-inter-handball-mod3" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-inter-handball-mod3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.9: Modellfit der Handballdaten unter Momdell 3
</figcaption>
<div aria-describedby="tbl-mlm-inter-handball-mod3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<caption>Modell 3</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
<th style="text-align: right;">t</th>
<th style="text-align: left;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">21.346</td>
<td style="text-align: right;">0.143</td>
<td style="text-align: right;">149.296</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">body_mass_c</td>
<td style="text-align: right;">0.119</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">8.133</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">arm_span_c</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">4.380</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">body_mass_c:arm_span_c</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">12.633</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\hat{\sigma}\)</span></td>
<td style="text-align: right;">0.868</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Bei Betrachtung der Residualvarianz <span class="math inline">\(\hat{\sigma}\)</span> ist zu beobachten, dass sich der halbiert hat. D.h das Interaktionsmodell scheint deutlich präziser den Zusammenhang zwischen den Prädiktorvariablen und der abhängigen Variablen abbilden zu können, als dies bei dem rein additiven Modell der Fall war. Zusätzlich haben sich die Standardfehler der beiden Steigungskoeffizienten für die <strong>Haupteffekte</strong> deutlich verringert (vgl. <a href="#tbl-mlm-inter-handball-mod2" class="quarto-xref">Tabelle&nbsp;<span>6.8</span></a>). Beide Koeffizienten sind nun statistisch signifikant geworden. Der neu dazugekommene Koeffizient für den Interaktionseffekt ist ebenfalls statistisch signifikant mit einem sehr kleinen Standardfehler. D.h die Hinzunahme des Interaktionseffekts hat in dem vorliegenden Beispiel dazu geführt, dass der Modellfit deutlich verbessert wurde.</p>
<p>Abschließend nun eine Betrachtung der resultierenden Flächen unter additiven und dem Interaktionsmodell. In <a href="#fig-mlm-inter-resid-plane" class="quarto-xref">Abbildung&nbsp;<span>6.7</span></a> sind die gefitteten Flächen und die Residuen unter den beiden Modellen abgebildet.</p>
<div id="fig-mlm-inter-resid-plane" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-inter-resid-plane-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-inter-resid-plane" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-inter-resid-plane-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-inter-resid-plane-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-inter-resid-plane-1.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-inter-resid-plane" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-inter-resid-plane-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) 3D Streudiagramm des Interaktionsmodells und gefittet Ebene unter Model 1
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-inter-resid-plane" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-inter-resid-plane-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-inter-resid-plane-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-inter-resid-plane-2.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-inter-resid-plane" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-inter-resid-plane-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) 3D Streudiagramm des Interaktionsmodells und gefittet Fläche unter Model 2
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-inter-resid-plane-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.7: Vergleich der gefitteten Ebenen in den beiden Modellen.
</figcaption>
</figure>
</div>
<p>Unter dem Interaktionsmodell ist die gefittete Fläche keine einfache Ebene mehr, sondern durch die Hinzunahme des Interaktionseffekts ähnelt die Fläche nun eher einem Sattel. D.h. durch die Integration von Interaktionseffekte zwischen den Prädiktorvariablen können deutlich komplizierte Zusammenhänge zwischen den Prädiktorvariablen und der abhängigen Variable modellieren werden. Die Komplexität erhöht sich entsprechend mit der Zahl der Prädiktorvariablen und den möglichen Interaktion zwischen diesen.</p>
<p>Zurückkommend auf unser Ausgangsbeispiel mit den Handballdaten, kann entsprechend die Auswirkung auf den die Modellanpassung analysiert werden. Dazu ein Vergleich der beiden Residuenplots (siehe <a href="#fig-mlm-inter-resid-comparison" class="quarto-xref">Abbildung&nbsp;<span>6.8</span></a>).</p>
<div id="fig-mlm-inter-resid-comparison" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-inter-resid-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-inter-resid-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-inter-resid-comparison-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-inter-resid-comparison-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-inter-resid-comparison-1.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-inter-resid-comparison" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-inter-resid-comparison-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Residuen im additiven Modell
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-inter-resid-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-inter-resid-comparison-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-inter-resid-comparison-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-inter-resid-comparison-2.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-inter-resid-comparison" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-inter-resid-comparison-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Residuen im Interaktionsmodell
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-inter-resid-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.8: Vergleich der Residuen zwischen Modell 2 und Modell 3.
</figcaption>
</figure>
</div>
<p>Es ist zu beobachten, dass in <a href="#fig-mlm-inter-resid-comparison-2" class="quarto-xref">Abbildung&nbsp;<span>6.8 (b)</span></a> die Struktur, die im additiven Modell in <a href="#fig-mlm-inter-resid-comparison-1" class="quarto-xref">Abbildung&nbsp;<span>6.8 (a)</span></a> für die Residuen , nun nicht mehr vorhanden ist. Ähnlich verhält sich auch der Vergleich für die die qq-Plots der Residuen (siehe <a href="#fig-mlm-inter-qq-comparison" class="quarto-xref">Abbildung&nbsp;<span>6.9</span></a>).</p>
<div id="fig-mlm-inter-qq-comparison" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-inter-qq-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-inter-qq-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-inter-qq-comparison-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-inter-qq-comparison-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-inter-qq-comparison-1.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-inter-qq-comparison" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-inter-qq-comparison-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) qq-Plot für das additive Modell
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-inter-qq-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-inter-qq-comparison-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-inter-qq-comparison-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-inter-qq-comparison-2.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-inter-qq-comparison" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-inter-qq-comparison-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) qq-Plot für das Interaktionsmodell
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-inter-qq-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.9: Vergleich der Residuen zwischen Modell 2 und Modell 3.
</figcaption>
</figure>
</div>
<p>Dazu nun ein Vergleich der weiteren Modellfitparameter.</p>
<div class="cell">
<div id="tbl-stats-int-model-performance" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stats-int-model-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.10: Vergleich der Modellperformance zwischen Model 2 und Model 3
</figcaption>
<div aria-describedby="tbl-stats-int-model-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Model</th>
<th style="text-align: right;">R2</th>
<th style="text-align: right;">R2_adjusted</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">Sigma</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mod_2</td>
<td style="text-align: left;">lm</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.252</td>
<td style="text-align: right;">1.919</td>
<td style="text-align: right;">1.996</td>
</tr>
<tr class="even">
<td style="text-align: left;">mod_3</td>
<td style="text-align: left;">lm</td>
<td style="text-align: right;">0.869</td>
<td style="text-align: right;">0.859</td>
<td style="text-align: right;">0.824</td>
<td style="text-align: right;">0.868</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Insgesamt sind durch die Hinzunahme des Interaktionseffekt nicht nur die Standardfehler und der Residualfehler verringert worden, sondern das Modell fittet die Daten auch deutlich besser als das additive Modell. Dies ist natürlich nicht immer der Fall, sondern hängt eng mit den jeweiligen Daten zusammen.</p>
<section id="take-away-1" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="take-away-1"><span class="header-section-number">6.3.1</span> Take-away</h3>
<p>Das Interaktionsmodell:</p>
<ul>
<li>Erhöht die Flexibilität des linearen Modells.</li>
<li>Bei Interaktionen hängt der Einfluss der einzelnen Variablen immer von den Werten der anderen Variablen ab.</li>
<li>Achtung: Interpretation der einfachen Haupteffekte oft nicht mehr möglich bzw. sinnvoll!</li>
</ul>
</section>
</section>
<section id="nominale-variablen-im-modell" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="nominale-variablen-im-modell"><span class="header-section-number">6.4</span> Nominale Variablen im Modell</h2>
<p>Sei das folgende Beispiel gegeben (siehe <a href="#fig-mlm-dummy-reaction-01" class="quarto-xref">Abbildung&nbsp;<span>6.10</span></a>)</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-reaction-01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-dummy-reaction-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-dummy-reaction-01-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-dummy-reaction-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.10: Ein Reaktionszeitexperiment mit vier Stufen A, B, C und D
</figcaption>
</figure>
</div>
</div>
</div>
<p>Es wurde ein Datensatz ähnlich einem Reaktionszeitexperiment erstellt, bei dem Probanden jeweils unter einer von vier verschiedenen Konditionen <span class="math inline">\(A,B,C\)</span> und <span class="math inline">\(D\)</span> beobachtet wurden. Die deskriptive Daten sind <a href="#tbl-mlm-dummy-reaction-01" class="quarto-xref">Tabelle&nbsp;<span>6.11</span></a> einsehbar. Der Einfachheit halber sind die Daten so generiert, dass die Gruppenmittelwert von <span class="math inline">\(A\)</span> nach <span class="math inline">\(D\)</span> immer größer werden.</p>
<div class="cell">
<div id="tbl-mlm-dummy-reaction-01" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-dummy-reaction-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.11: Gruppenmittelwerte, Standardabweichung und Unterschiede zu Stufe A
</figcaption>
<div aria-describedby="tbl-mlm-dummy-reaction-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Gruppe</th>
<th style="text-align: right;"><span class="math inline">\(\bar{y}_j\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_j\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\Delta_{j-A}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">509.53</td>
<td style="text-align: right;">45.66</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">599.68</td>
<td style="text-align: right;">43.57</td>
<td style="text-align: right;">90.15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">706.94</td>
<td style="text-align: right;">40.49</td>
<td style="text-align: right;">197.41</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: right;">805.09</td>
<td style="text-align: right;">52.51</td>
<td style="text-align: right;">295.56</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Die letzten Spalte zeigt die Abweichungen der Gruppenmittelwerte der Gruppen <span class="math inline">\(B,C,D\)</span> von der Gruppe <span class="math inline">\(A\)</span> an. Nun führen wir eine sogenannten <strong>Referenzgruppe</strong> bzw. <strong>Referenzstufe</strong> ein. Sei z.B. die Gruppe <span class="math inline">\(A\)</span> die Referenzgruppe. Problem ist es nun die <em>Gruppen</em> bzw. die Zugehörigkeit der einzelnen Datenpunkte auf die Prädiktorvariablen im multiplen linearen Regressionsmodell abzubilden. D.h. es ist notwendig eine Abbildung von <span class="math inline">\({A,B,C,D} \mapsto X_i\)</span> zu definieren. Dies lässt mit der Einführung von sogenannten <strong>Indikatorvariblen</strong> (auch Dummyvariablen) erreichen und führt zu der folgenden Kodierung der Daten (siehe <a href="#tbl-mlm-dummy-reaction-02" class="quarto-xref">Tabelle&nbsp;<span>6.12</span></a>).</p>
<div class="cell">
<div id="tbl-mlm-dummy-reaction-02" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-dummy-reaction-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.12: Kodierung der Dummyvariablen für das Reaktionszeitexperiment.
</figcaption>
<div aria-describedby="tbl-mlm-dummy-reaction-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">x1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">x2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">x3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Es werden drei <em>Indikatorvariablen</em> <span class="math inline">\(x_1, x_2\)</span> und <span class="math inline">\(x_3\)</span> eingeführt. Wenn ein Datenwert <span class="math inline">\(Y_i\)</span> aus Gruppe <span class="math inline">\(A\)</span>, der Referenzgruppe, kommt, dann werden die die Indikatorvariablen <span class="math inline">\(X_{1i}, X_{2i}, X_{3i}\)</span> mit den Werten <span class="math inline">\((0,0,0)\)</span> belegt. Wenn ein Wert <span class="math inline">\(Y_i\)</span> aus Gruppe <span class="math inline">\(B\)</span> kommt, dann mit <span class="math inline">\((1,0,0)\)</span> belegt, aus Gruppe <span class="math inline">\(C\)</span> dann <span class="math inline">\((0,1,0)\)</span> und aus Gruppe <span class="math inline">\(D\)</span> dann mit <span class="math inline">\((0,0,1)\)</span>.Es folgt ein Modell der Form:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \beta_3  x_{3i} + \epsilon_i
\]</span></p>
<p>Wird nun mittels dieser Kodierung ein lineares Modell in die Reaktionszeitdaten gefittet ergibt dies den folgenden Modellfit (siehe <a href="#tbl-mlm-dummy-reaction-03" class="quarto-xref">Tabelle&nbsp;<span>6.13</span></a>).</p>
<div class="cell">
<div id="tbl-mlm-dummy-reaction-03" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-dummy-reaction-03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.13: Koeffizientenmatrix für die Dummykodierung des Reaktionszeitexperiments.
</figcaption>
<div aria-describedby="tbl-mlm-dummy-reaction-03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<caption>Modellfit</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
<th style="text-align: right;">t</th>
<th style="text-align: left;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">509.526</td>
<td style="text-align: right;">10.235</td>
<td style="text-align: right;">49.784</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">groupB</td>
<td style="text-align: right;">90.150</td>
<td style="text-align: right;">14.474</td>
<td style="text-align: right;">6.228</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">groupC</td>
<td style="text-align: right;">197.414</td>
<td style="text-align: right;">14.474</td>
<td style="text-align: right;">13.639</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">groupD</td>
<td style="text-align: right;">295.561</td>
<td style="text-align: right;">14.474</td>
<td style="text-align: right;">20.420</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Die Steigungskoeffizienten <span class="math inline">\(\beta_i, i=1,\ldots,3\)</span> geben nun genau die die Abweichungen der Mittelwerte der jeweiligen Faktorstufen von der Referenzstufe <span class="math inline">\(A\)</span> (siehe <a href="#tbl-mlm-dummy-reaction-02" class="quarto-xref">Tabelle&nbsp;<span>6.12</span></a>). Der Steigungskoeffizient <span class="math inline">\(\beta_0\)</span> hat dagegen genau den Mittelwert der Werte aus Gruppe <span class="math inline">\(A\)</span>. D.h. mittels der Indikatorvariablen haben wir das folgende Modell erhalten:</p>
<p><span class="math display">\[
y_i = \mu_A + \Delta_{B-A} x_{1i} + \Delta_{C-A} x_{2i} + \Delta_{D-A} x_{3i} + \epsilon_i
\]</span></p>
<p>Um die Abweichungen von der Referenzgruppe zu modellieren sind drei Indikatorvarialben <span class="math inline">\(x_{1i}, x_{2i}\)</span> und <span class="math inline">\(x_{3i}\)</span> eingeführt worden. Die Modellkoeffizienten bilden somit jeweils die Abweichungen der Mittelwerte von der Referenzgrppe <span class="math inline">\(A\)</span> ab. Insgesamt ermöglicht somit die Verwendung von Indikatorvariablen nominale Variable mit beliebig vielen Faktorstufen in einem linearen Modell abzubilden.</p>
<div id="def-dummy" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 6.4 (Indikator-/Dummyvariablen )</strong></span> Eine Dummyvariable, auch Indikatorvariable genannt, ist eine binäre Prädiktorvariable die nur die Werte <span class="math inline">\(0\)</span> oder <span class="math inline">\(1\)</span> annimmt. Mit einer Dummyvariable kann die An- bzw. Abwesenheit eines kategorialen Effekts modelliert werden.</p>
</div>
<p>Der Ansatz mit Indikatorvariablen lässt sich dabei wie folgt Verallgemeinern (siehe <a href="#tbl-mlm-dummy-coding" class="quarto-xref">Tabelle&nbsp;<span>6.14</span></a>).</p>
<div id="tbl-mlm-dummy-coding" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-dummy-coding-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.14: Indikatorkodierung bei <span class="math inline">\(k\)</span>-Faktorstufen.
</figcaption>
<div aria-describedby="tbl-mlm-dummy-coding-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(x_1\)</span></th>
<th><span class="math inline">\(x_2\)</span></th>
<th><span class="math inline">\(\ldots\)</span></th>
<th><span class="math inline">\(x_{K-1}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Referenz (<span class="math inline">\(j=1\)</span>)</td>
<td>0</td>
<td>0</td>
<td></td>
<td>0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(j=2\)</span></td>
<td>1</td>
<td>0</td>
<td><span class="math inline">\(\ldots\)</span></td>
<td>0</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(j=3\)</span></td>
<td>0</td>
<td>1</td>
<td><span class="math inline">\(\ldots\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(j=K\)</span></td>
<td>0</td>
<td>0</td>
<td><span class="math inline">\(\ldots\)</span></td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Bei Integration einer nominalen Variable mit <span class="math inline">\(K\)</span> Faktorstufen werden <span class="math inline">\(K-1\)</span> Indikatorvariablen <span class="math inline">\(X_1, X_2, \ldots, X_{K-1}\)</span> benötigt. Eine der Faktorstufen wird als Referenzstufe definiert. Die Indikatorvariablen <span class="math inline">\(X_1\)</span> bis <span class="math inline">\(X_{K-1}\)</span> kodieren dann die Abweichungen der anderen Stufen von der Referenzstufe. Diese Art der Kodierung wird in der Literatur auch als <em>treatment</em> Kodierung bezeichnet. Die Indikatorvariablen werden oft auch als Dummyvariablen bezeichnet</p>
<p>Mit der Integration von nominalen Variablen in das Modell ist dann auch die Unterscheidung in ANOVA und linear Regression als überfällig anzusehen, da beide letztendlich auf dem gleichem Modell, nämlich dem linearen Modell, beruhen.</p>
<p>Es folgt wieder eine kurze Betrachtung des Residuenplots (siehe <a href="#fig-mlm-dummy-reaction-02" class="quarto-xref">Abbildung&nbsp;<span>6.11</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-reaction-02" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-dummy-reaction-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-dummy-reaction-02-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-dummy-reaction-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.11: Residuenplot für das Modell der Reaktionszeitdaten.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Es ist wieder zu sehen, dass nur vier verschiedene <span class="math inline">\(\hat{y}_i\)</span> Werte vorhergesagt werden, nämlich die Mittelwerte <span class="math inline">\(\bar{y}_k\)</span> in den jeweiligen <span class="math inline">\(K\)</span> Gruppen. Die Residuen <span class="math inline">\(e_i\)</span> streuen daher nur um diese vorhergesagten Werte.</p>
</section>
<section id="kombination-von-kontinuierlichen-und-nominalen-prädiktorvariablen" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="kombination-von-kontinuierlichen-und-nominalen-prädiktorvariablen"><span class="header-section-number">6.5</span> Kombination von kontinuierlichen und nominalen Prädiktorvariablen</h2>
<p>Da durch die Verwendung von Indikatorvariablen die Unterscheidung zwischen nominalen und kontinuierlichen Variablen in der Modellierung aufgehoben wird, können beide Typen von Variablen in einem Modell integriert werden. In <a href="#fig-mlm-dummy-combi-01" class="quarto-xref">Abbildung&nbsp;<span>6.12</span></a> ist ein hypothetischen Zusammenhang zwischen der körperlichen Leistung dem Trainingsalter und dem Gender abgetragen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-combi-01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-dummy-combi-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-dummy-combi-01-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-dummy-combi-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.12: Hypothetische Leistungsentwicklung in Abhängigkeit vom Alter und Gender
</figcaption>
</figure>
</div>
</div>
</div>
<p>Das Trainingsalter (<code>ta</code>) geht wie bisher als kontinuierliche Variable in das Modell ein, während <code>gender</code> als nominale Variable über eine Dummyvariable modelliert wird. Weibliche Teilnehmerinnen der Studie werden als Referenzstufe festgelegt. Das resultiert dann in dem folgenden linearen Modell:</p>
<p><span class="math display">\[
\begin{aligned}
Y_i &amp;= \beta_{ta = 0,x_{1i}=0} + \Delta_m \cdot x_{1i} + \beta_{ta} \cdot ta + \epsilon_i \\
x_1 &amp;=
\begin{cases}
0\text{ wenn weiblich}\\
1\text{ wenn männlich}
\end{cases} \\
\end{aligned}
\]</span></p>
<p>Modellierung führt dann zu:</p>
<div class="cell">
<div id="tbl-mlm-dummy-combi-01" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-dummy-combi-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.15: Modellfit für das Modell mit Trainingsalter und Gender.
</figcaption>
<div aria-describedby="tbl-mlm-dummy-combi-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">41.181</td>
<td style="text-align: right;">1.083</td>
<td style="text-align: right;">38.024</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender_fm</td>
<td style="text-align: right;">-10.877</td>
<td style="text-align: right;">0.805</td>
<td style="text-align: right;">-13.503</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ta</td>
<td style="text-align: right;">1.927</td>
<td style="text-align: right;">0.145</td>
<td style="text-align: right;">13.261</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Die Variable <code>gender</code> ist als Dummyvariable definiert worden und der Steigungskoeffizient <span class="math inline">\(\beta_1=\)</span> <code>gender_fm</code> kodiert den mittleren Unterschied zwischen männlichen und weiblichen Studienteilnehmerinnen. Der <span class="math inline">\(Y\)</span>-Achsenabschnitt kodiert daher die Leistung von weiblichen Teilnehmerinnen mit einem Trainingsalter von <code>ta</code><span class="math inline">\(= 0\)</span>. (Warum?). Der Graph der Datenpunkte zusammen mit den resultierenden Modellgraphen der vorhergesagten <span class="math inline">\(\hat{y}_i\)</span> zeigt an wie das Modell die Daten modelliert (siehe <a href="#fig-mlm-dummy-combi-02" class="quarto-xref">Abbildung&nbsp;<span>6.13</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-combi-02" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-dummy-combi-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-dummy-combi-02-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-dummy-combi-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.13: Leistungsentwicklung in Abhängigkeit vom Alter und Gender
</figcaption>
</figure>
</div>
</div>
</div>
<p>Es wurden zwei Geraden modelliert. Eine Gerade für die weiblichen und eine für die männlichen Teilnehmer. Die Geraden sind parallel zueinander und um den Wert von <span class="math inline">\(\beta_1\)</span> gegeneinander verschoben.</p>
<p>Natürlich ist es auch nun möglich mit dem Indikatorvariablenansatz auch eine Interaktion zwischen kontinuierlichen und nominalen Variablen zu modellieren. Wenn die Daten zum Beispiel dem Trend in <a href="#fig-mlm-dummy-combi-03" class="quarto-xref">Abbildung&nbsp;<span>6.14</span></a> folgen würden.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-combi-03" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-dummy-combi-03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-dummy-combi-03-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-dummy-combi-03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.14: Leistungsentwicklung in Abhängigkeit vom Alter und Gender
</figcaption>
</figure>
</div>
</div>
</div>
<p>Hier ist zu sehen, dass die Zunahme der Leistung mit dem Trainingsalter nicht gleich ist in beiden <code>gender</code> Gruppen. Bei den männlichen Teilnehmern ist der Zuwachs mit dem Trainingsalter größer. D.h der Einfluss der Prädiktorvariable Trainingsalter hängt mit der Ausprägung der Prädiktorvariablen <code>gender</code> zusammen. Es liegt ein Interaktionseffekt vor. Übertragen auf ein lineares Modell könnte der Modellansatz wie folgt aussehen:</p>
<p><span class="math display">\[
y_i = \beta_{ta=0,x_{1i}=0} + \Delta_m \times x_{1i} + \beta_{ta} \times ta + \beta_{ta \times gender} \times x_{1i} \times ta + \epsilon_i
\]</span></p>
<p>Das zu folgenden Modellfit führt.</p>
<div class="cell">
<div id="tbl-mlm-dummy-combi-02" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-dummy-combi-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.16: Modellfit für das Interaktionsmodell mit Trainingsalter und Gender.
</figcaption>
<div aria-describedby="tbl-mlm-dummy-combi-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">31.354</td>
<td style="text-align: right;">1.370</td>
<td style="text-align: right;">22.891</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender_ff</td>
<td style="text-align: right;">8.575</td>
<td style="text-align: right;">2.010</td>
<td style="text-align: right;">4.266</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ta</td>
<td style="text-align: right;">1.763</td>
<td style="text-align: right;">0.195</td>
<td style="text-align: right;">9.043</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender_ff:ta</td>
<td style="text-align: right;">2.362</td>
<td style="text-align: right;">0.290</td>
<td style="text-align: right;">8.139</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Die gefitteten Regressionsgeraden nehmen dann die folgende Form an (siehe <a href="#fig-mlm-dummy-combi-04" class="quarto-xref">Abbildung&nbsp;<span>6.15</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-combi-04" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-dummy-combi-04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-dummy-combi-04-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-dummy-combi-04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.15: Leistungsentwicklung in Abhängigkeit vom Alter und Gender
</figcaption>
</figure>
</div>
</div>
</div>
<p>Wie sind die Modellkoeffizienten zu interpretieren? Dazu schauen wir uns der Einfachheit halber die Werte im zentrierten Modell an.</p>
<div class="cell">
<div id="tbl-mlm-dummy-combi-03" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-dummy-combi-03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;6.17: Modellfit für das Interaktionsmodell mit Trainingsalter und Gender im zentrierten (Alter) Modell.
</figcaption>
<div aria-describedby="tbl-mlm-dummy-combi-03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">41.934</td>
<td style="text-align: right;">0.561</td>
<td style="text-align: right;">74.787</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender_ff</td>
<td style="text-align: right;">22.750</td>
<td style="text-align: right;">0.807</td>
<td style="text-align: right;">28.184</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ta_c</td>
<td style="text-align: right;">1.763</td>
<td style="text-align: right;">0.195</td>
<td style="text-align: right;">9.043</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender_ff:ta_c</td>
<td style="text-align: right;">2.362</td>
<td style="text-align: right;">0.290</td>
<td style="text-align: right;">8.139</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Die Referenzgruppe sind die Datenpunkte der männlichen Gruppe. Daher ist der <span class="math inline">\(Y\)</span>-Achsenabschnitt <span class="math inline">\(\beta_0 = 41.93\)</span> die Performance einer durchschnittlichen, männlichen Versuchsperson mit einem Trainingsalter von <code>ta</code><span class="math inline">\(= 6\)</span>. Der zweite Koeffizient <span class="math inline">\(\beta_1 = 22.75\)</span> kodiert hier den Unterschied zwischen einer männlichen und einer weiblichen Versuchsperson jeweils mit einem Trainingsalter von <code>ta</code><span class="math inline">\(=6\)</span>. Der Steigungskoeffizient <span class="math inline">\(\beta_2 = 1.76\)</span> dagegen, kodiert den Unterschied zwischen zwei männlichen Versuchspersonen, die sich um ein Trainingsjahr <code>ta</code> voneinander unterscheiden. Der letzte Koeffizient <span class="math inline">\(\beta_3 = 2.36\)</span>, der Interaktionskoeffizient kodiert nun den Unterschied in den Steigungen zwischen den männlichen und den weiblichen Versuchspersonen. Um den Unterschied zwischen zwei weiblichen Versuchsperson zu erhalten, die sich um ein Trainingsjahr <code>ta</code> voneinander Unterscheiden, müssen daher <span class="math inline">\(\beta_2\)</span> und <span class="math inline">\(\beta_3\)</span> miteinander addiert werden <span class="math inline">\(4.12\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-combi-05" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-dummy-combi-05-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-dummy-combi-05-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-dummy-combi-05-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.16: Leistungsentwicklung in Abhängigkeit vom Alter und Gender und die Modellkoeffizienten im zentrierten Modell.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-mlm-dummy-combi-05" class="quarto-xref">Abbildung&nbsp;<span>6.16</span></a> sind die einzelnen Modellkoeffizienten aus <a href="#tbl-mlm-dummy-combi-02" class="quarto-xref">Tabelle&nbsp;<span>6.16</span></a> in der Grafik miteingefügt. Die Interpretation der Werte sollte damit klarer werden.</p>
<section id="take-away-2" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="take-away-2"><span class="header-section-number">6.5.1</span> Take-away</h3>
<p>In diesem Abschnitt wurde gezeigt, dass auch nominale Prädiktorvariablen ohne Probleme in das lineare Modell integrieren können. Dabei können die Variablen rein additiv oder auch als interaktive Effekte eingehen. Damit ist der Prozess um Daten zu modellieren deutlich flexibler geworden. Dabei bleibt aber immer die bekannten Rückführung auf Punkt-Steigungs-Modell erhalten.</p>
<p>In den bisherigen Abschnitten sind die behandelten Modelle Stück für Stück immer komplizierter geworden. Angefangen mit dem einfachen linearen Modell, wurde die Erweiterung zum additiven multiplen linearen Modell mit mehreren <span class="math inline">\(X\)</span>-Variablen vollzogen. Im nächsten Schritt konnten die <span class="math inline">\(X\)</span>-Variablen miteinander interagieren, während im letzten Schritt die Anforderung aufgehoben wurde, dass die <span class="math inline">\(X\)</span>-Variablen kontinuierlich sein mussten. Im Kern wurde aber immer das einfache Modell der Punkt-Steigungsform beibehalten. Im Zuge der Behandlung von Indikatorvariablen wurde eine direkte Verbindung zwischen dem linearen Modell und einer ANOVA gezeigt.</p>
</section>
</section>
<section id="genereller-linearer-modell-testansatz" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="genereller-linearer-modell-testansatz"><span class="header-section-number">6.6</span> Genereller Linearer Modell Testansatz</h2>
<p>Ausgangspunkt ist wieder das Modell der einfachen linearen Regression, mit nur einer Prädiktorvariablen <span class="math inline">\(X\)</span>-Variable und der abhängigen Variablen <span class="math inline">\(Y\)</span>. Sei der folgende Modellfit gegeben.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Modellfit</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.841</td>
<td style="text-align: right;">0.701</td>
</tr>
<tr class="even">
<td style="text-align: left;">x</td>
<td style="text-align: right;">0.457</td>
<td style="text-align: right;">0.375</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Zunächst werden wieder die Residuen betrachtet, die Abweichungen der beobachteten Daten <span class="math inline">\(y_i\)</span> von der vorhergesagten Werten der Regressionsgeraden <span class="math inline">\(\hat{y}_i\)</span>. Im Rahmen der Behandlung des Determinationskoeffizienten <span class="math inline">\(R^2\)</span> sind bereits Quadratsummen und deren Unterteilung besprochen worden. Dort wurde die Aufteilung der Varianz von <span class="math inline">\(Y\)</span>, bezeichnet als <span class="math inline">\(SSTO\)</span>, die totale Varianz in die beiden Komponenten Regressionsvarianz <span class="math inline">\(SSR\)</span> und Fehlervarianz <span class="math inline">\(SSE\)</span> eingeführt.</p>
<p><span class="math display">\[
SSTO = SSR + SSE
\]</span></p>
<p>Die Fehlerquadratsumme SSE, die Summe der quadrierten Abweichungen zwischen dem beobachteten Wert <span class="math inline">\(y_i\)</span> und dem vorhergesagten Wert <span class="math inline">\(\hat{y}_i\)</span> ist definiert mittels:</p>
<p><span class="math display">\[
SSE = \sum_{i=1}^n (y_i - \hat{y}_i)^2
\]</span></p>
<p>Also letztendlich wieder nur die Summe der quadrierten Residuen. Um für gegebene Daten die vorhergesagten Werte <span class="math inline">\(\hat{y}_i\)</span> berechnen zu können, wird ein Modell und die dazugehörigen Modellkoeffizienten <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> benötigt. Das einfache lineare Modell hat in diesem Fall zwei Modellparameter. Zuvor wurde bereits die Anzahl der Modellparameter formalisiert und als eigener Parameter bezeichnet. Per Konvention wird die Parameteranzahl mit <span class="math inline">\(p\)</span> bezeichnet. Im einfachen Fall mit den beiden Parametern <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> gilt daher <span class="math inline">\(p = 2\)</span>. Die Anzahl der Parameter <span class="math inline">\(p\)</span> spielt eine Rolle wenn die sogenannten <strong>Freiheitsgrade</strong> <span class="math inline">\(df\)</span> (degrees of freedom) bestimmt werden müssen. Umgangssprachlich bezeichnen die Freiheitsgerade die Anzahl der Daten die frei variiert werden können. Die Freiheitsgrade für die Fehlerquadratsumme <span class="math inline">\(SSE\)</span> berechnet sich mittels der Formel <span class="math inline">\(N-p\)</span>. <span class="math inline">\(N\)</span> bezeichnet die Anzahl der Beobachtungen, in unserem Fall die Anzahl der Datenpunkte.</p>
<p><span class="math display">\[
df_E := N - p
\]</span></p>
<p>Die Freiheitsgerade <span class="math inline">\(df\)</span> bestimmen die <em>effektive</em> Anzahl der Beobachtungen die zur Verfügung stehen um die Varianz <span class="math inline">\(\sigma^2\)</span> des Modells abzuschätzen. Dadurch, dass zwei Parameter anhand der Daten für das Modell bestimmt werden, fallen zwei Datenpunkt als <em>unabhängige</em> Informationsquellen weg. Anders ausgedrückt, wenn die beiden Modellparameter <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> bekannt sind, dann sind nur noch <span class="math inline">\(N-2\)</span> Datenpunkt frei variierbar. Sobald die Werte von <span class="math inline">\(N-2\)</span> Datenpunkten und die beiden Parameter bekannt, können die verbleibenden beiden Werte berechnet werden. Daher der Begriff der Freiheitsgrade.</p>
<p>Das Ziel ist nun eine Metrik zu entwickeln die es erlaubt abschätzen, ob die Hinzunahme von zusätzlichen Modellparametern zu einer Verbesserung der Modellvorhersage führt. D.h. der Analyseprozess startet mit einem <em>einfachen</em> Modell und sukzessive werden weitere Variablen zum Modell hinzugefügt und es wird überprüft ob dadurch die Modellvorhersage verbessert wird. Eine <em>Verbesserung</em> wird in diesem Fall über die Veränderung in <span class="math inline">\(SSE\)</span> ermittelt. Wenn zusätzliche Modellparameter zu einer Verbesserung führen, dann sollte eine <em>relevante</em> Reduktion der Fehlervarianz <span class="math inline">\(SSE\)</span> beobachtet werden. Die Residuen werden kleiner und die Präzision der Vorhersagen wird verbessert. Als Randbedingung sollen die zu vergleichenden Modelle in einer Hierarchie zueinander stehen. Dies bedeutet, dass einfachere Modelle als Teilmodelle von komplexeren Modellen interpretiert werden.</p>
<p>Dazu wird zunächst eine Unterscheidung zwischen einem vollem Modell (<span class="math inline">\(F\)</span>ull model) und einem reduzierten Modell (<span class="math inline">\(R\)</span>educed model) getroffen. Als das volle Modell wird immer das kompliziertere Modell, also dasjenige mit größerem <span class="math inline">\(p\)</span>, bezeichnet. Dementsprechend ist das reduzierte Modell das weniger komplizierte Modell, welches einem Spezialfall des vollen Modell entspricht. Dabei ist die Bezeichnung voll bzw. reduziertes Modell immer nur temporär. Ein volles Modell kann bei einem weiteren Vergleich zum reduzierten Modell werden. Für das Beispiel der einfachen lineare Regression ist das full model das bekannte Modell:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 X_i + \epsilon_i, \quad \epsilon_i \sim \mathcal{N}(0,\sigma^2)
\]</span></p>
<p>Nun kann die Frage gestellt werden, ob der Modellparameter <span class="math inline">\(\beta_1\)</span> wirklich benötigt wird? Vielleicht zeigt die <span class="math inline">\(X\)</span>-Variable gar keinen Zusammenhang mit der <span class="math inline">\(Y\)</span>-Variable und durch die Inklusion von <span class="math inline">\(X\)</span> wird letztendlich nur Datenrauschen im Modell angepasst. Aus dieser Überlegung heraus, ist es möglich ein reduziertes Modell zu formulieren bei dem der Parameter <span class="math inline">\(\beta_1\)</span> fehlt.</p>
<p><span class="math display">\[
Y_i = \beta_0 + \epsilon_i, \quad \epsilon_i \sim \mathcal{N}(0,\sigma^2)
\]</span></p>
<p>Die Residualvarianz <span class="math inline">\(SSE(R)\)</span> für dieses reduzierte Modell berechnet sich nun mittels.</p>
<p><span class="math display">\[
\textrm{SSE(R)} = \sum_{i=1}^N (y_i - \beta_0)^2
\]</span></p>
<p>Im reduzierten Modell ist nur noch ein Parameter <span class="math inline">\(\beta_0\)</span> vorhanden, somit gilt <span class="math inline">\(p = 1\)</span> und entsprechend <span class="math inline">\(df_{R} = N - 1\)</span>.</p>
<p>Mit etwas Algebra lässt sich zeigen, dass im Allgemeinen <span class="math inline">\(SSE(F) \leq SSE(R)\)</span> gilt. Dieser Zusammenhang lässt sich auch heuristisch herleiten. Wenn es keinen Zusammenhang zwischen <span class="math inline">\(X\)</span> und <span class="math inline">\(Y\)</span> gibt, dann wird der <span class="math inline">\(\beta_1\)</span> im full model nahezu <span class="math inline">\(0\)</span> sein und Formel <span class="math inline">\(\eqref{eq-mlm-hier-ssef}\)</span> wird zu <span class="math inline">\(SSE(R)\)</span>. Im realistischen Fall wird aber, selbst wenn kein Zusammenhang zwischen <span class="math inline">\(X\)</span> und <span class="math inline">\(Y\)</span> besteht, ein Teil des immer vorhandenen Rauschens in den Daten mittels <span class="math inline">\(\beta_1\)</span> gefittet. Das führt dazu, das praktisch immer <span class="math inline">\(SSE(F)\)</span> etwas kleiner ist als <span class="math inline">\(SSE(R)\)</span>. Somit folgt der beschriebene Zusammenhang zwischen <span class="math inline">\(SSE(F)\)</span> und <span class="math inline">\(SSE(R)\)</span>.</p>
<p>Sei nun das reduzierte Modell korrekt. D.h. die Hinzunahme von <span class="math inline">\(X\)</span> sollte keine Verbesserung des Modells, keine Verbesserung in der Modellvorhersage, nach sich ziehen. Konkret bedeutet dies, dass <span class="math inline">\(SSE(R)\)</span> und <span class="math inline">\(SSE(F)\)</span> in etwas gleich groß sein sollten, bzw. <span class="math inline">\(SSE(F)\)</span> nur wenig besser (also kleiner) als <span class="math inline">\(SSE(R)\)</span> ist. Wenn die Differenz der beiden Quadratsummen gebildet wird, dann sollte diese Differenz entsprechend eher klein sein.</p>
<p><span id="eq-mlm-hier-div"><span class="math display">\[
\textrm{SSE(R)} - \textrm{SSE(F)}
\tag{6.4}\]</span></span></p>
<p>Beide Modelle sind in etwas gleich gut, fitten die Daten also in etwa gleich gut. Das volle Modell etwas besser, das es durch den zusätzlichen Parameter etwas flexibler als das reduzierte Modell ist. Sei nun von von der entgegen gesetzten Annahme ausgegangen. Das reduzierte Modell ist falsch und die Variable <span class="math inline">\(X\)</span> wird benötigt um die Varianz in <span class="math inline">\(Y\)</span> aufzuklären. In diesem Fall sollte die Differenz <a href="#eq-mlm-hier-div" class="quarto-xref">Gleichung&nbsp;<span>6.4</span></a> einen deutlich größeren Wert annehmen. Das reduzierte Modell kann denjenigen Teil der Varianz von <span class="math inline">\(Y\)</span> nicht aufklären der durch <span class="math inline">\(X\)</span> entsteht. Dadurch wandert die durch <span class="math inline">\(X\)</span> verursachte Varianz in die Residuen, was dazu führt das <span class="math inline">\(SSE(R)\)</span> größer wird. Im vollem Modell dagegen, kann die durch <span class="math inline">\(X\)</span> entstehende Varianz durch den zusätzlichen Modellparameter <span class="math inline">\(\beta_1\)</span> erklärt werden und entsprechend sind die Residuen geringer. Wenn die Residuen geringer werden führt das wiederum dazu, dass der Wert von <span class="math inline">\(SSE(F)\)</span> kleiner wird. Zusammengefasst, aus der Differenz in den <span class="math inline">\(SSE\)</span> zwischen den beiden Modellen, kann heuristisch eine Metrik hergeleitet werden. Diese Metrik erlaubt verschiedene Modelle miteinander zu vergleichen. Wenn das reduzierte, <em>einfachere</em>, Modell ausreicht um die Daten zu erklären, dann wird die Differenz <a href="#eq-mlm-hier-div" class="quarto-xref">Gleichung&nbsp;<span>6.4</span></a> eher klein ausfallen. Wenn dagegen die zusätzlichen Parameter im vollem Modell benötigt werden und die Varianz in <span class="math inline">\(Y\)</span> zu erklären, dann wird der Unterschied <a href="#eq-mlm-hier-div" class="quarto-xref">Gleichung&nbsp;<span>6.4</span></a> eher groß werden. Dieser Überlegung folgend, lässt sich ein statistischer Test formulieren:</p>
<p><span id="eq-mlm-hier-Ftest"><span class="math display">\[
F =\frac{\frac{\textrm{SSE(R)} - \textrm{SSE(F)}}{df_{E(R)} - df_{E(F)}}}{ \frac{\textrm{SSE(F)}}{df_{E(F)}}} = \frac{MS_{\textrm{test}}}{MS_{E(F)}}  \sim F(df_{E(R)}-df_{E(F)},df_{E(F)})
\tag{6.5}\]</span></span></p>
<p>Unter der Annahme, das das reduzierte Modell korrekt ist, folgt dieser <span class="math inline">\(F\)</span>-Werte einer theoretische Verteilung <span class="math inline">\(F\)</span>-Verteilung. Dies ist die <span class="math inline">\(F\)</span>-Verteilung mit <span class="math inline">\(df_{E(R)} - df_{E(F)}\)</span> und <span class="math inline">\(df_{E(F)}\)</span> Freiheitsgeraden. Die Annahme das das reduzierte Modell korrekt ist, stellt somit wieder die <span class="math inline">\(H_0\)</span> dar. Ein <span class="math inline">\(F\)</span>-Wert in der Nähe von <span class="math inline">\(1\)</span> deutet daraufhin, das das reduzierte Modell adäquat ist um die Daten zu beschreiben und die Hinzunahme des Parameters im vollen Modell keine Verbesserung liefert. Sobald nun aber wieder eine bekannte, theoretische Verteilung unter einer <span class="math inline">\(H_0\)</span> vorhanden ist, kann wieder das bereits bekannte Instrumentarium zur Hypothesentestung angewendet werden. Fällt der beobachtete Wert <span class="math inline">\(F\)</span>-Wert für ein gegebenes <span class="math inline">\(\alpha\)</span> in einen kritischen Bereich (siehe <a href="#fig-mlm-hier-fcrit" class="quarto-xref">Abbildung&nbsp;<span>6.17</span></a> für ein Beispiel), dann kann dies als Evidenz gegen die <span class="math inline">\(H_0\)</span> interpretiert werden. <em>Wir sind überrascht diesen Wert unter der <span class="math inline">\(H_0\)</span> zu beobachten und lehnen die <span class="math inline">\(H_0\)</span>, das das einfachere Modell korrekt ist ab.</em> Der beobachtete <span class="math inline">\(F\)</span>-Wert wird als Evidenz dafür gewertet, das das komplexere, volle Modell die Daten besser abbildet und <em>statistisch signifikant</em> mehr Varianz der abhängigen Variable modellieren kann.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-hier-fcrit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-hier-fcrit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-hier-fcrit-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-hier-fcrit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.17: F-Verteilung mit <span class="math inline">\(df_1 = 5, df_2 = 10\)</span> und kritischem Wert bei <span class="math inline">\(\alpha=0.05\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
<p>Insgesamt erlaubt der Vergleich von Modellen miteinander, Verbesserung/Verschlechterung der Modellvorhersage statistisch zu überprüfen. Über die Statistik <a href="#eq-mlm-hier-Ftest" class="quarto-xref">Gleichung&nbsp;<span>6.5</span></a> wurde eine Teststatistik hergeleitet, die einer bekannten theoretischen Verteilung folgt. Wenn dieser <span class="math inline">\(F\)</span>-Test statistisch signifikant wird, dann wird dies als Evidenz dafür gewertet, das das volle Modell die Daten so viel besser modelliert und das dieses Modell dem reduzierten Modell vorgezogen werden sollte.</p>
<p>Einschränkend muss allerdings beachtet werden, dass nur Modell miteinander verglichen werden können, die in einem <strong>hierarchischen</strong> Zusammenhang miteinander stehen.</p>
<div id="def-model-hierarchies" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 6.5 (Modellhierarchie)</strong></span> Eine Modellhierarchie beschreibt eine verschachtelte Modellstruktur (nested models) von statistischen Modellen. Jedes Modell in der Hierarchie stellt eine Teilmenge (oder einen Spezialfall) eines darauffolgenden komplexeren Modells dar. Modelle die hierarchisch miteinander in Beziehung stehen können einfach miteinander verglichen werden.</p>
</div>
<p>Insgesamt ist durch die Modellvergleiche ein flexiblen Ansatz gewonnen um Modellparameter zu testen. Bisher wurde immer nur ein einzelner Parameter anhand des zum jeweiligen Koeffizienten <span class="math inline">\(\beta_i\)</span> gehörenden <span class="math inline">\(t\)</span>-Werts getestet. Die Interpretation war hier die resultierende Steigung der zum Koeffizienten gehörenden Grade. Mittels der Modellvergleiche, ergibt sich nun eine zweite Interpretation in Form der Reduktion der Fehlerquadrate. Der Modellvergleich erlaubt darüber hinaus dasjenige Modell zu bestimmen, welches die Daten am <em>Besten</em> bzw. am einfachsten (mit den wenigsten Parametern) modelliert.</p>
<p>Als letzter Schritt, nun werden nun Modellvergleiche betrachtet, bei denen eine nominale Variable am Modell beteiligt ist. Wie bereits diskutiert, werden diese Variablen mittels Indikatorvariablen repräsentiert. In <a href="#fig-mlm-hier-rtex" class="quarto-xref">Abbildung&nbsp;<span>6.18</span></a> ist wieder das hypothetische Beispiel mit Reaktionszeiten unter vier verschiedenen Konditionen <code>A</code>, <code>B</code>, <code>C</code> und <code>D</code> abgetragen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-hier-rtex" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-hier-rtex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-hier-rtex-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-hier-rtex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;6.18: Ein Reaktionszeitexperiment mit vier Stufen A, B, C und D
</figcaption>
</figure>
</div>
</div>
</div>
<p>Klassischerweise würde diese Art von Daten mittels einer Varianzanalyse (ANOVA) untersuchen. Mittels der Modellvergleiche kann aber die <em>nominale</em> Variable Kondition einfach über zwei Modelle getestet werden. Als Modellhierarchien interpretiert wird das vollständige Modell bei dem beispielsweise die Faktorstufe <code>A</code> als Referenz definiert wird und mittels dreier Dummy-Variablen (<span class="math inline">\(K-1\)</span>) die Abweichungen der Stufen <code>B</code>-<code>D</code> von <code>A</code> modelliert werden. Daraus folgt, dass <span class="math inline">\(p = 4\)</span> gilt.</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_{\Delta_{B-A}} x_1 + \beta_{\Delta_{C-A}} x_2 + \beta_{\Delta_{D-A}} x_3 + \epsilon_i
\]</span></p>
<p>Als reduziertes Modell sein nun das Modell mit nur einem <span class="math inline">\(y\)</span>-Achsenabschnitt und dementsprechend nur einem Parameter <span class="math inline">\(\beta_0\)</span> und somit <span class="math inline">\(p = 1\)</span>. Das reduziert Modell hat daher die Formulierung:</p>
<p><span class="math display">\[
y_i = \beta_0 + \epsilon_i
\]</span></p>
<p>Wenn das reduzierte Modell die Daten gleich gut fittet wie das vollständige Modell dann bedeutet dies, dass die zusätzliche Information über die verschiedenen Konditionstufen die Vorhersage von <span class="math inline">\(y_i\)</span> nicht verbessert. D.h. ein einzelner Parameter reicht aus um die Daten zu fitten. Letztendlich bedeutet dies nichts anderes als <span class="math inline">\(\beta_{\Delta_{B-A}} = \beta_{\Delta_{C-A}} = \beta_{\Delta_{D-A}} =0\)</span>, also dass die Koeffizienten, welche die Abweichungen der Faktorstufen von der Referenzstufen bedeuten alle gleich Null sind. Tatsächlich lässt sich zeigen, das das berechnete <span class="math inline">\(F\)</span> über den Modellvergleich das gleich ist, wie bei einer <em>normalen</em> ANOVA. Insgesamt folgt daraus nochmal, dass die ANOVA und die Regression letztendlich auf das gleiche Modell zurück gehen, nämlich auf das <strong>Allgemeine Lineare Modell</strong>. Unter dem allgemeinen linearen Modell sind die ANOVA und die Regression beides spezielle Fälle desselben grundlegenden statistischen Modells. Wie bisher immer wieder wiederholt beruht das Modell auf einer Beschreibung eines Zusammenhangs zwischen einer abhängigen Variable und einer oder mehreren unabhängigen Variablen durch eine lineare Gleichung. Bei der Regression sind die unabhängigen Variablen kontinuierlich und werden oft genutzt, um Vorhersagen zu treffen. Bei der ANOVA hingegen sind die unabhängigen Variablen nominale und dienen dazu, Mittelwertsunterschiede zwischen Gruppen zu analysieren. Trotz dieser unterschiedlichen Anwendungsbereiche beruhen beide Verfahren auf denselben mathematischen Prinzipien zur Schätzung von Effekten und zur Überprüfung von Hypothesen.</p>
<div id="def-general-linear-model" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 6.6 (Allgemeine Lineare Modell )</strong></span> Das allgemeine lineare Modell (ALM) ist ein statistisches Verfahren, das den Zusammenhang zwischen <strong>einer</strong> abhängigen Variable und einer oder mehreren unabhängigen Variablen durch eine <strong>lineare Gleichung</strong> beschreibt. Dem ALM liegt die Annahme zugrunde, dass der Wert der abhängigen Variable durch eine lineare Kombination der <span class="math inline">\(p\)</span> unabhängigen Variablen und ihrer jeweiligen Gewichte (Modellkoeffizienten) vorhergesagt werden kann. In der Modellformulierung ist zusätzlich eine additive, zufällige Fehlerkomponente enthalten. Die Formulierung hat daher die folgende Form:</p>
<p><span id="eq-general-linear-model"><span class="math display">\[
Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \cdots + \beta_p X_{pi} + \epsilon_i
\tag{6.6}\]</span></span></p>
</div>
</section>
<section id="zum-weiterlesen" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="zum-weiterlesen"><span class="header-section-number">6.7</span> Zum Weiterlesen</h2>
<p>Viele der Ideen die hier diskutiert werden sind aus <span class="citation" data-cites="christensen2018">Christensen (<a href="references.html#ref-christensen2018" role="doc-biblioref">2018, p.57–64</a>)</span>. Daher wer noch mal etwas mehr Hintergrund dazu haben möchte, sei diese Quelle wärmstens empfohlen.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-christensen2018" class="csl-entry" role="listitem">
Christensen, Ronald. 2018. <em>Analysis of variance, design, and regression: Linear modeling for unbalanced data</em>. CRC Press.
</div>
<div id="ref-debanne2011" class="csl-entry" role="listitem">
Debanne, Thierry, und Guillaume Laffaye. 2011. <span>„Predicting the throwing velocity of the ball in handball with anthropometric variables and isotonic tests“</span>. <em>Journal of Sports Sciences</em> 29 (7): 705–13.
</div>
<div id="ref-jiroumaru2023" class="csl-entry" role="listitem">
Jiroumaru, Takumi, Yutaro Hyodo, Michio Wachi, Nobuko Shichiri, Junko Ochi, und Takamitsu Fujikawa. 2023. <span>„Relationship between walking speed, respiratory muscle strength, and dynamic balance in community-dwelling older people who required long-term care or support and used a daycare center“</span>. <em>PeerJ</em> 11: e16630.
</div>
<div id="ref-kutner2005" class="csl-entry" role="listitem">
Kutner, Michael H, Christopher J Nachtsheim, John Neter, und William Li. 2005. <em>Applied Linear Statistical Models</em>. 5. Aufl. McGraw-Hill Irwin New York.
</div>
<div id="ref-riechman2002" class="csl-entry" role="listitem">
Riechman, Steven E, Robert F Zoeller, G Balasekaran, Fredric L Goss, und Robert J Robertson. 2002. <span>„Prediction of 2000 m indoor rowing performance using a 30 s sprint and maximal oxygen uptake“</span>. <em>Journal of Sports Sciences</em> 20 (9): 681–87.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./mlm_title.html" class="pagination-link" aria-label="Das Lineare Modell und Erweiterungen">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Das Lineare Modell und Erweiterungen</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./mlm_logistic.html" class="pagination-link" aria-label="Logistische Regression">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>