<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Grundlagen und Inferenz – Skriptum - Fortgeschrittene Statistik</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./slm_model_fit.html" rel="next">
<link href="./slm_title.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-631496449bf32ff9b0bb69a6bfd9195d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>
<script>

  MathJax = {

    tex: {

      tags: 'ams'  // should be 'ams', 'none', or 'all'

    }

  };

</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./slm_title.html">Das einfache Regressionmodell</a></li><li class="breadcrumb-item"><a href="./slm_basics.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Grundlagen und Inferenz</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skriptum - Fortgeschrittene Statistik</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stats_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistik - Die Grundlagen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Eine kleine Welt der Unsicherheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistische Signifikanz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Hypothesentests</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./slm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das einfache Regressionmodell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_basics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Grundlagen und Inferenz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_model_fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modellfit</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./mlm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das Lineare Modell und Erweiterungen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_lmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Gemischte Lineare Modelle</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./ed_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_causal_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Kausale Inferenz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Messfehler und Reliabilität</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_factorial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Faktorielle Untersuchungsdesigns</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_misc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Weitere Untersuchungsdesigns</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literatur</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#back-to-school" id="toc-back-to-school" class="nav-link active" data-scroll-target="#back-to-school"><span class="header-section-number">4.1</span> Back to school</a></li>
  <li><a href="#funktionaler-versus-stochastischer-zusammenhang-zwischen-zwei-variablen" id="toc-funktionaler-versus-stochastischer-zusammenhang-zwischen-zwei-variablen" class="nav-link" data-scroll-target="#funktionaler-versus-stochastischer-zusammenhang-zwischen-zwei-variablen"><span class="header-section-number">4.2</span> Funktionaler versus stochastischer Zusammenhang zwischen zwei Variablen</a></li>
  <li><a href="#die-einfache-lineare-regression" id="toc-die-einfache-lineare-regression" class="nav-link" data-scroll-target="#die-einfache-lineare-regression"><span class="header-section-number">4.3</span> Die einfache lineare Regression</a></li>
  <li><a href="#methode-der-kleinsten-quadrate" id="toc-methode-der-kleinsten-quadrate" class="nav-link" data-scroll-target="#methode-der-kleinsten-quadrate"><span class="header-section-number">4.4</span> Methode der kleinsten Quadrate</a></li>
  <li><a href="#was-bedeuten-die-koeffizienten" id="toc-was-bedeuten-die-koeffizienten" class="nav-link" data-scroll-target="#was-bedeuten-die-koeffizienten"><span class="header-section-number">4.5</span> Was bedeuten die Koeffizienten?</a></li>
  <li><a href="#statistische-überprüfung-von-beta_1-und-beta_0" id="toc-statistische-überprüfung-von-beta_1-und-beta_0" class="nav-link" data-scroll-target="#statistische-überprüfung-von-beta_1-und-beta_0"><span class="header-section-number">4.6</span> Statistische Überprüfung von <span class="math inline">\(\beta_1\)</span> und <span class="math inline">\(\beta_0\)</span></a></li>
  <li><a href="#gauss-markov-modell" id="toc-gauss-markov-modell" class="nav-link" data-scroll-target="#gauss-markov-modell"><span class="header-section-number">4.7</span> Gauss-Markov-Modell</a></li>
  <li><a href="#teststatistik-für-beta_1" id="toc-teststatistik-für-beta_1" class="nav-link" data-scroll-target="#teststatistik-für-beta_1"><span class="header-section-number">4.8</span> Teststatistik für <span class="math inline">\(\beta_1\)</span></a></li>
  <li><a href="#teststatistik-für-beta_0" id="toc-teststatistik-für-beta_0" class="nav-link" data-scroll-target="#teststatistik-für-beta_0"><span class="header-section-number">4.9</span> Teststatistik für <span class="math inline">\(\beta_0\)</span></a></li>
  <li><a href="#konfidenzintervalle-für-die-koeffizienten" id="toc-konfidenzintervalle-für-die-koeffizienten" class="nav-link" data-scroll-target="#konfidenzintervalle-für-die-koeffizienten"><span class="header-section-number">4.10</span> Konfidenzintervalle für die Koeffizienten</a></li>
  <li><a href="#weiteres-material" id="toc-weiteres-material" class="nav-link" data-scroll-target="#weiteres-material"><span class="header-section-number">4.11</span> Weiteres Material</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./slm_title.html">Das einfache Regressionmodell</a></li><li class="breadcrumb-item"><a href="./slm_basics.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Grundlagen und Inferenz</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Grundlagen und Inferenz</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="back-to-school" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="back-to-school"><span class="header-section-number">4.1</span> Back to school</h2>
<p>Wir beginnen mit einem uns schon bekannten Konzept, der Punkt-Steigungsform aus der Schule (siehe <a href="#eq-slm-psform-1" class="quarto-xref">Gleichung&nbsp;<span>4.1</span></a>).</p>
<p><span id="eq-slm-psform-1"><span class="math display">\[
y = m x + b
\tag{4.1}\]</span></span></p>
<p>Wir haben eine abhängige Variable <span class="math inline">\(y\)</span> und eine lineare Formel <span class="math inline">\(mx + b\)</span> die den funktionalen Zusammenhang zwischen den Variablen <span class="math inline">\(y\)</span> und <span class="math inline">\(x\)</span> beschreibt. Um dies konkret zu machen seien die folgenden Festsetzungen gegeben: <span class="math inline">\(m = 2\)</span> und <span class="math inline">\(b = 3\)</span>. Die <a href="#eq-slm-psform-1" class="quarto-xref">Gleichung&nbsp;<span>4.1</span></a> wird dann zu:</p>
<p><span id="eq-slm-psform-2"><span class="math display">\[
y = 2 x + 3
\tag{4.2}\]</span></span></p>
<p>Um ein paar Werte für <span class="math inline">\(y\)</span> zu erhalten, setzen wir jetzt verschiedene Werte für <span class="math inline">\(x\)</span> ein, indem wir <span class="math inline">\(x\)</span> in Einserschritten zwischen <span class="math inline">\([0, \ldots, 5]\)</span> erhöhen. Um die Werte darzustellen, verwenden wir zunächst eine Tabelle (vgl. <a href="#tbl-slm-psform" class="quarto-xref">Tabelle&nbsp;<span>4.1</span></a>):</p>
<div class="cell">
<div id="tbl-slm-psform" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-slm-psform-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.1: Tabelle der Daten
</figcaption>
<div aria-describedby="tbl-slm-psform-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">x</th>
<th style="text-align: right;">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">13</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Wenig überraschend nimmt <span class="math inline">\(y\)</span> für den Wert <span class="math inline">\(x = 0\)</span> den Wert <span class="math inline">\(3\)</span> an und z. B. für den Wert <span class="math inline">\(x = 3\)</span> nimmt <span class="math inline">\(y\)</span> den Wert <span class="math inline">\(2 \cdot 3 + 3 = 9\)</span> an.</p>
<p>Eine weitere Darstellungsform ist die graphische Darstellung, indem wir die Werte von <span class="math inline">\(y\)</span> gegen <span class="math inline">\(x\)</span> in einem Graphen abtragen (siehe <a href="#fig-slm-psform-1" class="quarto-xref">Abbildung&nbsp;<span>4.1</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-psform-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-psform-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-psform-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-psform-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.1: Graphische Darstellung der Daten aus <a href="#tbl-slm-psform" class="quarto-xref">Tabelle&nbsp;<span>4.1</span></a>
</figcaption>
</figure>
</div>
</div>
</div>
<p>Wiederum wenig überraschend sehen wir einen linearen Zuwachs der <span class="math inline">\(y\)</span>-Werte mit den größer werdenden <span class="math inline">\(x\)</span>-Werten. Da in der Definition der Formel <a href="#eq-slm-psform-2" class="quarto-xref">Gleichung&nbsp;<span>4.2</span></a> nirgends festgelegt wurde, dass diese nur für ganzzahlige <span class="math inline">\(x\)</span>-Werte gilt, haben wir direkt eine Gerade durch die Punkte gelegt. Somit sollte auch die Bedeutung von <span class="math inline">\(m\)</span> und <span class="math inline">\(b\)</span> direkt klar sein. Die Variable <span class="math inline">\(m\)</span> bestimmt die Steigung der Gleichung, während <span class="math inline">\(b\)</span> den y-Achsenabschnitt beschreibt.</p>
<div id="def-slm-basics-y-intercept" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4.1 (<span class="math inline">\(y\)</span>-Achsenabschnitt)</strong></span> Der y-Achsenabschnitt ist der Wert, den <span class="math inline">\(y\)</span> einnimmt, wenn <span class="math inline">\(x\)</span> den Wert <span class="math inline">\(0\)</span> annimmt. Sei <span class="math inline">\(y\)</span> durch eine lineare Gleichung <span class="math inline">\(y = mx + b\)</span> definiert, dann wird der y-Achsenabschnitt durch den Wert <span class="math inline">\(b\)</span> bestimmt.</p>
</div>
<p>Die Variable <span class="math inline">\(m\)</span> hingegen bestimmt die Steigung der Geraden.</p>
<div id="def-slm-basics-slope" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4.2 (Steigungskoeffizient)</strong></span> Wenn <span class="math inline">\(y\)</span> durch eine lineare Gleichung <span class="math inline">\(y = mx + b\)</span> definiert ist, dann bestimmt die Variable <span class="math inline">\(m\)</span> die Steigung der dazugehörenden Geraden. D. h., wenn sich die Variable <span class="math inline">\(x\)</span> um eine Einheit vergrößert (verkleinert), wird der Wert von <span class="math inline">\(y\)</span> um <span class="math inline">\(m\)</span> Einheiten größer (kleiner). Gilt <span class="math inline">\(m &lt; 0\)</span>, dann umgekehrt.</p>
</div>
<p>Diese beiden trivialen Konzepte mit eigenen Definitionen zu versehen, erscheint im ersten Moment vielleicht etwas übertrieben. Wie sich allerdings später zeigen wird, sind diese beiden Einsichten immer wieder zentral, wenn es um die Interpretation von linearen statistischen Modellen geht.</p>
<p>Soweit so gut. Führen wir direkt ein paar Symbole ein, die uns später noch behilflich sein werden. Sei jetzt die Menge der <span class="math inline">\(x\)</span>-Werte gegeben <span class="math inline">\(x = [0, 1, 2, 3, 4, 5]\)</span>. Streng genommen handelt es sich wieder um ein Tupel, da wir jetzt die Reihenfolge nicht mehr ändern. Wir führen nun einen Index <span class="math inline">\(i\)</span> ein, um einzelne Werte in dem Tupel über ihre Position zu bestimmen, und wir hängen diesen Index <span class="math inline">\(i\)</span> an <span class="math inline">\(x\)</span> an. Dann wird aus <span class="math inline">\(x\)</span>, <span class="math inline">\(x_i\)</span>.</p>
<div class="cell">
<div id="tbl-slm-basic-index" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-slm-basic-index-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.2: <span class="math inline">\(x\)</span>-Werte und ihr Index <span class="math inline">\(i\)</span>
</figcaption>
<div aria-describedby="tbl-slm-basic-index-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Index <span class="math inline">\(i\)</span></th>
<th style="text-align: right;"><span class="math inline">\(x\)</span>-Wert</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Damit können wir jetzt einen speziellen Wert, zum Beispiel den dritten Wert, mit <span class="math inline">\(x_3 = 2\)</span> bestimmen. Wenden wir unseren Index auf unsere Formel <span class="math inline">\(\eqref{eq-slm-psform-1}\)</span> an, folgt daraus, dass <span class="math inline">\(y\)</span> jetzt auch einen Index <span class="math inline">\(i\)</span> erhält.</p>
<p><span class="math display">\[
y_i = m x_i + b \qquad i \text{ in } [1,2,3,4,5,6]
\]</span></p>
<p>Wir bezeichnen die beiden Variablen <span class="math inline">\(m\)</span>, die Steigung, und <span class="math inline">\(b\)</span>, den y-Achsenabschnitt, mit neuen Variablen, die ebenfalls einen Index erhalten. Aus <span class="math inline">\(m\)</span> wird <span class="math inline">\(\beta_1\)</span> und aus <span class="math inline">\(b\)</span> wird <span class="math inline">\(\beta_0\)</span>. Damit wird der y-Achsenabschnitt mit <span class="math inline">\(\beta_0\)</span> bezeichnet und die Steigung wird mit <span class="math inline">\(\beta_1\)</span> bezeichnet. Dann wird aus unserer Gleichung:</p>
<p><span id="eq-slm-psform-beta"><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i
\tag{4.3}\]</span></span></p>
<p>Formel <span class="math inline">\(\eqref{eq-slm-psform-beta}\)</span> ist immer noch die einfache Punkt-Steigungsform. Es wurde lediglich der Index <span class="math inline">\(i\)</span> eingeführt, um unterschiedliche <span class="math inline">\(x-y\)</span>-Wertepaare zu identifizieren. Weiterhin wurde der <span class="math inline">\(y\)</span>-Achsenabschnitt und die Steigung mit neuen Symbolen versehen. Wenn im späteren Verlauf des Skripts die die multiple linearen Regression eingeführt wird, hat diese Nomenklatur große Vorteile, da nicht mehr nur eine einzige <span class="math inline">\(x\)</span>-Variable vorhanden ist sondern mehrere. Hier vereinfacht die Benutzung von <span class="math inline">\(\beta\)</span>s die Schreibweise, da zusätzliche <span class="math inline">\(\beta\)</span>s nach Bedarf angehängt werden können und mit einem fortlaufenden Index (z. B. <span class="math inline">\(\beta_2, \beta_3, \ldots\)</span>) versehen werden können.</p>
<p>Bezogen auf die Datenpunkte, nochmal jeder Datenpunkt besteht aus zwei Koordinaten, einem <span class="math inline">\(x\)</span>-Wert und einem <span class="math inline">\(y\)</span>-Wert. Um die Datenpunkte voneinander auseinander zu halten verwenden wir den Index <span class="math inline">\(i\)</span> (siehe <a href="#fig-slm-basic-index-2" class="quarto-xref">Abbildung&nbsp;<span>4.2</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basic-index-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-basic-index-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-basic-index-2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-basic-index-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.2: <span class="math inline">\(x-y\)</span>-Werte und ihr Index <span class="math inline">\(i\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="funktionaler-versus-stochastischer-zusammenhang-zwischen-zwei-variablen" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="funktionaler-versus-stochastischer-zusammenhang-zwischen-zwei-variablen"><span class="header-section-number">4.2</span> Funktionaler versus stochastischer Zusammenhang zwischen zwei Variablen</h2>
<p>Bei dem bisherigen Zusammenhang handelt es sich um einen funktionalen Zusammenhang zwischen den beiden Variablen <span class="math inline">\(x\)</span> und <span class="math inline">\(y\)</span>. Funktional deswegen, weil wir ein definiertes mathematisches Modell angeben können, d.&nbsp;h., wir haben eine präzise mathematische Funktion, welche die Beziehung zwischen den beiden Variablen beschreibt. Wenn wir den Wert für <span class="math inline">\(x\)</span> kennen, dann können wir einen einzigen Wert für <span class="math inline">\(y\)</span> ausrechnen, indem wir den Wert <span class="math inline">\(x\)</span> in <a href="#eq-slm-psform-1" class="quarto-xref">Gleichung&nbsp;<span>4.1</span></a> einsetzen. Aus der Schule kennen wir noch die Darstellung <span class="math inline">\(y = f(x)\)</span>. Streng genommen ist diese Darstellung für Formel <a href="#eq-slm-psform-1" class="quarto-xref">Gleichung&nbsp;<span>4.1</span></a> nicht ausreichend, denn um den Wert für <span class="math inline">\(y\)</span> auszurechnen, benötigen wir auch noch Kenntnis über die Werte <span class="math inline">\(m\)</span> und <span class="math inline">\(b\)</span>, bzw. in unserer weiteren Darstellung <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>. Daher sollte der Zusammenhang eigentlich mit <span class="math inline">\(y = f(x, \beta_0, \beta_1)\)</span> bezeichnet werden. Es gilt aber immer noch: Für gegebene <span class="math inline">\(x, \beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> ist der Wert für <span class="math inline">\(y\)</span> fest determiniert.</p>
<p>Wenn wir mit realen Daten arbeiten, funktioniert dieser Ansatz leider nicht direkt. Selbst wenn wir ein Experiment mehrmals genau gleich durchführen, werden wir immer etwas unterschiedliche Werte im Sinne der Messungenauigkeit messen. Wenn wir biologische Systeme messen, kommt hinzu, dass diese in den seltensten Fällen zeitstabil sind, sondern immer bestimmte Veränderungen von einem Zeitpunkt zum nächsten auftauchen.</p>
<p>In <a href="#fig-slm-basics-jump-1" class="quarto-xref">Abbildung&nbsp;<span>4.3</span></a> ist ein realer Datensatz abgetragen. Auf der <span class="math inline">\(y\)</span>-Achse sind die Sprungweiten von mehreren Weitspringerinnen gegen die Anlaufgeschwindigkeit auf der <span class="math inline">\(x\)</span>-Achse abgetragen. Bei der Betrachtung der Daten erscheint ein linearer Zusammenhang zwischen diesen beiden Variablen durchaus plausibel.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-jump-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-basics-jump-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-basics-jump-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-basics-jump-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.3: Zusammenhang der Anlaufgeschwindigkeit und der Sprungweite beim Weitsprung
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-basics-jump-1" class="quarto-xref">Abbildung&nbsp;<span>4.3</span></a> sind zwei Punkte rot markiert. Die beiden Werte haben praktisch den gleichen <span class="math inline">\(x\)</span>-Wert, unterscheiden sich allerdings bezüglich ihrer <span class="math inline">\(y\)</span>-Werte deutlich voneinander. Und dies sind nicht die einzigen Beispielpaare, bei denen die <span class="math inline">\(x\)</span>-Werte nahe zusammenliegen, während die <span class="math inline">\(y\)</span>-Werte klar voneinander getrennt sind. Dies steht im Unterschied zu einem funktionalen Zusammenhang nach <a href="#eq-slm-psform-1" class="quarto-xref">Gleichung&nbsp;<span>4.1</span></a>. Bei einem rein funktionalen Zusammenhang wird jedem <span class="math inline">\(x\)</span>-Wert genau ein <span class="math inline">\(y\)</span>-Wert zugeordnet.</p>
<p>Die Abweichungen kommen durch zufällige Einflussfaktoren wie eben die Veränderungen angesprochener biologischer Faktoren und Messunsicherheiten. Beim Beispiel des Weitsprungs spielen auch noch externe Einflüsse, wie beispielsweise Windverhältnisse, eine Rolle. Vielleicht hatte der Springer beim zweiten Mal auch keine Lust mehr. Wenn die Punkte zwei unterschiedliche Springer darstellen, kommt hinzu, dass zwei Weitspringer bei identischer Anlaufgeschwindigkeit unterschiedliche Sprungfähigkeiten haben oder auch technisch nicht gleich gesprungen sind, und so weiter. Insgesamt führen all diese Einflüsse dazu, dass wir nicht mehr einen streng funktionalen Zusammenhang zwischen unseren beiden Variablen <span class="math inline">\(x\)</span> (der Anlaufgeschwindigkeit) und <span class="math inline">\(y\)</span> (der Sprungweite) vorfinden. Es handelt sich um einen <strong>stochastischen Zusammenhang</strong> zwischen den beiden Variablen. Wie wir mit diesen zufälligen Einflüssen umgehen, ist das zentrale Thema des nächsten Abschnitts und markiert auch unseren Einstieg in die einfache lineare Regression.</p>
</section>
<section id="die-einfache-lineare-regression" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="die-einfache-lineare-regression"><span class="header-section-number">4.3</span> Die einfache lineare Regression</h2>
<p>Bleiben wir bei unserem Beispiel aus <a href="#fig-slm-basics-jump-1" class="quarto-xref">Abbildung&nbsp;<span>4.3</span></a>. Wir versetzen uns in die Lage einer Weitsprungtrainerin, die vor der Aufgabe steht, ihr Training zu optimieren, um die Weitsprungleistung ihrer Athleten zu verbessern. Wir haben uns dazu entschlossen, am Anlauf etwas zu verbessern, wissen jetzt aber nicht, ob das wirklich lohnenswert ist. Von einer befreundeten Trainerin haben wir einen Datensatz mit Anlaufgeschwindigkeiten und den dazugehörigen Sprungweiten erhalten. Schauen wir uns zunächst einmal die Struktur der Daten an.</p>
<div class="cell">
<div id="tbl-slm-basics-jump-1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-slm-basics-jump-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.3: Ausschnitt der Sprungdaten
</figcaption>
<div aria-describedby="tbl-slm-basics-jump-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">jump_m</th>
<th style="text-align: right;">v_ms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">4.36</td>
<td style="text-align: right;">6.13</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.31</td>
<td style="text-align: right;">6.39</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4.56</td>
<td style="text-align: right;">6.56</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.75</td>
<td style="text-align: right;">6.44</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5.52</td>
<td style="text-align: right;">7.30</td>
</tr>
<tr class="even">
<td style="text-align: right;">5.63</td>
<td style="text-align: right;">7.19</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5.70</td>
<td style="text-align: right;">7.30</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In <a href="#tbl-slm-basics-jump-1" class="quarto-xref">Tabelle&nbsp;<span>4.3</span></a> sind die ersten <span class="math inline">\(7\)</span> Zeilen der Sprungdaten abgebildet. Die Daten zeigen eine einfache Struktur mit zwei Spalten. <code>jump_m</code> bezeichnet die Sprungweiten und <code>v_ms</code> die Anlaufgeschwindigkeiten. Damit wir die Datenpaare voneinander unterscheiden bzw. identifizieren können, führen wir unseren bereits besprochenen Index <span class="math inline">\(i\)</span> ein und können so einzelne Paare ansprechen.</p>
<div class="cell">
<div id="tbl-slm-basics-jump-2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-slm-basics-jump-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.4: Ausschnitt der Sprungdaten
</figcaption>
<div aria-describedby="tbl-slm-basics-jump-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">i</th>
<th style="text-align: right;">jump_m</th>
<th style="text-align: right;">v_ms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.36</td>
<td style="text-align: right;">6.13</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">4.31</td>
<td style="text-align: right;">6.39</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">4.56</td>
<td style="text-align: right;">6.56</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4.75</td>
<td style="text-align: right;">6.44</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">5.52</td>
<td style="text-align: right;">7.30</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">5.63</td>
<td style="text-align: right;">7.19</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">5.70</td>
<td style="text-align: right;">7.30</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Daher hat zum Beispiel der dritte Datenpunkt <span class="math inline">\(i = 3\)</span> die Datenwerte <span class="math inline">\(\text{jump}_3 = 4.31\)</span> und <span class="math inline">\(\text{v}_3 = 6.56\)</span>.</p>
<p>Das waren bisher aber nur Formalitäten. Wir wollen jetzt den Zusammenhang zwischen den beiden Variablen modellieren. Wir könnten wahrscheinlich auch einfach Pi-mal-Daumen abschätzen, wie groß der Zusammenhang ist. Wenn wir jetzt aber einen unserer Läufer haben, der z.B. etwa <span class="math inline">\(9m/s\)</span> anläuft, welchen Vergleichswert nehmen wir dann aus <a href="#fig-slm-basics-jump-1" class="quarto-xref">Abbildung&nbsp;<span>4.3</span></a>? Den unteren oder den oberen der beiden roten Werte? Oder vielleicht den Mittelwert? Welchen Wert nehmen wir, wenn unser Athlet mit <span class="math inline">\(v=9.7m/s\)</span> anläuft? Da haben wir leider keinen Vergleichswert in unserer Tabelle. Daher wäre es schon ganz praktisch, eine Formel nach dem Muster von <a href="#eq-slm-psform-beta" class="quarto-xref">Gleichung&nbsp;<span>4.3</span></a> zu haben. Wie wir allerdings schon festgestellt haben, geht dies nicht so einfach, da wir eben das Problem mit den Einflussfaktoren haben, die dazu führen, dass die Werte nicht präzise auf einer Geraden liegen. Somit liegt die Herausforderung nun darin, eine Gerade zu finden, die möglichst <em>genau</em> die Daten widerspiegelt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-line-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-basics-line-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-basics-line-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-basics-line-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.4: Mögliche Geraden, um den Zusammenhang der Anlaufgeschwindigkeit und der Sprungweite zu modellieren
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-basics-line-1" class="quarto-xref">Abbildung&nbsp;<span>4.4</span></a> sind die Daten zusammen mit verschiedenen möglichen Geraden abgebildet. Eine kurze Überlegung macht schnell klar, dass es im Prinzip unendlich viele unterschiedliche Geraden gibt, die durch die Datenpunkte gelegt werden können. Da jede Gerade durch die beiden Parameter <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> spezifiziert ist, gibt es somit auch unendlich viele Kombinationen von <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>, die die jeweiligen Geraden definieren. Um nun eine spezielle Gerade aus den unendlich vielen Geraden auswählen zu können, benötigen wir ein Kriterium, das definiert, was eine besser passende versus eine schlechter passende Gerade durch die gegebenen Punkte ist. Das heißt, wir suchen eine Gerade, die im Sinne eines Kriteriums <em>optimal</em> ist. Tatsächlich gibt es verschiedene Möglichkeiten, Kriterien zu entwickeln. Das am weitesten verbreitete und auch intuitiv nachvollziehbare Kriterium basiert auf den quadrierten Abweichungen der Geraden von den Datenpunkten (engl. <strong>least squares</strong>). Versuchen wir daher nun, die Herleitung der least squares schrittweise nachzuvollziehen.</p>
</section>
<section id="methode-der-kleinsten-quadrate" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="methode-der-kleinsten-quadrate"><span class="header-section-number">4.4</span> Methode der kleinsten Quadrate</h2>
<p>Fangen wir dazu zunächst einmal mit den einfachen Abweichungen an, also nicht den quadrierten Abweichungen. In <a href="#fig-slm-basics-line-2" class="quarto-xref">Abbildung&nbsp;<span>4.5</span></a> ist zur Übersicht nur ein Ausschnitt der Daten zusammen mit einer möglichen Geraden eingezeichnet. Die senkrechten Abweichungen der Geraden zu den jeweiligen Datenpunkten sind rot eingezeichnet. Es ist ersichtlich, dass für diese Wahl der Geraden zwei Punkte ziemlich genau auf der Geraden liegen, während die anderen Punkte oberhalb bzw. unterhalb der Geraden liegen. Ein mögliches Kriterium könnte dementsprechend sein, diejenige Gerade aus den unendlich vielen zu finden, bei der die Abweichungen (die roten Linien) ein Minimum annehmen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-line-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-basics-line-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-basics-line-2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-basics-line-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.5: Abweichungen der Gerade von den Datenpunkten für die Daten mit einer Anlaufgeschwindigkeit zwischen <span class="math inline">\(8m/s\)</span> und <span class="math inline">\(10m/s\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Um die Abweichungen (rote Linien) berechnen zu können, benötigen wir für jeden beobachteten Wert den dazugehörigen Punkt auf der Geraden. Wenn wir die Gerade schon hätten, wäre das kein Problem. Bisher haben wir allerdings nur die Formel der Geraden. Die Punkte auf der Geraden sind mithilfe der Formel genau diejenigen <span class="math inline">\(y\)</span>-Werte, die für die jeweiligen <span class="math inline">\(x\)</span>-Werte mittels <span class="math inline">\(\beta_0 + \beta_1 x_i\)</span> berechnet werden. Die Abweichung für einen Punkt <span class="math inline">\(y_i\)</span> von der Geraden lässt sich somit wie folgt berechnen:</p>
<p><span class="math display">\[\begin{equation*}
\text{Abweichung}_i = y_i - (\beta_0 + \beta_1 x_i)
\end{equation*}\]</span></p>
<p>Entsprechend führt unser Kriterium, die Summation der Abweichungen über alle Punkte, zu folgender Formel:</p>
<p><span class="math display">\[\begin{equation*}
\text{min}\sum_{i=1}^n y_i - (\beta_0 + \beta_1 x_i) = \sum_{i=1}^n y_i - \beta_0 - \beta_1 x_i
\end{equation*}\]</span></p>
<p>Wir verschärfen das Kriterium, um eine optimale Gerade zu finden, indem wir größere Abweichungen stärker gewichten wollen als kleinere. Das heißt, große Abweichungen zwischen der Geraden und den Datenpunkten sollen stärker berücksichtigt werden als kleine Abweichungen. Dies können wir erreichen, indem wir die Abweichungen quadrieren. Dementsprechend erhalten wir die folgende Gleichung:</p>
<p><span id="eq-slm-basics-rms-1"><span class="math display">\[
E(\beta_0, \beta_1) = \sum_{i=1}^n(y_i - (\beta_0 + \beta_1 x_i))^2
\tag{4.4}\]</span></span></p>
<p>Mit <span class="math inline">\(E(\beta_0, \beta_1)\)</span> wird ausgedrückt, dass die Summe von der Wahl der beiden Parameter <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> abhängt. <span class="math inline">\(E\)</span> ist eine Funktion von <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>. Um unsere Gerade zu bestimmen, suchen wir daher das Minimum der Funktion <span class="math inline">\(E(\beta_0, \beta_1)\)</span> (<span class="math inline">\(E\)</span> steht hier für “error”).</p>
<p>Die Abweichungen der Punkte auf der Geraden von den tatsächlichen Datenpunkten spielen in der weiteren Betrachtung immer wieder eine wichtige Rolle und haben daher einen eigenen Term. Die Abweichungen werden als Residuen <span class="math inline">\(e_i\)</span> bezeichnet. Dementsprechend kann die Minimierungsgleichung auch so dargestellt werden:</p>
<p><span class="math display">\[\begin{equation*}
\text{min} \sum_{i=1}^n e_i^2
\end{equation*}\]</span></p>
<p>Es gilt <span class="math inline">\(e_i := y_i - (\beta_0 + \beta_1 x_i)\)</span>. Insgesamt ergibt sich:</p>
<p><span class="math display">\[\begin{equation*}
E(\beta_0, \beta_1) = \sum_{i=1}^n e_i^2 = \sum_{i=1}^n (y_i - \beta_0 - \beta_1 x_i)^2
\end{equation*}\]</span></p>
<p>Das Minimum lässt sich nun bestimmen, indem wir die partiellen Ableitungen von <span class="math inline">\(E\)</span> nach <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> berechnen und, wie wir es aus der Schule kennen, diese gleich Null setzen:</p>
<p><span class="math display">\[\begin{align*}
\frac{\partial E(\beta_0, \beta_1)}{\partial \beta_0} &amp;= -2 \sum_{i=1}^n (y_i - \beta_0 - \beta_1 x_i) = 0 \\
\frac{\partial E(\beta_0, \beta_1)}{\partial \beta_1} &amp;= -2 \sum_{i=1}^n x_i (y_i - \beta_0 - \beta_1 x_i) = 0
\end{align*}\]</span></p>
<p>Diese Gleichungen bilden ein Gleichungssystem mit zwei Unbekannten <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> und können mit etwas Algebra nach <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> aufgelöst werden (siehe <span class="quarto-unresolved-ref">?sec-step-by-step-normal</span>). Dies führt zu den folgenden Lösungen für <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>:</p>
<p><span id="eq-slm-basics-norm"><span class="math display">\[
\begin{align*}
\hat{\beta_1} &amp;= \frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^n (x_i - \bar{x})^2} \\
\hat{\beta_0} &amp;= \bar{y} - \hat{\beta_1} \bar{x}
\end{align*}
\tag{4.5}\]</span></span></p>
<p><span class="math inline">\(\bar{x}\)</span> und <span class="math inline">\(\bar{y}\)</span> sind die Mittelwerte von <span class="math inline">\(x_i\)</span> und <span class="math inline">\(y_i\)</span>. Diese beiden Gleichungen werden als die Normalengleichungen bezeichnet.</p>
<p>Wir führen noch einen weiteren Term ein: den vorhergesagten Wert <span class="math inline">\(\hat{y}_i\)</span> von <span class="math inline">\(y_i\)</span> anhand der Geradengleichung. Das Hütchen über <span class="math inline">\(y_i\)</span> zeigt an, dass es sich um einen geschätzten Wert handelt. Wenn wir <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> anhand der Normalengleichungen bestimmen, dann sind das mit großer Wahrscheinlichkeit nicht die <em>wahren</em> Werte aus der Population, sondern wir haben sie nur anhand der Daten geschätzt. Daher bekommen die berechneten Werte ebenfalls ein Hütchen <span class="math inline">\(\hat{\beta}_0\)</span> und <span class="math inline">\(\hat{\beta}_1\)</span>. Insgesamt nimmt die lineare Geradengleichung dann folgende Form an:</p>
<p><span class="math display">\[
\hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 \cdot x_i
\]</span></p>
<p>D.h. die Residuen können auch mittels <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span> dargestellt werden. Graphisch sind die <span class="math inline">\(\hat{y}_i\)</span>s die Werte auf der Geraden für die gegebenen <span class="math inline">\(x_i\)</span>-Werte.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-line-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-basics-line-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-basics-line-3-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-basics-line-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.6: Die vorhergesaten Werte <span class="math inline">\(\hat{y}_i\)</span> auf der Gerade.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Gehen wir zurück zu unseren Weitsprungdaten. Wenn wir die Datenpunkte in die Normalengleichungen <a href="#eq-slm-basics-norm" class="quarto-xref">Gleichung&nbsp;<span>4.5</span></a> einsetzen, dann erhalten wir für die Koeffizienten die Werte <span class="math inline">\(\hat{\beta}_0 = -0.14\)</span> und <span class="math inline">\(\hat{\beta}_1 = 0.76\)</span>. Somit folgt für die Geradengleichung:</p>
<p><span class="math display">\[
\hat{y}_i = -0.14 + 0.76 \cdot x_i
\]</span></p>
<p>Wir erhalten die graphische Darstellung der Geradengleichung indem die <span class="math inline">\(x_i\)</span>-Werte eingesetzt werden und eine Gerade durch die Punkte gezogen wird. Oder auch einfacher für den größten und den kleinsten <span class="math inline">\(x_i\)</span>-Wert.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-line-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-basics-line-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-basics-line-4-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-basics-line-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.7: Die Regressionsgerade der Sprungdaten.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Um uns auch zu vergewissern, dass unsere Berechnungen korrekt sind, schauen wir uns noch einmal an, wie sich <span class="math inline">\(E\)</span> verhält, wenn wir unterschiedliche Kombinationen von Werten für <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> in die lineare Gleichung einsetzen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-gradient" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-basics-gradient-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-basics-gradient-1.png" class="img-fluid figure-img" width="384">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-basics-gradient-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.8: Heatmap von <span class="math inline">\(log(E)\)</span> für verschiedene Werte von <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-basics-gradient" class="quarto-xref">Abbildung&nbsp;<span>4.8</span></a> sind verschiedene Werte für <span class="math inline">\(E\)</span> in Form einer Heatmap dargestellt. Die Abweichungen wurden <span class="math inline">\(log\)</span>-transformiert (d.&nbsp;h., der Logarithmus der <span class="math inline">\(E\)</span>-Werte wurde berechnet), da sonst die Unterschiede in der diagonalen Bildrichtung zu schnell wachsen und die Unterschiede nicht mehr so einfach zu erkennen sind. Werte näher an Weiß bedeuten kleine Werte, und Werte näher an Rot bedeuten größere Werte von <span class="math inline">\(E\)</span>. Das berechnete Paar für <span class="math inline">\((\hat{\beta}_0, \hat{\beta}_1)\)</span> mit <span class="math inline">\(\hat{\beta}_0 = -0.14\)</span> und <span class="math inline">\(\hat{\beta}_1 = 0.76\)</span> ist schwarz eingezeichnet. Die Abbildung zeigt, dass dieses Wertepaar tatsächlich ein Minimum bezüglich der Funktion <span class="math inline">\(E\)</span> ist, da in alle Richtungen weg von dem schwarzen Punkt die Werte für <span class="math inline">\(E\)</span> zunehmen. Da wir nur einen Ausschnitt der möglichen Werte sehen, handelt es sich zunächst um ein lokales Minimum, aber es lässt sich zeigen, dass es sich dabei auch um ein globales Minimum handelt. Diese Eigenschaft hängt mit der Form der Funktion <span class="math inline">\(E\)</span> zusammen. In <a href="#tbl-slm-basics-gradient" class="quarto-xref">Tabelle&nbsp;<span>4.5</span></a> sind beispielhaft ein paar Werte für <span class="math inline">\(log(E)\)</span> für Paare von <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> angezeigt, die in <a href="#fig-slm-basics-gradient" class="quarto-xref">Abbildung&nbsp;<span>4.8</span></a> gelb eingezeichnet sind.</p>
<div class="cell">
<div id="tbl-slm-basics-gradient" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-slm-basics-gradient-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.5: Werte von <span class="math inline">\(log(E)\)</span> für verschiedenen Kombinationen von <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>.
</figcaption>
<div aria-describedby="tbl-slm-basics-gradient-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(\beta_0\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\beta_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(log(E)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-0.48</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">70.34</td>
</tr>
<tr class="even">
<td style="text-align: right;">-0.44</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">51.85</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-0.38</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">22.04</td>
</tr>
<tr class="even">
<td style="text-align: right;">-0.30</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">6.46</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-0.22</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">3.77</td>
</tr>
<tr class="even">
<td style="text-align: right;">-0.14</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">2.41</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Wir können in <a href="#tbl-slm-basics-gradient" class="quarto-xref">Tabelle&nbsp;<span>4.5</span></a> erkennen, das das Wertepaar für <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>, welches wir mit Hilfe der Normalengleichung bestimmt haben, denn kleinesten Abweichungswert hat. Also im Sinne unseres Kriteriums ein Optimum darstellt.</p>
<div id="exm-slm-hursh" class="theorem example">
<p><span class="theorem-title"><strong>Beispiel 4.1 (Nervenleitgeschwindigkeit)</strong></span> In einem klassischen Artikel von <span class="citation" data-cites="hursh1939">Hursh (<a href="references.html#ref-hursh1939" role="doc-biblioref">1939</a>)</span> wurde der Zusammenhang zwischen der Leitungsgeschwindigkeit eines Neurons und dem Durchmesser seines Axons bei erwachsenen Katzen untersucht. Es wurde die maximale Geschwindigkeit der Nervenfasern in verschiedenen Nervenbündeln sowie der Durchmesser der größten Faser in jedem Bündel bestimmt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-hursh" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-basics-hursh-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-basics-hursh-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-basics-hursh-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.9: Leitungsgeschwindigkeit gegen die Nervenfaserdicke bei erwachsenen Katzen adaptiert nach Hursh (1939). Die Regressionsgerade ist in blau eingezeichnet.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Wie in <a href="#fig-slm-basics-hursh" class="quarto-xref">Abbildung&nbsp;<span>4.9</span></a> zu sehen ist, zeigen die Daten eine nahezu lineare Beziehung zwischen der maximalen Geschwindigkeit und dem Nervendurchmesser. Der <span class="math inline">\(y\)</span>-Achsenabschnitt liegt bei nahezu null. Dies kann dahingehend interpretiert werden, dass eine Verdoppelung des Faserdurchmessers für den beobachteten Berech der Nervendurchmesser nahezu zu einer verdoppelung der Leitungsgeschwindigkeit führt. Die eingezeichnet Regressionsgerade modelliert die Daten entsprechend gut.</p>
</div>
<p>Die Methode der kleinsten Quadrate hat tatsächlich schon ein lange Tradition und wurde bereits von Gauss im 19. Jhd angewandt.</p>
<blockquote class="blockquote">
<p>“<em>Die Bestimmung einer Grösse durch eine einem grösseren oder kleineren Fehler unterworfene Beobachtung wird nicht unpassend mit einem Glücksspiel verglichen, in welchem man nur verlieren, aber nicht gewinnen kann, wobei also jeder zu befürchtende Fehler einem Verluste entspricht. Das Risiko eines solchen Spieles wird nach dem wahrscheinlichen Verlust geschätzt, d.&nbsp;h. nach der Summe der Produkte der einzelnen möglichen Verluste in die zugehörigen Wahrscheinlickeiten. Welchem Verluste man aber jeden einzelnen Beobachtungsfehle gleichsetzen soll, ist keineswegs an sich klar: hängt doch vielmehr diese Bestimmung zum Theil von unserem Ermessen ab. Den Verlust dem Fehler selbst gleichzusetzen, ist offenbar nicht erlaubt; würden nämlich positive Fehler wie Verluste behandelt, so müssten negative als Gewinne gelten. Die Grösse des Verlustes muss vielmehr durch eine solche Funktion des Fehlers ausgedrückt werden, die ihrer Natur nach immer positiv ist. Bei der unendlichen Mannigfaltigkeit derartiger Funktionen scheint die einfachste, welche diese Eigenschaft besitzt, vor den übrigen den Vorzug zu verdienen, und diese ist unstreitig das Quadrat.</em>” <span class="citation" data-cites="gauss1887">(<a href="references.html#ref-gauss1887" role="doc-biblioref">Gauss 1887, 5–6</a>)</span></p>
</blockquote>
</section>
<section id="was-bedeuten-die-koeffizienten" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="was-bedeuten-die-koeffizienten"><span class="header-section-number">4.5</span> Was bedeuten die Koeffizienten?</h2>
<p>Gehen wir zurück zu unserem Ausgangsproblem der Weitspringer: Was haben wir jetzt durch die Berechnung der Geraden eigentlich gewonnen? Dazu müssen wir erst einmal verstehen, was die beiden Koeffizienten <span class="math inline">\(\hat{\beta}_0\)</span> und <span class="math inline">\(\hat{\beta}_1\)</span> bedeuten. Wenn wir zurück zu <a href="#eq-slm-psform-1" class="quarto-xref">Gleichung&nbsp;<span>4.1</span></a> gehen, beschreiben die beiden Koeffizienten den <span class="math inline">\(y\)</span>-Achsenabschnitt und die Steigung der Geraden. In unserem Beispiel haben wir anhand der Daten einen <span class="math inline">\(y\)</span>-Achsenabschnitt <span class="math inline">\(\hat{\beta}_0\)</span> von <span class="math inline">\(-0.14\)</span> berechnet. Das bedeutet, ein Weitspringer, der mit einer Anlaufgeschwindigkeit von <span class="math inline">\(x = 0\)</span> anläuft, landet <span class="math inline">\(14\)</span> cm hinter der Sprunglinie. Dies macht offensichtlich nicht viel Sinn (warum?). Den Grund, warum hier ein offensichtlich unrealistischer Wert berechnet wurde, werden wir später noch genauer betrachten. Trotzdem können wir zwei Eigenschaften von <span class="math inline">\(\hat{\beta}_0\)</span> beobachten:</p>
<ol type="1">
<li>Der Koeffizient hat eine Einheit, nämlich die gleiche Einheit wie die Variable <span class="math inline">\(y\)</span>.</li>
<li>Ob der Wert sinnvoll interpretierbar ist, hängt von der Verteilung der Daten ab.</li>
</ol>
<p>Schauen wir uns nun den Steigungskoeffizienten <span class="math inline">\(\hat{\beta}_1\)</span> an. Der Steigungskoeffizient in Formel <a href="#eq-slm-psform-1" class="quarto-xref">Gleichung&nbsp;<span>4.1</span></a> zeigt an, wie sich der <span class="math inline">\(y\)</span>-Wert verändert, wenn sich der <span class="math inline">\(x\)</span>-Wert um eine Einheit verändert. In unserem Fall beschreibt er, welcher Unterschied zwischen zwei Weitspringern zu erwarten ist, die sich in der Anlaufgeschwindigkeit um <span class="math inline">\(1 \, m/s\)</span> unterscheiden. Das bedeutet, der Steigungskoeffizient ist ebenfalls in der Einheit der <span class="math inline">\(y\)</span>-Variable zu interpretieren.</p>
<p>Unsere Trainerin kann die berechnete Gerade nun nutzen, um zu überprüfen, ob es sich lohnt, Trainingszeit in den Anlauf zu investieren, und welche Verbesserungen dort zu erwarten sind. Allerdings fehlt dazu noch etwas: Wir wissen nämlich noch nicht, ob die berechnete Gerade auch wirklich die Daten gut widerspiegelt. Im Beispiel erscheint dies anhand der Grafik als relativ plausibel. Das muss aber nicht immer so sein. Wir können für alle möglichen Daten eine Gerade berechnen, ohne dass diese Gerade die Daten auch nur annähernd korrekt wiedergibt. In den Formeln <a href="#eq-slm-basics-norm" class="quarto-xref">Gleichung&nbsp;<span>4.5</span></a> steht nirgends, für welche Daten die Berechnung zulässig ist.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-cubepoly" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-basics-cubepoly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-basics-cubepoly-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-basics-cubepoly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.10: Gefittete Gerade durch die Daten einer Funktion <span class="math inline">\(f(x) = x^3\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-basics-cubepoly" class="quarto-xref">Abbildung&nbsp;<span>4.10</span></a> sind synthetische Daten der Funktion <span class="math inline">\(f(x) = x^3\)</span> abgebildet, und die mittels <a href="#eq-slm-basics-norm" class="quarto-xref">Gleichung&nbsp;<span>4.5</span></a> berechnete Gerade ist eingezeichnet. Die Gerade ist zwar in der Lage, die ansteigenden Werte zu modellieren, aber nicht die Schwingungen, die durch die kubische Abhängigkeit zustande kommen. Dennoch verhindert nichts die Anwendung der Formel auf diese Daten!</p>
<p>Der gleiche Effekt ist auch in <a href="#fig-slm-basics-sinus" class="quarto-xref">Abbildung&nbsp;<span>4.11</span></a> zu beobachten. Hier besteht eine sinusförmige Abhängigkeit zwischen <span class="math inline">\(y\)</span> und <span class="math inline">\(x\)</span>. Wir können erneut die Normalengleichungen anwenden und erhalten ein Ergebnis für <span class="math inline">\(\hat{\beta}_0\)</span> und <span class="math inline">\(\hat{\beta}_1\)</span>. Allerdings repräsentiert die Gerade in keiner Weise den tatsächlichen Zusammenhang zwischen den Daten, wie in <a href="#fig-slm-basics-sinus" class="quarto-xref">Abbildung&nbsp;<span>4.11</span></a> zu sehen ist.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-sinus" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-basics-sinus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-basics-sinus-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-basics-sinus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.11: Gefittete Gerade durch die Daten einer Funktion <span class="math inline">\(f(x) = sin(x) + 3\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Im nächsten Kapitel werden wir uns daher damit beschäftigen die Repräsentation der Daten näher zu betrachten und zu präzisieren.</p>
<p>Wir nehmen noch eine weitere Eigenschaft der Gerade mit, die zunächst nichts mit der Interpretation der Koeffizienten zu tun hat, aber später noch mal von Interesse sein wird. Die Gerade hat nämlich die Eigenschaft durch den Punkt (<span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(\bar{y}\)</span>) zu gehen. Dies kann daran gesehen werden wenn in die Gleichung <span class="math inline">\(\bar{x}\)</span> für <span class="math inline">\(x_i\)</span> eingesetzt wird. Anhand von <a href="#eq-slm-basics-norm" class="quarto-xref">Gleichung&nbsp;<span>4.5</span></a> der Normalgleichungen kann die Geradengleichung in der folgenden Form dargestellt werden.</p>
<p><span class="math display">\[\begin{equation*}
y_i = \hat{\beta}_0 + \hat{\beta}_1 \cdot x_i = \underbrace{\bar{y} - \hat{\beta}_1 \bar{x}}_{\text{Def. }\hat{\beta}_0} + \hat{\beta}_1 \cdot x_i
\end{equation*}\]</span></p>
<p>Wird jetzt für <span class="math inline">\(x_i\)</span> der Mittelwer der <span class="math inline">\(x\)</span>-Werte <span class="math inline">\(\bar{x}\)</span> eingesetzt folgt daraus.</p>
<p><span class="math display">\[
y_i = \bar{y} - \hat{\beta}_1 \bar{x} + \hat{\beta}_1 \bar{x} = \bar{y}
\]</span></p>
<p>D.h. für den Wert <span class="math inline">\(\bar{x}\)</span> nimmt die Geradengleichung der Wert <span class="math inline">\(\bar{y}\)</span> an. Für die Sprungdaten ist diese Eigenschaft auch noch mal in <a href="#fig-slm-basics-hatxy" class="quarto-xref">Abbildung&nbsp;<span>4.12</span></a> graphisch dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-hatxy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-basics-hatxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-basics-hatxy-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-basics-hatxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.12: Regressionsgerade der Sprungdaten und der Punkt <span class="math inline">\((\bar{x}, \bar{y})\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
<p>Eine weitere Eigenschaft, die in der weiteren Behandlung der Regression immer wieder auftaucht, bezieht sich auf die <span class="math inline">\(x\)</span>-Werte. Bei der Regression wird im Allgemeinen davon ausgegangen, dass die beobachteten <span class="math inline">\(x\)</span>-Werte fixiert sind. Das bedeutet, obwohl die <span class="math inline">\(x\)</span>-Werte bei einem Experiment möglicherweise zufällige Werte angenommen haben, werden diese in den nachfolgenden Analyseschritten als fixiert bzw. gegeben angesehen.</p>
<p>Zusammenfassend lässt sich sagen, dass wir jetzt gelernt haben, wie wir ein einfaches Regressionsmodell der Form <a href="#eq-slm-psform-beta" class="quarto-xref">Gleichung&nbsp;<span>4.3</span></a> an einen beliebigen Datensatz fitten können. Die Berechnung der beiden Koeffizienten <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> erfolgt mithilfe von <a href="#eq-slm-basics-norm" class="quarto-xref">Gleichung&nbsp;<span>4.5</span></a>. Dabei berechnen wir die Koeffizienten nicht von Hand, sondern lassen sie von <code>R</code> mittels der Funktion <code>lm()</code> durchführen. Die Berechnung ist dabei vollkommen mechanisch, und die Koeffizienten selbst sagen nichts darüber aus, ob das lineare Modell die Daten tatsächlich auch widerspiegelt. Dazu müssen wir noch etwas mehr Theorie aufbauen, um Aussagen darüber treffen zu können, ob das Modell adäquat ist. Dies werden wir in den folgenden Abschnitten und Kapiteln angehen.</p>
<p>Da das einfache lineare Modell zwei Parameter <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> (siehe <a href="#eq-slm-psform-beta" class="quarto-xref">Gleichung&nbsp;<span>4.3</span></a>) beinhaltet, stellt sich Frage der Relevanz für die beiden Koeffizienten <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>. Anders formuliert führt dies zu der Fragestellung, ob das gefittete Modell einen statistisch signifikanten Zusammenhang zwischen den beiden Variablen <span class="math inline">\(X\)</span> und <span class="math inline">\(Y\)</span> beschreibt. Bezogen auf die beiden Parameter: Ist der Parameter <span class="math inline">\(\hat{\beta}_0\)</span> statistisch signifikant, und ist der Parameter <span class="math inline">\(\hat{\beta}_1\)</span> statistisch signifikant? Um den im vorhergehenden Abschnitt erarbeiteten Werkzeugsatz zur statistischen Signifikanz anwenden zu können, wird zunächst erst einmal wieder eine theoretische Verteilung benötigt welche die Verteilung der Koeffizienten, bzw. eine von den Koeffizienten abgeleiteten Statistik, unter einer <span class="math inline">\(H_0\)</span> beschreibt. Erst wenn diese Referenzverteilungen definiert sind, können <em>kritische</em> Bereiche identifiziert werden anhand derer entschieden werden kann, ob eine beobachtete Statistik statistisch signifikant ist. Dabei sei noch einmal betont, dass eine <em>statistische Signifikanz</em> nicht das Gleiche ist wie <em>praktische Relevanz</em> bzw. der Beweis einer Abweichung von einer gegebenen statistischen Hypothese.</p>
</section>
<section id="statistische-überprüfung-von-beta_1-und-beta_0" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="statistische-überprüfung-von-beta_1-und-beta_0"><span class="header-section-number">4.6</span> Statistische Überprüfung von <span class="math inline">\(\beta_1\)</span> und <span class="math inline">\(\beta_0\)</span></h2>
<p>Der erste Schritt, um eine Referenzverteilung zu erhalten, besteht zunächst darin, dass eine Zufallsvariable benötigt wird. Bisher wurde der Zusammenhang zwischen den Variablen über die Formel über den einfachen funktionalen Zusammenhang beschrieben:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 \cdot x_i
\]</span></p>
<p>In dieser Form ist allerdings noch gar kein <em>zufälliges</em> Element vorhanden. Für ein gegebenes <span class="math inline">\(x_i\)</span> wird genau ein spezifiziertes <span class="math inline">\(y_i\)</span> erhalten. Allerdings wurde schon bei der Herleitung der Regressionsgerade beoachtet, dass reale Daten in den seltensten Fällen genau auf der Gerade liegen. Letztendlich wurden wir die Parameter <span class="math inline">\(\hat{\beta}_0\)</span> und <span class="math inline">\(\hat{\beta}_1\)</span> genauso so gewählt, dass die quadrierten Abweichungen, die Residuen <span class="math inline">\(\epsilon_i\)</span>, minimal werden. Diese Residuen werden nun verwendet, um eine zufällige Komponente in das Regressionsmodell zu integrieren. Dazu muss den Residuen <span class="math inline">\(\epsilon_i\)</span> eine Verteilung zugewiesen werden.</p>
<p>Im Rahmen der vorhergehenden Herleitung zur statistischen Signifikanz wurden schon verschiedene theoretische Verteilungen kennengelernt. In diesem Zusammenhang hat sich die Normalverteilung als besonders praktisch erwiesen bzw. als eine Verteilung, die in verschiedenen Anwendungen eine passable Näherung an reale Daten liefert. Daher sei im Folgenden davon ausgegangen, dass die Residuen <span class="math inline">\(\epsilon_i\)</span> einer Normalverteilung folgen. Intuitiv wurde bei der Herleitung der Geradengleichung mittels der Methode der kleinsten Quadrate gesehen, dass die Abweichungen in etwa, in Abhängigkeit von der absoluten Abweichung, gleichmäßig oberhalb und unterhalb der Geraden verteilt waren.</p>
<p>Im behandelten Weitsprungbeispiel wurde informell hergeleitet, dass die Weitsprungleistung von unzähligen Faktoren beeinflusst werden kann. Diese Fakatoren führen, dass für eine gegebene Anlaufgeschwindigkeit nicht immer die gleiche Weitsprungweite erzielt wird. Generell ist diese Art der Begründung bei biologischen Systemen meistens plausibel. Im vorhergehenden Abschnitt wurde dazu auch noch gezeigt, dass die Normalverteilung gut geeignet ist, um Prozesse mit viele kleine additive Effekte zu modellieren. Dieser Argumentation folgend ist es also durchaus plausibel, die Gesamtheit von Störeinflüssen auch bei der Regression mittels einer Normalverteilung zu modellieren. Insgesamt erlaubt diese Annahme, die folgende, mathematisch Formulierung:</p>
<p><span id="eq-slm-inf-epsilon-norm"><span class="math display">\[
\epsilon_i \sim \mathcal{N}(0, \sigma^2)
\tag{4.6}\]</span></span></p>
<p>In <a href="#eq-slm-inf-epsilon-norm" class="quarto-xref">Gleichung&nbsp;<span>4.6</span></a> wird ausgedrückt, dass die Residuen <span class="math inline">\(\epsilon_i\)</span>, also die Abweichungen vom vorhergesagten Wert <span class="math inline">\(\hat{y}_i\)</span> zum beobachteten Wert <span class="math inline">\(y_i\)</span>, einer Normalverteilung mit einem Mittelwert von <span class="math inline">\(\mu = 0\)</span> und einer noch näher zu spezifizierenden Varianz <span class="math inline">\(\sigma^2\)</span> folgen. Der Mittelwert <span class="math inline">\(\mu = 0\)</span> drückt dabei unsere Erwartung aus, dass sich im Mittel die Abweichungen von der Geraden nach oben und nach unten gegenseitig aufheben. Der Skalenparameter <span class="math inline">\(\sigma^2\)</span> drückt dabei die Streuung der Werte um die Gerade aus. D.h., wenn <span class="math inline">\(\sigma^2\)</span> größer wird, dann streuen die Werte stärker um die Gerade, und entsprechend entgegengesetzt, wenn <span class="math inline">\(\sigma^2\)</span> kleiner ist. Insgesamt führt dies zu der folgenden Formulierung des einfachen Regressionsmodells:</p>
<p><span id="eq-slm-inf-simple-reg"><span class="math display">\[
Y_i = \beta_0 + \beta_1 \cdot x_i + \epsilon_i, \quad \epsilon_i \sim \mathcal{N}(0, \sigma^2)
\tag{4.7}\]</span></span></p>
</section>
<section id="gauss-markov-modell" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="gauss-markov-modell"><span class="header-section-number">4.7</span> Gauss-Markov-Modell</h2>
<p>Bezüglich der Residuen <span class="math inline">\(\epsilon_i\)</span> lässt sich noch eine weitere Spezifikation machen, auf die wir später noch öfter zurückgreifen werden. Bisher sind wir davon ausgegangen, dass die einzelnen Datenpunkte unabhängig voneinander sind. D.h., jeder einzelne Wert wird nicht durch einen der anderen Werte beeinflusst. In unserem Beispiel waren die Anlaufgeschwindigkeits-Sprungweiten-Paare jeweils von unterschiedlichen Athleten. In diesem Fall sind die Kovarianzen zwischen den Residuen <span class="math inline">\(= 0\)</span>, formal <span class="math inline">\(cov(e_i, e_j) = 0,~für~i \neq j\)</span>. Daher lassen sich die Varianzen und Kovarianzen von <span class="math inline">\(\epsilon_i\)</span> in Form einer sogenannten Varianz-Kovarianz-Matrix schreiben. Matrizen hatten wir schon in der Einführung zu <code>R</code> kennengelernt. Die Varianz-Kovarianz-Matrix bekommt per Konvention das Zeichen <span class="math inline">\(\Sigma\)</span>, und <span class="math inline">\(\mathbf{I}_n\)</span> bezeichnet die Einheitsmatrix.</p>
<p><span class="math display">\[\begin{equation*}
\Sigma = \begin{pmatrix}
\sigma^2 &amp; 0 &amp; \cdots &amp; 0 \\
0 &amp; \sigma^2 &amp; &amp; \vdots \\
\vdots &amp;  &amp; \ddots &amp;  \\
0 &amp; \cdots &amp; &amp; \sigma^2
\end{pmatrix} = \sigma^2 \begin{pmatrix}
1 &amp; 0 &amp; \cdots &amp; 0 \\
0 &amp; 1 &amp; &amp; \vdots \\
\vdots &amp;  &amp; \ddots &amp;  \\
0 &amp; \cdots &amp; &amp; 1
\end{pmatrix} = \sigma^2 \mathbf{I}_n
\end{equation*}\]</span></p>
<p>Die Annahmen des Modells, dass ein linearer Zusammenhang zwischen <span class="math inline">\(Y\)</span> und <span class="math inline">\(X\)</span> besteht, die einzelnen <span class="math inline">\(N\)</span> Datenpunkte unabhängig voneinander sind und die Residuen einer multivariaten Normalverteilung mit <span class="math inline">\(\epsilon \sim \mathcal{N}(0, \sigma^2 \mathbf{I}_n)\)</span> folgen, werden als Gauss-Markov-Modell bezeichnet.</p>
<div id="def-gauss-markov" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4.3 (Gauss-Markov-Modell)</strong></span> Besteht zwischen <span class="math inline">\(N\)</span> unabhängigen Datenpunkten <span class="math inline">\((y_i, x_i)\)</span> ein linearer Zusammenhang der Form <span class="math inline">\(Y = \beta_0 + \beta_1 \cdot X + \epsilon\)</span> zwischen den Variablen <span class="math inline">\(X\)</span> und <span class="math inline">\(Y\)</span>, und sind die Datenpunkte voneinander unabhängig sowie die <span class="math inline">\(\epsilon\)</span> folgen einer multivariaten Normalverteilung <span class="math inline">\(\epsilon \sim \mathcal{N}(0, \sigma^2 \mathbf{I}_n)\)</span>, dann wird dieses Modell als Gauss-Markov-Modell bezeichnet.</p>
</div>
<p><span class="math inline">\(Y\)</span> wird jetzt großgeschrieben, da es sich um eine Zufallsvariable handelt. Unter einer multivariaten Normalverteilung können wir uns eine Verallgemeinerung der uns bekannten Normalverteilung vorstellen. Beispielsweise hat eine zweidimensionale Normalverteilung die Form eines Zuckerhuts. Dieser Teil ist für unsere weitere Betrachtung aber zunächst nicht von Interesse. Unsere Formulierung des Regressionsmodells nach <a href="#eq-slm-inf-simple-reg" class="quarto-xref">Gleichung&nbsp;<span>4.7</span></a> führt nun dazu, dass wir das Regressionsmodell in zwei Teile unterscheiden können: einen deterministischen Teil <span class="math inline">\(\beta_0 + \beta_1 \cdot x\)</span> und einen stochastischen Teil <span class="math inline">\(\epsilon_i\)</span>. Da <span class="math inline">\(Y_i\)</span> durch die Addition der beiden Teile berechnet wird, führt dies dazu, dass <span class="math inline">\(Y_i\)</span> ebenfalls stochastisch ist und somit zu einer Zufallsvariable wird.</p>
<p>Schauen wir uns weiter an, wie sich <span class="math inline">\(Y_i\)</span> verhält, wenn wir <span class="math inline">\(X_i\)</span> als Konstante <span class="math inline">\(X\)</span> mit einem bestimmten Wert annehmen. Dann wird aus Formel <a href="#eq-slm-inf-simple-reg" class="quarto-xref">Gleichung&nbsp;<span>4.7</span></a> <span class="math inline">\(Y_i = \beta_0 + \beta_1 \cdot x + \epsilon_i\)</span>. Folglich bleibt der deterministische Teil immer gleich und wird zu einer Konstante. Da <span class="math inline">\(\epsilon_i\)</span> normalverteilt ist, ist <span class="math inline">\(Y_i\)</span> ebenfalls normalverteilt. Der Mittelwert der Normalverteilung von <span class="math inline">\(Y_i\)</span>, <span class="math inline">\(\mu_{Y_i}\)</span>, ist allerdings nicht gleich null, sondern die Normalverteilung von <span class="math inline">\(\epsilon_i\)</span> wird um die Konstante <span class="math inline">\(\beta_0 + \beta_1 \cdot x\)</span> verschoben (siehe <a href="#fig-slm-inf-epsilon-1" class="quarto-xref">Abbildung&nbsp;<span>4.13</span></a>). Das führt dazu, dass <span class="math inline">\(Y_i\)</span> der Verteilung <span class="math inline">\(\mathcal{N}(\beta_0 + \beta_1 x)\)</span> folgt.</p>
<div id="fig-slm-inf-epsilon-1" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-inf-epsilon-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-slm-inf-epsilon-1" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-slm-inf-epsilon-1-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-slm-inf-epsilon-1-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-inf-epsilon-1-1.png" class="img-fluid figure-img" data-ref-parent="fig-slm-inf-epsilon-1" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-slm-inf-epsilon-1-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Verteilung von <span class="math inline">\(\epsilon_i\)</span>
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-slm-inf-epsilon-1" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-slm-inf-epsilon-1-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-slm-inf-epsilon-1-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-inf-epsilon-1-2.png" class="img-fluid figure-img" data-ref-parent="fig-slm-inf-epsilon-1" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-slm-inf-epsilon-1-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Verteilung von <span class="math inline">\(Y_i\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-inf-epsilon-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.13: Relation der Lageparameter von <span class="math inline">\(e_i\)</span> und <span class="math inline">\(Y_i\)</span>
</figcaption>
</figure>
</div>
<p>Daraus folgt zusätzlich, dass für jedes gegebenes <span class="math inline">\(X\)</span> die <span class="math inline">\(Y\)</span>-Werte einer Normalverteilung folgen. Lediglich die Verschiebung des Mittelwert der jeweiligen <span class="math inline">\(Y\)</span>-Normalverteilung hängt von <span class="math inline">\(X\)</span> über die Formel <span class="math inline">\(\beta_0 + \beta_1 \cdot X\)</span> zusammen. Formal:</p>
<p><span class="math display">\[
Y|X \sim N(\beta_0+ \beta_1 X,\sigma^2)
\]</span></p>
<p>Die Schreibweise <span class="math inline">\(|X\)</span> wird übersetzt mit “für gegebenes <span class="math inline">\(X\)</span>” und sagt aus, dass die Verteilung von <span class="math inline">\(Y\)</span> von <span class="math inline">\(X\)</span> abhängt. Es handelt sich dabei um eine bedingte Wahrscheinlichkeit. Die Varianz der jeweiligen <span class="math inline">\(Y\)</span>-Werte ist dabei die zuvor angenommene Varianz der <span class="math inline">\(\epsilon_i\)</span>, also <span class="math inline">\(\sigma^2\)</span>. Eine wichtige Annahme, die noch einmal betont werden sollte: Wir gehen davon aus, dass die einzelnen Punkte unabhängig voneinander sind. Im Weitsprungbeispiel würde dies bedeuten, dass jeder Sprung von einem anderen Athleten kommen muss.</p>
<p>Wenn wir die Verteilungen von <span class="math inline">\(Y\)</span> graphisch für beispielsweise drei verschiedene <span class="math inline">\(X\)</span>-Werte darstellen, dann ergibt sich die folgende Abbildung (siehe <a href="#fig-slm-inf-epsilon-2" class="quarto-xref">Abbildung&nbsp;<span>4.14</span></a>). D.h., für jeden <span class="math inline">\(X\)</span>-Wert werden mehrere <span class="math inline">\(Y\)</span>-Werte beobachtet, die jeweils einer Normalverteilung folgen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-inf-epsilon-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-inf-epsilon-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pics/Stats_Figures.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-inf-epsilon-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.14: Verteilung der Daten für verschiedene <span class="math inline">\(x\)</span>-Werte
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-inf-epsilon-2" class="quarto-xref">Abbildung&nbsp;<span>4.14</span></a> ist klar zu sehen, wie für jeden der drei Punkte von <span class="math inline">\(X\)</span> die beobachteten <span class="math inline">\(Y\)</span>-Werte einer Normalverteilung folgen. Die Streuung der Verteilung ist an jedem der <span class="math inline">\(X\)</span>-Punkte gleich, nämlich <span class="math inline">\(=\sigma^2\)</span>. Dagegen ist der Mittelwert der Verteilung der <span class="math inline">\(Y_i\)</span>-Werte der Gleichung <span class="math inline">\(\beta_0 + \beta_1 X\)</span> folgend entlang der Regressionsgerade verschoben. Dies erklärt, warum die Verteilung von <span class="math inline">\(Y\)</span> vom <span class="math inline">\(X\)</span>-Wert abhängt. Die Verteilung von <span class="math inline">\(Y\)</span> ist im Gauss-Markov-Modell immer normalverteilt mit einer konstanten Varianz <span class="math inline">\(\sigma^2\)</span>. Der Mittelwert <span class="math inline">\(\mu\)</span> der Verteilung hängt jedoch vom <span class="math inline">\(X\)</span>-Wert ab und verändert sich entsprechend <span class="math inline">\(\beta_0 + \beta_1 X\)</span>.</p>
<p>Wenn wir uns an die Ausführungen zur statistischen Signifikanz erinnern, dann haben wir in diesem Zusammenhang von einem datengenerierenden Prozess (<a href="stats_significance.html#def-dgp" class="quarto-xref">Definition&nbsp;<span>2.1</span></a>) (DGP) gesprochen. In unserem jetzigen Modell können wir dementsprechend zwei Komponenten als Teile des DGP identifizieren. Entsprechend Formel <span class="math inline">\(\eqref{eq-slm-inf-simple-reg}\)</span> besteht der DGP aus dem deterministischen Teil <span class="math inline">\(\beta_0 + \beta_1 X\)</span> und dem stochastischen Teil <span class="math inline">\(\epsilon_i \sim \mathcal{N}(0,\sigma^2)\)</span>. Diese Einsicht können wir verwenden, um die Eigenschaften dieses Modells für mögliche Aussagen hinsichtlich statistischer Signifikanz zu untersuchen.</p>
<p>Wir fokussieren uns jetzt auf ein vereinfachtes Modell, bei dem wir <span class="math inline">\(\beta_0 = 0\)</span> setzen. D.h., der <span class="math inline">\(y\)</span>-Achsenabschnitt der Regressionsgeraden ist <span class="math inline">\(=0\)</span>, und wir betrachten erst einmal nur die Eigenschaften von <span class="math inline">\(\beta_1\)</span>. Gehen wir nun davon aus, dass zwischen <span class="math inline">\(X\)</span> und <span class="math inline">\(Y\)</span> der Zusammenhang <span class="math inline">\(\beta_1 = 1\)</span> besteht. D.h., der Steigungskoeffizient hat den Wert <span class="math inline">\(=1\)</span>, was dazu führt, dass, wenn <span class="math inline">\(X\)</span> um eine Einheit vergrößert wird, sich <span class="math inline">\(Y\)</span> ebenfalls um eine Einheit vergrößert. Die Gerade würde somit genau die 1. Winkelhalbierende beschreiben. Formal erhalten wir:</p>
<p><span class="math display">\[\begin{equation}
Y = 0 + 1 \cdot X + \epsilon, \quad \epsilon \sim \mathcal{N}(0,\sigma^2)
\label{eq-slm-inf-sim-mod-1}
\end{equation}\]</span></p>
<p>Jetzt müssen wir allerdings noch einen Wert für <span class="math inline">\(\sigma^2\)</span> bzw. <span class="math inline">\(\sigma\)</span> festlegen. Sei dieser der Einfachheit halber <span class="math inline">\(\sigma = \frac{1}{2}\)</span>. Jetzt können wir <code>R</code> benutzen, um <em>Experimente</em>, also Beobachtungen, anhand dieses DGP zu simulieren. Der Überschaubarkeit halber besteht unser Datensatz nur aus <span class="math inline">\(N = 12\)</span> Punkten, die sich auf drei <span class="math inline">\(X\)</span>-Werte verteilen, z.B. <span class="math inline">\(X \in \{-1, 0, 1\}\)</span>. Somit generieren wir für jeden <span class="math inline">\(X\)</span>-Wert vier unterschiedliche <span class="math inline">\(Y\)</span>-Werte. In <code>R</code>-Code übertragen könnten wir das folgende Programm erstellen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">12</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>beta_0 <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>beta_1 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>dat_sim_1 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_i =</span> <span class="fu">rep</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">each=</span><span class="dv">4</span>),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">y_i =</span> beta_0 <span class="sc">+</span> beta_1 <span class="sc">*</span> x_i <span class="sc">+</span> <span class="fu">rnorm</span>(N, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> sigma)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Wenn wir uns die generierten Daten anschauen, dann sehen wir wenig überraschend <span class="math inline">\(12\)</span> verschiedene Werte für <span class="math inline">\(y_i\)</span> und jeweils <span class="math inline">\(3 \times 4\)</span> verschiedene Werte für <span class="math inline">\(x_i\)</span> (siehe <a href="#tbl-slm-inf-sim-1" class="quarto-xref">Tabelle&nbsp;<span>4.6</span></a>).</p>
<div class="cell">
<div id="tbl-slm-inf-sim-1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-slm-inf-sim-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.6: Eine Simulation des Modells <span class="quarto-unresolved-ref">?eq-slm-inf-sim-mod-1</span>
</figcaption>
<div aria-describedby="tbl-slm-inf-sim-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">i</th>
<th style="text-align: right;">x_i</th>
<th style="text-align: right;">y_i</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">-1.22</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">-1.04</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">-1.20</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">-0.73</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.34</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.82</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-0.09</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-0.33</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.89</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.32</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.67</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.65</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Graphisch dargestellt erhalten wir (<a href="#fig-slm-inf-sim-1" class="quarto-xref">Abbildung&nbsp;<span>4.15</span></a>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat_sim_1, <span class="fu">aes</span>(x_i, y_i)) <span class="sc">+</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-slm-inf-sim-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-inf-sim-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-inf-sim-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-inf-sim-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.15: Streudiagramm der Daten aus <a href="#tbl-slm-inf-sim-1" class="quarto-xref">Tabelle&nbsp;<span>4.6</span></a>
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ebenfalls wenig überraschend, die Punkte sind auf den <span class="math inline">\(x\)</span>-Werten <span class="math inline">\(-1, 0\)</span> und <span class="math inline">\(1\)</span> zentriert und liegen nicht alle aufeinander, da sie einer Zufallsstichprobe aus <span class="math inline">\(\mathcal{N}(0, \frac{1}{4})\)</span> entspringen.</p>
<p>Für die Daten können die Normalengleichungen angewendet um Werte für <span class="math inline">\(\hat{\beta}_0\)</span> und <span class="math inline">\(\hat{\beta}_1\)</span> zu erhalten. In <code>R</code> liefert die Funktion <code>lm()</code> die entsprechenden Werte.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mod_sim_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y_i <span class="sc">~</span> x_i, dat_sim_1)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mod_sim_1)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         x_i 
-0.07669501  0.83955303 </code></pre>
</div>
</div>
<p>Es ist zu beobachten, dass die berechneten Werte für <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> in der Nähe der <em>wahren</em> Werte liegen (siehe Formel <span class="math inline">\(\eqref{eq-slm-inf-sim-mod-1}\)</span>). Die Werte entsprechen auf Grund der Stichprobenvariabilität nicht exakt den <em>wahren</em> Werten, da in der Simulation die Funktion <code>rnorm()</code> verwendet wurde. Nun kann die Frage gestellt werden: Was passiert, wenn die Simulation ein weiteres Mal durchgefüht wird?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dat_sim_2 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_i =</span> <span class="fu">rep</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">each=</span><span class="dv">4</span>),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y_i =</span> beta_0 <span class="sc">+</span> beta_1 <span class="sc">*</span> x_i <span class="sc">+</span> <span class="fu">rnorm</span>(N, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> sigma)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>mod_sim_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y_i <span class="sc">~</span> x_i, dat_sim_2)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mod_sim_2)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         x_i 
 -0.1950909   0.8628953 </code></pre>
</div>
</div>
<p>Es wird wenig überraschend ein neuer Satz von <span class="math inline">\(\hat{\beta_0}\)</span> und <span class="math inline">\(\hat{\beta_1}\)</span> erhalten. Jedes Mal wenn <code>rnom()</code> aufgerufen wird, wird eine neue Ziehung aus der Normalverteilung generiert. Somit werden neue Werte für <span class="math inline">\(y_i\)</span> erzeugt und dementsprechend andere Werte für <span class="math inline">\(\hat{\beta}_0\)</span> und <span class="math inline">\(\hat{\beta}_1\)</span>. Stichword: <strong>Stichprobenvariabilität</strong>. Um eine tatsächliche Verteilung zu erhalten, Wird die Simulation nun beispielsweise <span class="math inline">\(1000\times\)</span> durchgeführt.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>N_sim <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>beta_1_s <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N_sim)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>x_i <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">each=</span><span class="dv">4</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N_sim) {</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  daten_temporaer <span class="ot">&lt;-</span> <span class="fu">tibble</span>(x_i,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">y_i =</span> beta_0 <span class="sc">+</span> beta_1 <span class="sc">*</span> x_i <span class="sc">+</span> <span class="fu">rnorm</span>(N, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> sigma))</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  model_temporaer <span class="ot">&lt;-</span> <span class="fu">lm</span>(y_i <span class="sc">~</span> x_i, daten_temporaer)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  beta_1_s[i] <span class="ot">&lt;-</span> <span class="fu">coef</span>(model_temporaer)[<span class="dv">2</span>]</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Es wird nun ein Vektor <code>beta_1_s</code> mit <span class="math inline">\(1000\)</span> beobachteten <span class="math inline">\(\hat{\beta}_1\)</span> berechnet. Mit diesen Werten kann nun ein Histogramm der <span class="math inline">\(\hat{\beta}_1\)</span>s erstellt werden, um die Verteilung zu betrachten (<a href="#fig-slm-inf-hist-sim-1" class="quarto-xref">Abbildung&nbsp;<span>4.16</span></a>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(beta_1_s, <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(beta)[<span class="dv">1</span>]), <span class="at">main=</span><span class="st">''</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> beta_1, <span class="at">col=</span><span class="st">'red'</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-slm-inf-hist-sim-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-inf-hist-sim-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-inf-hist-sim-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-inf-hist-sim-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.16: Histogram der auf den simulierten Daten berechneten <span class="math inline">\(\hat{\beta}_1\)</span>. Wahrer Wert von <span class="math inline">\(\beta_1\)</span> rot eingezeichnet.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-inf-hist-sim-1" class="quarto-xref">Abbildung&nbsp;<span>4.16</span></a> begegnet uns zunächst wieder unsere altbekannte Glockenkurve. Was uns positiv stimmen sollte, ist, dass der Mittelwert der Verteilung im Bereich des wahren Werts von <span class="math inline">\(\beta_1\)</span> (rote Linie) liegt und Werte mit größer werdender Abweichung vom wahren Wert in ihrer Häufigkeit abnehmen. Die Häufigkeit ist jedoch nicht null, sondern lediglich geringer. Werte in der Nähe von <span class="math inline">\(\beta_1\)</span> weisen dagegen eine größere Häufigkeit auf. Dies zeigt, dass wir in der Lage sind, mit unserem Regressionsmodell im Mittel tatsächlich den <em>wahren</em> Wert <span class="math inline">\(\beta_1\)</span> abzuschätzen. Allerdings, wie immer: Bei einer einzelnen Durchführung des Experiments können wir alles von perfekt spot-on bis komplett danebenliegen und würden es nicht wissen. Die Standardabweichung der <span class="math inline">\(\hat{\beta}_1\)</span> beschreibt dabei wieder den Standardfehler der Stichprobenverteilung.</p>
<p>Wir können jetzt aber auch wieder, ganz parallel zu unseren Herleitungen in der kleinen Welt, einen Entscheidungsprozess spezifizieren. Wenn <a href="#fig-slm-inf-hist-sim-1" class="quarto-xref">Abbildung&nbsp;<span>4.16</span></a> den DGP beschreibt und dies die Verteilung der zu erwartenden <span class="math inline">\(\hat{\beta}_1\)</span> unter dem Modell ist, dann würden wir bei der Durchführung eines neuen Experiments sagen: Wenn unser beobachteter Wert in den Rändern der Verteilung von <a href="#fig-slm-inf-hist-sim-1" class="quarto-xref">Abbildung&nbsp;<span>4.16</span></a> liegt, gehen wir eher nicht davon aus, dass unser neues Experiment dem gleichen DGP zugrunde liegt. D.h., wir definieren uns Grenzen (kritische Werte) am oberen und unteren Rand der Verteilung. Wenn ein beobachteter Wert entweder unterhalb der unteren Grenze oder oberhalb der oberen Grenze liegt, interpretieren wir dies im Sinne von: <em>Wir sind jetzt aber sehr überrascht, diesen Wert zu sehen, wenn er dem gleichen datengenerierenden Prozess entstammen soll. Daher glauben wir nicht, dass dieses Experiment den gleichen DGP besitzt.</em></p>
<p>Um diese Entscheidung treffen zu können, müssen wir also Grenzen definieren. Dazu können wir zunächst einfach die Quantile der Verteilung nehmen und z.B. unten <span class="math inline">\(2.5\%\)</span> und oben <span class="math inline">\(2.5\%\)</span> abschneiden. So kommen wir dann insgesamt auf <span class="math inline">\(5\%\)</span>, um auf die übliche Irrtumswahrscheinlichkeit von <span class="math inline">\(\alpha = 0.05\)</span> zu kommen. Dazu benutzen wir in <code>R</code> die <code>quantile()</code>-Funktion<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>crit_vals <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">quantile</span>(beta_1_s, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>)), <span class="dv">2</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>crit_vals</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> 2.5% 97.5% 
 0.65  1.35 </code></pre>
</div>
</div>
<p>Mittels dieser Werte können wir zwei disjunkte Wertemengen definieren: einmal die Werte innerhalb von <span class="math inline">\(\hat{\beta}_1 \in [0.65,1.35]\)</span>, bei denen wir nicht überrascht sind und die unter der Annahme <span class="math inline">\(\beta_1 = 1\)</span> erwartbar sind, und die Werte <span class="math inline">\(\hat{\beta}_1 \notin [0.65,1.35]\)</span>, diejenigen Werte, die uns unter der Annahme überraschen würden. Ins Histogramm übertragen (siehe <a href="#fig-slm-inf-hist-sim-2" class="quarto-xref">Abbildung&nbsp;<span>4.17</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-inf-hist-sim-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-inf-hist-sim-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-inf-hist-sim-2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-inf-hist-sim-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.17: Histogram der auf den simulierten Daten berechneten <span class="math inline">\(\hat{\beta}_1\)</span>. Wahrer Wert von <span class="math inline">\(\beta_1\)</span> rot eingezeichnet und kritische Werte grün.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Führen wir nun ein Experiment einmal durch. Wir beobachten einen Wert für <span class="math inline">\(\hat{\beta}_1\)</span> von <span class="math inline">\(1.46\)</span>. Dieser Wert liegt außerhalb unseres definierten Intervalls <span class="math inline">\([0.65, 1.35]\)</span>, daher sehen wir diesen Wert als derart unwahrscheinlich unter dem angenommenen DGP, das wir sagen: <em>Wir glauben nicht, dass diesem Experiment der angenommene DGP zugrunde liegt</em>. Graphisch führt dies zu <a href="#fig-slm-inf-hist-sim-3" class="quarto-xref">Abbildung&nbsp;<span>4.18</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-inf-hist-sim-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-inf-hist-sim-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-inf-hist-sim-3-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-inf-hist-sim-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.18: Histogram der auf den simulierten Daten berechneten <span class="math inline">\(\hat{\beta}_1\)</span>. Wahrer Wert von <span class="math inline">\(\beta_1\)</span> rot eingezeichnet und kritische Werte grün und der beobachtete Wert als roter Punkt.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Daher würden wir diesen Wert als statisisch signifikant bezeichnen und würden unsere Annahme ablehnen.</p>
</section>
<section id="teststatistik-für-beta_1" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="teststatistik-für-beta_1"><span class="header-section-number">4.8</span> Teststatistik für <span class="math inline">\(\beta_1\)</span></h2>
<p>Jetzt sind wir aber etwas hin und her gesprungen zwischen Simulation, Experiment, Annahmen und Schlussfolgerungen. Normalerweise kennen wir die Stichprobenverteilung vor dem Experiment nicht, sondern wir sind an dem Wert <span class="math inline">\(\beta_1\)</span> interessiert. Wenn wir den Wert schon wüssten, müssten wir ja gar kein Experiment mehr durchführen. D.h., wir haben eigentlich noch keine klaren Vorkenntnisse. Mit welcher Annahme gehen wir dann in das Experiment hinein? Nun, wie schon beim kleinen Welt-Beispiel, starten wir mit der Annahme, dass zwischen den beiden Variablen <span class="math inline">\(X\)</span> und <span class="math inline">\(Y\)</span> kein Zusammenhang besteht. Übertragen auf den Modellparameter <span class="math inline">\(\beta_1\)</span> bedeutet dies, dass kein linearer Zusammenhang zwischen den beiden Variablen existiert. D.h., Informationen über <span class="math inline">\(X\)</span> geben uns keine Informationen über <span class="math inline">\(Y\)</span>. Formal:</p>
<p><span class="math display">\[\begin{align*}
H_0: \beta_1 &amp;= 0 \\
H_1: \beta_1 &amp;\neq 0
\end{align*}\]</span></p>
<p>Um die Stichprobenverteilung unter der <span class="math inline">\(H_0\)</span> formal herleiten zu können, sind der Erwartungswert von <span class="math inline">\(\hat{\beta}_1\)</span> und dessen Standardfehler notwendig. Es lässt sich zeigen, dass die folgenden Zusammenhänge unter den gesetzten Annahmen bestehen:</p>
<p><span class="math display">\[\begin{equation}
E[\hat{\beta}_1] = \beta_1
\end{equation}\]</span></p>
<p>Der Schätzer <span class="math inline">\(\hat{\beta}_1\)</span> aus den Normalengleichungen von <span class="math inline">\(\beta_1\)</span> ist erwartungstreu (unbiased). Der Standardfehler des Schätzers lässt sich wie folgt bestimmen:</p>
<p><span class="math display">\[\begin{equation}
\sigma_{\beta_1} = \sqrt{\frac{\sigma^2}{\sum{(X_i - \bar{X})^2}}}
\label{eq-slm-beta1-se}
\end{equation}\]</span></p>
<p>Hier taucht jetzt zum ersten Mal der Parameter <span class="math inline">\(\sigma^2\)</span> formal auf. Wo kommt diese Varianz her? Sie gehört zu unserer Annahme der Verteilung der <span class="math inline">\(\epsilon_i \sim \mathcal{N}(0,\sigma^2)\)</span>. Bisher haben wir aber noch keine Möglichkeit kennengelernt, diese abzuschätzen.</p>
<p>Nach etwas motiviertem Starren auf die verschiedenen Formeln könnte es heuristisch plausibel sein, dass die Varianz, also die Streuung der <span class="math inline">\(\epsilon_i\)</span>, mit der Streuung unserer Werte um die Regressionsgerade zusammenhängt. Formal hatten wir diese als Residuen bezeichnet und mit <span class="math inline">\(e_i = \hat{y}_i - y_i\)</span> bezeichnet. Zuvor hatten wir diese Abweichungen als Fehler bezeichnet, aber unter den jetzt eingeführten Annahmen handelt es sich nicht wirklich um Fehler. Stattdessen sind die Abweichungen eine Folge davon, dass <span class="math inline">\(Y_i\)</span> für jeden Wert von <span class="math inline">\(X_i\)</span> nicht nur einen einzigen Wert hat, sondern einer Verteilung folgt: <span class="math inline">\(Y_i|X_i \sim \mathcal{N}(\beta_0 + \beta_1 X, \sigma^2)\)</span>, deren Form durch die <span class="math inline">\(\epsilon_i\)</span> bestimmt wird.</p>
<p>Die <span class="math inline">\(e_i\)</span> sind tatsächlich die Schätzer für die <em>wahren</em> <span class="math inline">\(\epsilon_i\)</span>, also <span class="math inline">\(e_i = \hat{\epsilon}_i = \hat{y}_i - y_i\)</span>. Es lässt sich nun zeigen, dass mittels dieser <span class="math inline">\(e_i\)</span> ein erwartungstreuer Schätzer für <span class="math inline">\(\sigma^2\)</span> erzeugt werden kann, nämlich die mittleren quadrierten Abweichungen (MSE = mean squared error):</p>
<p><span class="math display">\[\begin{equation}
\hat{\sigma}^2 = \frac{\sum_{i=1}^N e_i^2}{N-2} = \frac{\text{SSE}}{N-2} = \text{MSE}
\label{eq-slm-sigma}
\end{equation}\]</span></p>
<p>Da das später immer wieder auftauchen wird, hier auch noch einmal in die zwei Komponenten zerlegt: Der Zähler wird als Summe der quadrierten Abweichungen (SSE = sum of squared errors) bezeichnet und durch den Term <span class="math inline">\(N-2\)</span>, der als Freiheitsgrade bezeichnet wird, geteilt. Damit die Formel und deren Bezeichnung <em>mittlere</em> Abweichung zusammenpassen, wäre es schöner, wenn die Summe durch die Anzahl <span class="math inline">\(N\)</span> der Terme geteilt würde. Allerdings verhält sich das in diesem Fall ähnlich wie bei der Varianz einer Stichprobe, wo die Summe ebenfalls durch <span class="math inline">\(N-1\)</span> geteilt wird (zur Erinnerung <span class="math inline">\(s^2 = \frac{\sum_{i=1}^N (x_i - \bar{x})^2}{N-1}\)</span>). Für die MSE wird dementsprechend nicht durch <span class="math inline">\(N-1\)</span>, sondern durch <span class="math inline">\(N-2\)</span> geteilt.</p>
<p>Für unser Problem der Stichprobenverteilung ist jetzt aber wichtiger, dass wir mittels Formel <span class="math inline">\(\eqref{eq-slm-sigma}\)</span> den Standardfehler von <span class="math inline">\(\hat{\beta}_1\)</span> bestimmen können, indem wir für <span class="math inline">\(\sigma^2\)</span> das mittels der Daten ermittelte <span class="math inline">\(\hat{\sigma}^2\)</span> einsetzen:</p>
<p><span class="math display">\[\begin{equation}
\hat{\sigma}_{\beta_1} = \sqrt{\frac{\hat{\sigma}^2}{\sum{(X_i - \bar{X})^2}}}
\label{eq-slm-hatbeta1-se}
\end{equation}\]</span></p>
<p>Dies erlaubt uns jetzt, nach unserem bereits bekannten Muster, eine Teststatistik für die <span class="math inline">\(H_0\)</span> herzuleiten:</p>
<p><span class="math display">\[
t = \frac{\hat{\beta}_1 - \beta_{1,H_0}}{\hat{\sigma}_{\beta_1}}
\]</span></p>
<p>Wir teilen die Abweichung des beobachteten Steigungskoeffizienten <span class="math inline">\(\hat{\beta}_1\)</span> von einem angenommenen Steigungskoeffizienten <span class="math inline">\(\beta_{1,H_0}\)</span> durch den Standardfehler von <span class="math inline">\(\hat{\beta}_1\)</span>. Unter der <span class="math inline">\(H_0\)</span> mit der Annahme <span class="math inline">\(\beta_1 = 0\)</span> wird daraus die folgende Teststatistik:</p>
<p><span class="math display">\[\begin{equation}
t = \frac{\hat{\beta}_1}{\hat{\sigma}_{\beta_1}}
\label{eq-slm-beta1-statistic}
\end{equation}\]</span></p>
<p>Die Referenzverteilung dieser Teststatistik folgt unter der <span class="math inline">\(H_0: \beta_1 = 0\)</span> einer <span class="math inline">\(t\)</span>-Verteilung mit <span class="math inline">\(N-2\)</span> Freiheitsgraden. Formal:</p>
<p><span class="math display">\[\begin{equation*}
t = \frac{\hat{\beta}_1 - \beta_{1,H_0}}{\hat{\sigma}_{\beta_1}} \sim t_{df = N-2}
\end{equation*}\]</span></p>
<p>Da diese Formel wieder etwas aus der Luft gegriffen erscheint, folgt hier noch einmal eine Simulation unter der <span class="math inline">\(H_0: \beta_1 = 0\)</span>. Wir nehmen <span class="math inline">\(n = 45\)</span> Datenpunkte und generieren zunächst <span class="math inline">\(x\)</span>-Werte, die wir immer wieder verwenden. Anschließend ziehen wir für die <span class="math inline">\(y\)</span>-Werte normalverteilte Werte aus der Normalverteilung <span class="math inline">\(\mathcal{N}(\mu = 0, \sigma^2 = 1)\)</span>. Konzeptionell bedeutet dies, dass kein Zusammenhang zwischen den <span class="math inline">\(x\)</span>- und den <span class="math inline">\(y\)</span>-Werten besteht, also die <span class="math inline">\(H_0: \beta_1 = 0\)</span> tatsächlich <em>wahr</em> ist. Der DGP ist also einfach eine Zufallszahlenziehung von <span class="math inline">\(y\)</span>-Werten ohne jeglichen Zusammenhang mit den <span class="math inline">\(x\)</span>-Werten.</p>
<p>Wir können diesen DGP jetzt für eine Simulation benutzen und <span class="math inline">\(1000\)</span>-mal durchlaufen lassen. Für jeden Durchgang berechnen wir ein Regressionsmodell zwischen den <span class="math inline">\(x\)</span>- und <span class="math inline">\(y\)</span>-Werten und extrahieren den Steigungskoeffizienten <span class="math inline">\(\hat{\beta}_1\)</span> mittels <code>coef()</code> und die Residualvarianz <span class="math inline">\(\hat{\sigma}^2\)</span> mittels <code>sigma()</code>. Wir erhalten mittels <code>replicate()</code> eine Matrix mit <span class="math inline">\(1000\)</span> <span class="math inline">\(\hat{\beta}_1\)</span> (1. Zeile) und <span class="math inline">\(1000\)</span> <span class="math inline">\(\hat{\sigma}\)</span>-Werten (2. Zeile). (Tipp: Kopiert den Code-Chunk, um das Programm auf eurem Rechner auszuführen).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">45</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>n_sim <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(N, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>experiment <span class="ot">&lt;-</span> <span class="cf">function</span>() {</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> sigma)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y<span class="sc">~</span>x)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  b <span class="ot">&lt;-</span> <span class="fu">coef</span>(mod)[<span class="dv">2</span>]</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">beta_1 =</span> <span class="fu">coef</span>(mod)[<span class="dv">2</span>],</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">sigma =</span> <span class="fu">sigma</span>(mod))</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>mod_ergebnisse <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">replicate</span>(n_sim, <span class="fu">experiment</span>()))</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Mit diesen Information können wir nun den Standarfehler <span class="math inline">\(\sigma[\hat{\beta}_1]\)</span> und die <span class="math inline">\(t\)</span>-Werte berechnen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>betas <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">beta_1 =</span> mod_ergebnisse[,<span class="dv">1</span>],</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">sigma  =</span> mod_ergebnisse[,<span class="dv">2</span>]) <span class="sc">|&gt;</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">s_e_beta_1 =</span> <span class="fu">sqrt</span>(sigma<span class="sc">**</span><span class="dv">2</span><span class="sc">/</span><span class="fu">sum</span>( (x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">**</span><span class="dv">2</span>)),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">t =</span> beta_1 <span class="sc">/</span> s_e_beta_1)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Nun, können wir ein Histogramm der berechneten <span class="math inline">\(t\)</span>-Werte erstellen und auch gleich noch dazu die theoretische <span class="math inline">\(t\)</span>-Verteilung einzeichnen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>t_theoretical <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">t =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="at">length.out =</span> <span class="dv">150</span>),</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> <span class="fu">dt</span>(t, N <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(betas, <span class="fu">aes</span>(t)) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">bins =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> t_theoretical, <span class="fu">aes</span>(t, p), <span class="at">color =</span> <span class="st">'red'</span>) <span class="sc">+</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"t"</span>, <span class="at">y =</span> <span class="st">'Relative Häufigkeit'</span>) </span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-slm-inf-beta1-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-inf-beta1-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-inf-beta1-dist-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-inf-beta1-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.19: Verteilung von t bei 1000 Simulationen unter der Annahme der <span class="math inline">\(H_0\)</span> und die theoretische Verteilung von t (rot).
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-inf-beta1-dist" class="quarto-xref">Abbildung&nbsp;<span>4.19</span></a> können wir sehen, dass die theoretische <span class="math inline">\(t\)</span>-Verteilung mit <span class="math inline">\(df = N - 2\)</span> Freiheitsgraden (in rot) die beobachtete Verteilung der <span class="math inline">\(t\)</span>-Werte sehr gut abschätzt. D.h. wir können die theoretische Verteilung benutzen um die statistische Signifikanz der berechneten <span class="math inline">\(t\)</span>-Werte unter der <span class="math inline">\(H_0\)</span> abzuschätzen. Anderes herum, wenn die <span class="math inline">\(H_0: \beta_1 = 0\)</span> zutrifft, dann sollte der in unserem (einmaligen, tatsächlichen) beobachtete <span class="math inline">\(t\)</span>-Wert einer <span class="math inline">\(t\)</span>-Verteilung mit <span class="math inline">\(df = N - 2\)</span> Freiheitsgraden folgen. Wenn wir nun einen Wert beobachten der unwahrscheinlich unter der Annahme der <span class="math inline">\(H_0\)</span> ist im Sinne der Irrtumswahrscheinlichkeit <span class="math inline">\(\alpha\)</span>, dann sehen wir das als Evidenz gegen die Korrektheit der <span class="math inline">\(H_0\)</span>-Annahme.</p>
<p>Nochmal, weil das eben so nebenbei kam. In <code>R</code> kann der Wert <span class="math inline">\(MSE = \hat{\sigma}\)</span> über die Funktion <code>sigma()</code> aus dem gefitteten <code>lm()</code>-Modell extrahiert werden, bzw. steht auch unten in der <code>summary()</code>-Ausgabe unter <code>Residual standard error</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sigma</span>(mod)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2369055</code></pre>
</div>
</div>
<p>Weil wir schon dabei sind, schauen wir uns gerade auch die Stichprobenverteilung von <span class="math inline">\(\hat{\sigma}^2\)</span> anhand unserer Simulation an. Es ist wieder zu beobachten, das im Mittel der korrekte, im Modell definierte, Wert von <span class="math inline">\(\sigma = 1\)</span> beobachtet wird (siehe <a href="#fig-slm-inf-sigma-dist" class="quarto-xref">Abbildung&nbsp;<span>4.20</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-inf-sigma-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slm-inf-sigma-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="slm_basics_files/figure-html/fig-slm-inf-sigma-dist-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slm-inf-sigma-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.20: Verteilung von <span class="math inline">\(\hat{\sigma}\)</span> in der Simulation und der wahre Wert in rot eingezeichnet
</figcaption>
</figure>
</div>
</div>
</div>
<p>Aber wie immer, leider steht uns bei einem realen Experiment diese Information nicht zur Verfügung, und wir haben nur einen einzelnen Wert, der alles von komplett daneben bis ziemlich perfekt sein kann.</p>
<p>Schauen wir uns noch einmal die Ausgabe zu unserem Weitsprungmodell mittels <code>summary()</code> an. Wie schon erwähnt, wird unter <code>Residual Standard Error</code> der Wert <span class="math inline">\(\hat{\sigma}\)</span> angegeben. Dieser Wert wird auch als mittlerer Schätzfehler bezeichnet und kann als Maß verwendet werden, um abzuschätzen, welche Abweichung das Modell im Mittel hat. Die Einheit entspricht wieder der Einheit der abhängigen Variable. Dies erlaubt uns abzuschätzen, mit welcher Präzision das Modell die Daten fittet.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = jump_m ~ v_ms, data = jump)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.44314 -0.22564  0.02678  0.19638  0.42148 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.13854    0.23261  -0.596    0.555    
v_ms         0.76110    0.02479  30.702   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2369 on 43 degrees of freedom
Multiple R-squared:  0.9564,    Adjusted R-squared:  0.9554 
F-statistic: 942.6 on 1 and 43 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In unserem Fall beobachten wir <span class="math inline">\(0.24m\)</span>. Diesen Wert muss unsere Trainerin im Sinne der Weitsprungleistung und deren Varianz interpretieren und eine Abschätzung treffen können.</p>
</section>
<section id="teststatistik-für-beta_0" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="teststatistik-für-beta_0"><span class="header-section-number">4.9</span> Teststatistik für <span class="math inline">\(\beta_0\)</span></h2>
<p>Nach der Herleitung der Teststatistik für <span class="math inline">\(\beta_1\)</span> können wir nun auch weitere Teile der Ausgabe von <code>summary()</code> interpretieren. In der Tabelle stehen die Standardfehler für <span class="math inline">\(\hat{\beta}_1\)</span> und <span class="math inline">\(\hat{\beta}_0\)</span>. Für <span class="math inline">\(\beta_0\)</span> wird genau die gleiche Vorgehensweise wie bei <span class="math inline">\(\beta_1\)</span> angewendet. Die Nullhypothese <span class="math inline">\(H_0\)</span> ist hier ebenfalls, dass der Parameter standardmäßig als Null angesetzt wird, also <span class="math inline">\(H_0: \beta_0 = 0\)</span>. Der Standardfehler <span class="math inline">\(\sigma[\beta_0]\)</span> von <span class="math inline">\(\beta_0\)</span> errechnet sich nach:</p>
<p><span class="math display">\[\begin{equation*}
\sigma[\beta_0] = \sqrt{\sigma^2\left(\frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=1}^n (x_i - \bar{x})^2}\right)}
\end{equation*}\]</span></p>
<p>Ein Schätzer wird erhalten, wenn für <span class="math inline">\(\sigma^2\)</span> unser Schätzer <span class="math inline">\(MSE = \hat{\sigma}^2\)</span> aus Formel <span class="math inline">\(\eqref{eq-slm-sigma}\)</span> eingesetzt wird:</p>
<p><span class="math display">\[\begin{equation}
\hat{\sigma}[\beta_0] = \sqrt{MSE\left(\frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=1}^n (x_i - \bar{x})^2}\right)}
\label{eq-slm-inf-beta0-se}
\end{equation}\]</span></p>
<p>Dies führt zu den beiden statistischen Hypothesen für <span class="math inline">\(\beta_0\)</span>, um einen formalen Test zu erstellen:</p>
<p><span class="math display">\[\begin{align*}
H_0: \beta_0 &amp;= 0 \\
H_1: \beta_0 &amp;\neq 0
\end{align*}\]</span></p>
<p>Dementsprechend überprüft die Hypothesentestung, ob der <span class="math inline">\(y\)</span>-Achsenabschnitt gleich Null ist. Hier sollte berücksichtigt werden, dass diese Hypothese in den seltensten Fällen tatsächlich von Interesse ist. Sie besagt lediglich, dass der <span class="math inline">\(y\)</span>-Achsenabschnitt durch den Nullpunkt geht, oder dass, wenn <span class="math inline">\(\beta_1 = 0\)</span> gilt, der Mittelwert von <span class="math inline">\(y\)</span> gleich Null ist, was ebenfalls selten von Interesse ist.</p>
<p>Mit den beiden Teststatistiken für <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> können wir nun auch die Spalten 3 und 4 in der Ausgabe von <code>summary()</code> unter <code>Coefficients</code> interpretieren. Es handelt sich hierbei um den jeweiligen <span class="math inline">\(t\)</span>-Wert der Koeffizienten <span class="math inline">\(\hat{\beta}_0\)</span> und <span class="math inline">\(\hat{\beta}_1\)</span>. Entsprechend ist der p-Wert unter der jeweiligen <span class="math inline">\(H_0\)</span> angegeben. Standardmäßig sind die Hypothesen ungerichtet.</p>
</section>
<section id="konfidenzintervalle-für-die-koeffizienten" class="level2" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="konfidenzintervalle-für-die-koeffizienten"><span class="header-section-number">4.10</span> Konfidenzintervalle für die Koeffizienten</h2>
<p>Wie wir im oberen Abschnitt gesehen haben, sind unsere Schätzer für die Koeffizienten <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> mit Unsicherheiten behaftet, die sich in Form der Standardfehler <span class="math inline">\(\sigma[\beta_0]\)</span> und <span class="math inline">\(\sigma[\beta_1]\)</span> ausdrücken. Die Standardfehler können, wie bereits im kleinen Welt-Beispiel gezeigt, dazu verwendet werden, Konfidenzintervalle für die beiden Koeffizienten <span class="math inline">\(\hat{\beta}_0\)</span> und <span class="math inline">\(\hat{\beta}_1\)</span> zu bestimmen:</p>
<p><span class="math display">\[\begin{equation}
\hat{\beta}_j \pm q_{t_{\alpha/2,df=N-2}} \times \hat{\sigma}_{\beta_j}
\label{eq-slm-inf-conf-0}
\end{equation}\]</span></p>
<p>Wie in Formel <span class="math inline">\(\eqref{eq-slm-inf-conf-0}\)</span> zu sehen, berechnet sich das Konfidenzintervall nach dem üblichen Muster: Schätzer <span class="math inline">\(\pm\)</span> Quantile <span class="math inline">\(\times\)</span> Standardfehler.</p>
<p>Im vorliegenden Fall werden die Quantile aus der <span class="math inline">\(t\)</span>-Verteilung mit <span class="math inline">\(N-2\)</span> Freiheitsgraden bestimmt. Wie vorher bereits betont, erlaubt das Konfidenzintervall keine Aussage über die Wahrscheinlichkeit, mit der der <em>wahre</em> Koeffizient im Konfidenzintervall liegt. Es gibt jedoch an, welche <span class="math inline">\(H_0\)</span>-Hypothesen mit den beobachteten Daten kompatibel sind. Alle Werte, die innerhalb des Konfidenzintervalls liegen, würden, wenn sie als <span class="math inline">\(H_0\)</span> angesetzt gewesen wären, zu keinem statistisch signifikanten Ergebnis führen. Die Ergebnisdokumentation muss das Konfidenzintervall angeben, und spätestens in der Diskussion sollten die obere und die untere Schranke diskutiert werden. Dies geschieht immer im Kontext der konkreten Studie.</p>
<p>In <code>R</code> kann das Konfidenzintervall direkt mit der Funktion <code>confint()</code> berechnet und ausgegeben werden:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept) -0.6076488 0.3305767
v_ms         0.7111082 0.8110957</code></pre>
</div>
</div>
<p>Wie schon vorher im Rahmen der Besprechung der Normalverteilung erwähnt, ist eine gute Daumenregel <span class="math inline">\(2 \times s_e\)</span>, um das Konfidenzintervall schnell abzuschätzen.</p>
<p>Wie die Koeffizienten haben die Konfidenzintervalle die gleiche Einheit wie die abhängige Variable und können daher direkt interpretiert werden. Im vorliegenden Fall sollte besprochen werden, welche Bedeutung ein Koeffizient von <span class="math inline">\(\beta_1 = 0.7\)</span> bzw. von <span class="math inline">\(\beta_1 = 0.8\)</span> für die Interpretation des Modells hat. In unserem konkreten Fall würde eine Erhöhung der Anlaufgeschwindigkeit um <span class="math inline">\(1~\text{m/s}\)</span> zu einer Verbesserung zwischen <span class="math inline">\(0.7~\text{m}\)</span> und <span class="math inline">\(0.8~\text{m}\)</span> führen.</p>
<p>Noch einmal zu erwähnen ist, dass die beiden Parameter <span class="math inline">\(\hat{\beta}_0\)</span> und <span class="math inline">\(\hat{\beta}_1\)</span>, welche die Regressionsgerade beschreiben, Schätzer für die Parameter aus einer Population sind. In dieser beschreiben <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> den zugrunde liegenden Zusammenhang zwischen den beiden Variablen. Diese Betrachtung ist parallel zu derjenigen, wenn wir z.B. anhand des Mittelwerts <span class="math inline">\(\bar{x}\)</span> den wahren Populationsmittelwert <span class="math inline">\(\mu\)</span> versuchen zu schätzen. D.h., wir haben eine Populationsregressionsgerade, die wir mit Hilfe der Daten versuchen zu schätzen. Die <em>wahre</em> Regressionsgerade werden wir jedoch niemals mit 100%-iger Sicherheit bestimmen können – ebenso wenig, wie wir den Populationsmittelwert <span class="math inline">\(\mu\)</span> nicht mittels <span class="math inline">\(\bar{x}\)</span> exakt bestimmen können.</p>
</section>
<section id="weiteres-material" class="level2" data-number="4.11">
<h2 data-number="4.11" class="anchored" data-anchor-id="weiteres-material"><span class="header-section-number">4.11</span> Weiteres Material</h2>
<p>Eine schnelle Zusammenfassung ist in <span class="citation" data-cites="pos_simple_regression">Altman und Krzywinski (<a href="references.html#ref-pos_simple_regression" role="doc-biblioref">2015</a>)</span> zu finden, während <span class="citation" data-cites="kutner2005">Kutner u.&nbsp;a. (<a href="references.html#ref-kutner2005" role="doc-biblioref">2005</a>)</span> die Lineare Regression detailliert herleitet. Für die hier behandelten Themen ist vor allem Abschnitt (S.40–48) relevant.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-pos_simple_regression" class="csl-entry" role="listitem">
Altman, Naomi, und Martin Krzywinski. 2015. <span>„Points of Significance: Simple linear regression.“</span> <em>Nature methods</em> 12 (11).
</div>
<div id="ref-gauss1887" class="csl-entry" role="listitem">
Gauss, Carl Friedrich. 1887. <em>Abhandlungen zur Methode der kleinsten Quadrate</em>. P. Stankiewicz.
</div>
<div id="ref-hursh1939" class="csl-entry" role="listitem">
Hursh, J. B. 1939. <span>„Conduction velocity and diameter of nerve fibers“</span>. <em>American Journal of Physiology</em> 127 (1): 131–39. <a href="https://doi.org/10.1152/ajplegacy.1939.127.1.131">https://doi.org/10.1152/ajplegacy.1939.127.1.131</a>.
</div>
<div id="ref-kutner2005" class="csl-entry" role="listitem">
Kutner, Michael H, Christopher J Nachtsheim, John Neter, und William Li. 2005. <em>Applied Linear Statistical Models</em>. 5. Aufl. McGraw-Hill Irwin New York.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Im folgenden Snippet werden die Werte auf zwei Kommastellen mit <code>round()</code> der besseren Darstellung wegen gerundet.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./slm_title.html" class="pagination-link" aria-label="Das einfache Regressionmodell">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Das einfache Regressionmodell</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./slm_model_fit.html" class="pagination-link" aria-label="Modellfit">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modellfit</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>